### ISSUE TITLE
Intent of extended JsDoc mode

### ISSUE THREAD

**Issue by sramam** [vega/ts-json-schema-generator#10]
I'd like to better understand the intent of the three JsDoc modes: none/Basic/Extended.

Atleast for my purpose, I'd like them to behave like so:

- none: do not use JsDoc annotations (only use what the type system gives you?)
- basic: only use spec compliant annotations
- extended: allow non-standard annotations

But it seems this is not how things work.

**Comment by domoritz** [comment]
The original was designed by @mrix. I am mostly using `extended` for my project.

**Comment by sramam** [comment]
Extended mode as implemented currently does not render custom annotations. 

At the moment, I have a working implementation for extended mode as defined in the issue.

https://github.com/sramam/typescript-to-json-schema/commit/daa2316f9e0e03a44ba8bef23b32903814857c6f

Wondering if there is any appetite for a PR on this?

**Comment by domoritz** [comment]
Can you show me a concrete use case for custom annotations? I'm definitely interested in this addition but I also want to be careful not too support as many options as https://github.com/YousefED/typescript-json-schema (I prefer good defaults) because too many options increase the surface area of this tool and make it harder to keep it bug-free as the number of required tests grows exponentially. Having said that, changing how annotations get parsed should only affect a few tests.

**Comment by sramam** [comment]
As I see it, property attributes are used to communicate information between (sub) systems. 

At a base level, type and value/validation attributes suffice. Which is what the JSON schema does.
However, even the spec allows for extensions, http://json-schema.org/latest/json-schema-core.html#rfc.section.6.4.

In my system, I want to keep more information in the annotations. Something as simple as 
a default validator + a customized validator. Basically, both have to be satisfied for the
validation to succeed.

The default validator is needed for the underlying system to function. The customized version
is created by the user. The underlying system cannot rely on the customized one being correct
for it's needs. That safety property is a requirement of my system. JSON schema's custom format capabilities make the validation constraints easy to manage.

But for all this to work, I need custom properties to carry the information needed between
subsystems.

Without boring you with details of my system, one way to think of my need is that 
an Out-Of-The-Box schema represents the core system. The user can customize it,
as long as the core constraints are satisfied. Since every user can do this, I need 
a simple way to provide my users the flexibility while maintaining my sanity.

That last paragraph was a whole bunch of hand-waving, hopefully it makes some sense.
Happy to explain more - but it will have to be off-thread. It's mostly non-proprietary, but
way too much context for this thread.

**Comment by domoritz** [comment]
That makes a lot of sense to me. Thanks for the explanation.
