### ISSUE TITLE
Referencing HTMLElement type causes null-reference error in TypeofNodeParser

### ISSUE THREAD

**Issue by thw0rted** [vega/ts-json-schema-generator#1016]
I spent a bunch of time trying to debug an error I'm running into while trying to start using this project, and have boiled the issue down to [as minimal a repro as I can](https://github.com/thw0rted/issue-examples/tree/ts-schema).  The error is:

```text
TypeError: Cannot read property 'kind' of undefined
    at Object.isEnumDeclaration (...node_modules\typescript\lib\typescript.js:28259:21)
    at TypeofNodeParser.createType (...node_modules\ts-json-schema-generator\dist\src\NodeParser\TypeofNodeParser.js:26:34)        
```

I've gotten as far as stopping the debugger [here](https://github.com/vega/ts-json-schema-generator/blob/next/src/NodeParser/TypeofNodeParser.ts#L25), and what's happening is that the incoming `node` is a reference to `globalThis` (no idea why!), which results in a `symbol` with no `valueDeclaration`.  Your non-null assertion operator makes the code compile but there's a runtime error when the (undefined) `valueDec` is passed to `ts.isEnumDeclaration`.

EDIT: I was totally wrong about the cause in my original writeup.  The problem was that, several levels deep, I was trying to use a class with a property that is typed as `HTMLElement`.  I've updated the repro to show how including this type causes a stackdump, just run `generate-foo`.

----

Also, using the `ConstructorParamters` helper type causes `Error: Unknown node "ConstructorParameters<typeof Entity>" (ts.SyntaxKind = 178)` -- run the `generate-bar` script in the repro to see this behavior.  I looked it up and that's `SyntaxKind.ConstructorType`.  Is `ConstructorParameters` unsupported?  If so, is there some way I can annotate the type declaration so that it just gets replaced by `any` or `unknown`?  I'm not actually trying to include the `ConstructorParameters` type itself in the schema, but rather the keys of an object whose *values* have the constructor options-object type.

(I can file a separate issue about `ConstructorParameters` if needed.)

**Comment by sonokoh** [comment]
I ran into the same problem. Looks like the parser tries to convert every property in HTMLElement recursively, which eventually attempts to convert `globalThis`.
I didn't need HTMLElement in my exported schema, so I just tweaked the parser to ignore it.

Custom parser classes:
```ts
import { BaseType, Context, NeverType, ReferenceType, TypeReferenceNodeParser, UnionNodeParser, UnionType, notNever, ts } from "ts-json-schema-generator";

export class ExcludingTypeUnionNodeParser extends UnionNodeParser {
  excludedTypeNames: string[] = []
  constructor(excludedTypeNames: string[], ...args: ConstructorParameters<typeof UnionNodeParser>) {
    super(...args);
    this.excludedTypeNames = excludedTypeNames
}

  createType(node: ts.UnionTypeNode, context: Context, reference?: ReferenceType): BaseType {
      const types = node.types
      .filter(i => {
          const type = this.typeChecker.getTypeAtLocation(i);
          const symbol = type.getSymbol();
          if (symbol == null) return true
          const fullyQualifiedName = this.typeChecker.getFullyQualifiedName(symbol);
          return !this.excludedTypeNames.includes(fullyQualifiedName)
      })
      .map((subnode) => {
          return this.childNodeParser.createType(subnode, context);
      })
      .filter(notNever);

  if (types.length === 1) {
      return types[0];
  } else if (types.length === 0) {
      return new NeverType();
  }

  return new UnionType(types);
  }
}

export class ExcludingTypeReferenceNodeParser extends TypeReferenceNodeParser {
  excludedTypeNames: string[] = []
  constructor(excludedTypeNames: string[], ...args: ConstructorParameters<typeof TypeReferenceNodeParser>) {
      super(...args);
      this.excludedTypeNames = excludedTypeNames
  }
  
  createType(node: ts.TypeReferenceNode, context: Context): BaseType {
    const type = this.typeChecker.getTypeAtLocation(node);
    const symbol = type.getSymbol();
    if (symbol != null) {
      const fullyQualifiedName = this.typeChecker.getFullyQualifiedName(symbol);
      if (this.excludedTypeNames.includes(fullyQualifiedName)) {
          return new NeverType();
      }
    }
      return super.createType(node, context);
  };
}
```

Then register it:
```ts
const parser = createParser(program, config, (prs) => {
    prs.addNodeParser(new ExcludingTypeUnionNodeParser(['HTMLElement', 'Element'], program.getTypeChecker(), prs as ChainNodeParser));
    prs.addNodeParser(new ExcludingTypeReferenceNodeParser(['HTMLElement', 'Element'], program.getTypeChecker(), prs as ChainNodeParser));
});
```

That removed the error for me. But I'd love to learn better ways to solve this.
