### ISSUE TITLE
how to rename definition name while parsing

### ISSUE THREAD

**Issue by Nishchit14** [vega/ts-json-schema-generator#1020]
I use `I` as a prefix to declare an interface name for our type system. but I need to remove that `I` prefix while we prepare our json-schema from .ts file.

Here is my `url.ts`
```ts
interface IUrl {

}
```
**its outcome in json-schema is**
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/IUrl",
  "definitions": {
    "IUrl": {}
  }
}
```

**the desired outcome is** 

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/url",
  "definitions": {
    "url": {}
  }
}
```

is there anyway to achieve it?

**Comment by domoritz** [comment]
You could post-process the json or update this library.

I'll close this as there is no action item for me here.
