### ISSUE TITLE
Crash on a recursive interface with an intersection type at root

### ISSUE THREAD

**Issue by tuner** [vega/ts-json-schema-generator#1038]
Hi

I have a simple recursive interface and I'd like to have additional properties at the root. However, the following crashes in `removeUnreachable.ts`:

```ts
export interface Container {
    children: Container[];
}

export type Dummy = {
    x: number;
};

export type Intersection = Container & Dummy;
```

I commented out the call to `removeUnreachable()` to see what's going on. When using `Container` as root, everything looks good:

```json
{
  "$ref": "#/definitions/Container",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Container": {
      "additionalProperties": false,
      "properties": {
        "children": {
          "items": {
            "$ref": "#/definitions/Container"
          },
          "type": "array"
        }
      },
      "required": [
        "children"
      ],
      "type": "object"
    }
  }
}
```

However, when using `Intersection` as root, no definition for `Container` is present. The `children` reference becomes invalid and causes a crash in [`addReachable()`](https://github.com/vega/ts-json-schema-generator/blob/fb2d238a2a12d911119348ac45110d50d5ffd52b/src/Utils/removeUnreachable.ts#L14). 

```json
{
  "$ref": "#/definitions/Intersection",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Intersection": {
      "additionalProperties": false,
      "properties": {
        "children": {
          "items": {
            "$ref": "#/definitions/Container"
          },
          "type": "array"
        },
        "x": {
          "type": "number"
        }
      },
      "required": [
        "children",
        "x"
      ],
      "type": "object"
    }
  }
}
```

Schema generator seems to do some merging to intersections types and prunes unnecessary stuff. I'm not too familiar with that. It's doing something a bit too eagerly. I could try to fix this if I get some hints on how to proceed. Thanks!

**Comment by domoritz** [comment]
Try adding breakpoints and step through the execution. I'm not sure what's going wrong here but there seems to be a bug.

**Comment by tuner** [comment]
Yeh, did that already in `addReachable()`. Maybe I'll continue stepping if you don't have any obvious culprits to suggest. Thanks.

**Comment by domoritz** [comment]
I know we have some logic for merge objects in type intersections and I think you are right that we are pruning something we shouldn't be pruning. It could either happen in the parsing phase or when we generate the JSON schema later.
