### ISSUE TITLE
Error while rendering RecursivePartial type

### ISSUE THREAD

**Issue by matteobruni** [vega/ts-json-schema-generator#1075]
I migrated from `typescript-json-schema` because it wasn't working anymore. I set up everything to create a schema from an interface (too big to be pasted here, this is the [link](https://github.com/matteobruni/tsparticles/blob/dev/engine/src/Options/Interfaces/IOptions.ts) for reference).

But when I run the executable I got this error:

``` shell
$ ts-json-schema-generator --path 'src/**/*.ts' --type 'IOptions' -f tsconfig.schema.json --additional-properties true --out ./schema/options.schema.json
Error: Unknown node "{" (ts.SyntaxKind = 188) at ***/tsparticles/engine/src/Types/RecursivePartial.ts(4,34)
error Command failed with exit code 1.
```

*RecursivePartial.ts* (can be seen in the link provided above)

``` typescript
/**
 * @category Types
 */
export type RecursivePartial<T> = {
    [P in keyof T]?: T[P] extends (infer U)[]
        ? RecursivePartial<U>[]
        : T[P] extends object | undefined
        ? RecursivePartial<T[P]>
        : T[P];
};
```

**Comment by domoritz** [comment]
Can you go through the debugger and check what ts.SyntaxKind 188 is?

**Comment by matteobruni** [comment]
I don’t know how to debug that, but I’ve searched the enum on the TypeScript source code, and it should be ConditionalType

**Comment by domoritz** [comment]
The readme explains how to debug. The error usually means that we haven't implemented the appropriate node parser.

**Comment by domoritz** [comment]
Done in https://github.com/vega/ts-json-schema-generator/pull/1265
