### ISSUE TITLE
JSDoc interface level being ignored

### ISSUE THREAD

**Issue by then3rdman** [vega/ts-json-schema-generator#1096]
I am not sure if i am doing something wrong but I can not for the life of me make the JSDoc on the interface, at least not as i expect.

```typescript
/**
 * Description goes here
 * @customEmptyAnnotation
 * @id Address
 */
export interface Address {
  /**
   * @format uuid
   * */
  id: string;
  line1: string;
  city: string;
  state: string;
  postcode: string;
  country: string;
}
```
gives the following output 

```json
{
  "$ref": "#/definitions/Address",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Address": {
      "additionalProperties": false,
      "description": "Description goes here",
      "properties": {
        "city": {
          "type": "string"
        },
        "country": {
          "type": "string"
        },
        "line1": {
          "type": "string"
        },
        "postcode": {
          "type": "string"
        },
        "state": {
          "type": "string"
        }
      },
      "required": [
        "line1",
        "city",
        "state",
        "postcode",
        "country"
      ],
      "type": "object"
    }
  }
}
```

The description works but nothing else does.

Using @next and running the following command.
`ts-json-schema-generator -p index.ts -o out.json`

I am hoping this is just a miss-understanding on my part as otherwise this is a major issue with the tool that seemingly no oneis aware of?

**Comment by then3rdman** [comment]
After spending some time digging, I have discovered a few things.

`symbol.getJsDocTag()` returns the tags WITHOUT the leading $, so `$id` is returned as just `id`. I am assuming that this might have been a change in a version of TS  (i did a very brief search but couldn't confirm this). Also I know that this was changed in JSON schema spec version.

Additionally it would seem that text tags array in the `BasicAnnotationsReader` is missing some of the usable keywords. Is this intentional?

**Comment by domoritz** [comment]
Good find. 

The missing names might just be because json schema has added new names that we didn't keep up with.

**Comment by then3rdman** [comment]
I will put in a pull request soon that has a complete list of keywords and accounts for the missing $.

**Comment by domoritz** [comment]
Thank you. It's probably in https://github.com/vega/ts-json-schema-generator/blob/next/src/AnnotationsReader/BasicAnnotationsReader.ts.
