### ISSUE TITLE
broken with TypeScript version 2.5(RC)

### ISSUE THREAD

**Issue by sramam** [vega/ts-json-schema-generator#11]
Based on a preliminary analysis, TypeScript 2.5 (RC) will break schema generation. 

Specifically, it boils down to how we detect types that are exported:
https://github.com/vega/typescript-to-json-schema/blob/master/src/SchemaGenerator.ts#L65

TypeScript@2.5+ breaks this logic with this change:
https://github.com/Microsoft/TypeScript/commit/c6a6467073387dc657471e8eb2349f2bb2d0f4f7

**Comment by domoritz** [comment]
Thanks for raising this issue. I will wait for the official release to switch over to 2.5. it doesn't look like the changes in ts are fundamentally breaking any assumptions.

**Comment by domoritz** [comment]
Looks like I can just use`"exportSymbol" in symbol`.
