### ISSUE TITLE
Update to draft-07

### ISSUE THREAD

**Issue by kayahr** [vega/ts-json-schema-generator#110]
The draft-06 JSON schemas generated by ts-json-schema-generator are not accepted by [AJV](https://www.npmjs.com/package/ajv) without further configuration to tell AJV to support the old schema format or changing the schema URL manually after generation.

Would be nice if ts-json-schema-generator generated draft-07 schemas directly so I don't have to workaround this problem.

The [release notes of draft-07](https://json-schema.org/draft-07/json-schema-release-notes.html) says "In terms of validation keywords and outcomes, it is fully backwards-compatible with draft-06" so I guess this is a simple search/replace and no code needs to be changed? I tried this in my own fork, all tests are still running and the generated schema is now working out-of-the-box with AJV.

**Comment by domoritz** [comment]
Happy to merge a PR. Please make sure the keyword list is updated accordingly.
