### ISSUE TITLE
Allow to prioritize files when searching for types

### ISSUE THREAD

**Issue by marcoqu** [vega/ts-json-schema-generator#111]
I know this was already discussed in the past, when looking to optimize speed. There was even a working pull request #60 by @bywo that was closed, hardcoding a priority to anything that is not included in "node_modules".  
I would like to discuss this again, as in my [use case](https://marketplace.visualstudio.com/items?itemName=marcoq.vscode-typescript-to-json-schema) I need to disambiguate what specific type I want to convert, and in a given project there might be more than one type with the same name, in different files.  
As in my extension the user activates `ts-json-schema-generator` with reference to a specific file, the ability to prioritize files when searching for types would greatly help. At the moment I'm implementing the ability in a fork, but I would love to depend on the original library.

**Comment by domoritz** [comment]
I think there are two separate issues. Prioritization to speed up the parsing and correctly parsing different types with the same name.

Let's separate those and address them separately. Please open a new issue so we can discuss proposed solutions.
