### ISSUE TITLE
Add an option to minify the output.

### ISSUE THREAD

**Issue by arthurfiorette** [vega/ts-json-schema-generator#1120]
This line is formatting the json schema output. I have some files generated by this tool with 5K+ lines, and just by not formatting the output, i can reduce around 2K lines.

https://github.com/vega/ts-json-schema-generator/blob/1f22dda8ec2ec9470788da0f5b2129ca692bf611/ts-json-schema-generator.ts#L64

An option `--no-format` can resolve this issue.

**Comment by domoritz** [comment]
Could you post process the json or use the generator programmatically? 

I'd be happy to review a pull request.

**Comment by arthurfiorette** [comment]
In my environment, post processing would require a lot of work :)

I'll take the time to do a PR, I just don't promise to be today.
