### ISSUE TITLE
Intersections do not properly merge property types

### ISSUE THREAD

**Issue by kayahr** [vega/ts-json-schema-generator#115]
When creating an intersection of two types which have the same properties but with different types these types are not properly merged.

Example:

```typescript
interface A {
  x: boolean;
}

interface B {
  x: true;
}

export type C = A & B;
```

The generated schema now must only allow `true`as value for `x` but instead it also allows `false` because it simply required a boolean. It works when swapping the type to `B & A`. Looks like the left type always wins when both types define the same property.

Another example:

```typescript
interface A {
  x: { a: number; };
}

interface B {
  x: { b: number; };
}

export type C = A & B;
```

The generated schema now only allows the property `a` under `x` but it must also allow `b`. Swapping the type to `B & A` doesn't help in this case because then only `b` is allowed.

**Comment by domoritz** [comment]
Our implementation is still not correct: https://github.com/vega/ts-json-schema-generator/issues/181
