### ISSUE TITLE
Support the type "never"

### ISSUE THREAD

**Issue by hmil** [vega/ts-json-schema-generator#1152]
Currently, ts-json-schema-generator doesn't produce anything for the type "never".

The use-case I have is for the type `Record<string, never>`, which is recommended by `typescript-eslint` for when an object has no properties.
Though in general, having support for never wouldn't hurt anyways.

My first instinct would be to use the schema [false](https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-01#section-4.3.1) which means "Always fails validation". However, boolean schemas are not currently possible because ts-json-schema-generator represents schemas with the type `JSONSchema7` instead of `JSONSchema7Definition` (see @types/json-schema).

As an alternative, we can use the schema `{ "not": {} }` which has the same effect (though the spec recommends to use a boolean schema over this form).

**Comment by domoritz** [comment]
Just so I understand, having never in the schema basically means a definition is invalid. Shouldn't that mean that we remove it from the schema?

**Comment by hmil** [comment]
No I don't think so. `never` is a useful type which we can use in some circumstances (as shown with the use case in OP). 

For instance, how would you represent an object with "all keys except some"?

In JSON-schema, I'd go with:
```
{
  "type": "object",
  "properties": {
    "exceptThisOne": false
  }
  "additionalProperties": true
}
```

[In TypeScript](https://www.typescriptlang.org/play?#code/DYUwLgBAhgXBDeAoCKIGs4DsQDcQCdEBfCAMgQgG0MIBnMfAS0wHMBdOKTATxIF4IOAPaMAJhAAM0WtB4BuRIigA6NBAEAiKACMAxhoUrt6iBtG4DiIA):
```
{
    exceptThisOne: never;
} & {
    [k: string]: any;
}
```

`never` in TS and `false` in JSON schema appear to work the same way and fulfill the same role of a "bottom type", just the same way that `any` and `true` are analogous.


As a matter of fact, I think `UnionType.normalize` should be updated to return NeverType when the union is empty, because this is how TypeScript behaves.

**Comment by domoritz** [comment]
Makes sense. I think we used undefined for this so far but it's not complete (see https://github.com/vega/ts-json-schema-generator/pull/1154#issuecomment-1064304918).
