### ISSUE TITLE
Extending InterfaceAndClassNodeParser

### ISSUE THREAD

**Issue by loopingz** [vega/ts-json-schema-generator#1160]
When trying to extend the parser `InterfaceAndClassNodeParser`, I had to duplicate it instead of extending as most methods are `private` and not `protected`.

The use case is to define specific override for some specific classes so the schema generator have some preset behavior for my framework classes.

I'm about to send a PR to change this from `private` to `protected`, would it make sense to you?

**Comment by domoritz** [comment]
That's okay with me as long as all classes are consistent.

**Comment by loopingz** [comment]
Ok I did update all `NodeParser` and `TypeFormatter`, I left `Type` and the classes that were using private and had getter for the private attributes
