### ISSUE TITLE
Unknown Node Error (x4)

### ISSUE THREAD

**Issue by switchupcb** [vega/ts-json-schema-generator#1179]
All of the referenced files for this issue can be viewed here: [unconverted](https://github.com/switchupcb/discord-api-spec/tree/main/v9/unconverted).

Attempting to convert these files results in an Unknown node error:
```ts
unconverted\gateway\v9.ts: Error: Unknown node "shard_id: number
unconverted\payloads\v9\gateway.ts: Error: Unknown node "current_size: number
unconverted\payloads\v9\_interactions\modalSubmit.ts: Error: Unknown node " `${Locale}`
unconverted\rest\common.ts: Error: Unknown node " `${Locale}`
unconverted\rest\v9\oauth2.ts: Error: Unknown node " `${string}${' ' | '%20'}${OAuth2Scopes.Bot}`
```

Are any of these already being worked on and how does one fix each? https://github.com/vega/ts-json-schema-generator/issues/828 hints at these issues being solved by handling the node through the AST.

## Fix

Here are all of the issues regarding Unknown Nodes: https://github.com/vega/ts-json-schema-generator/issues?q=is%3Aissue+is%3Aopen+unknown

**Problematic Nodes (from the above output):**
All of the following nodes are fields.

[shard_id](https://github.com/switchupcb/discord-api-spec/blob/main/v9/unconverted/gateway/v9.ts#L413)
```
shard?: [shard_id: number, shard_count: number];
```

[current_size: number](https://github.com/switchupcb/discord-api-spec/blob/main/v9/unconverted/payloads/v9/gateway.ts#L277)
```
size?: [current_size: number, max_size: number];
```

[${Locale}](https://github.com/switchupcb/discord-api-spec/blob/main/v9/unconverted/payloads/v9/_interactions/modalSubmit.ts)
```
Locale not present in the file.
```
Perhaps refers to a file such as this one: [common.ts](https://github.com/discordjs/discord-api-types/blob/main/rest/common.ts).

[${string}${' ' | '%20'}${OAuth2Scopes.Bot}](https://github.com/switchupcb/discord-api-spec/blob/main/v9/unconverted/rest/v9/oauth2.ts#L115)
```
scope:
		| OAuth2Scopes.Bot
		| `${string}${' ' | '%20'}${OAuth2Scopes.Bot}`
		| `${OAuth2Scopes.Bot}${' ' | '%20'}${string}`
		| `${string}${' ' | '%20'}${OAuth2Scopes.Bot}${string}${' ' | '%20'}`;
```
Similar: https://github.com/vega/ts-json-schema-generator/issues/1041

**Comment by domoritz** [comment]
Please scope the issue down to a minimal example.

**Comment by switchupcb** [comment]
@domoritz I can create 5 issues separately but don't want to spam. Is this what you're asking for?

**Comment by domoritz** [comment]
No, please try to debug what the issue is. If these are different instances of the same issue, create a minimal reproduction.

**Comment by switchupcb** [comment]
Isolated the issues. [Reproducible Example](https://github.com/vega/ts-json-schema-generator#programmatic-usage) replace path with the individual file.

**Comment by domoritz** [comment]
Can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the issue?
