### ISSUE TITLE
<> in TS file causing generation of numbers

### ISSUE THREAD

**Issue by switchupcb** [vega/ts-json-schema-generator#1180]
Using `<` or `>` results in the JSON using an (escaped HTML?) long list of numbers when used with a structure. In this example,  `AddUndefinedToPossiblyUndefinedPropertiesOfInterface<...>` becomes `AddUndefinedToPossiblyUndefinedPropertiesOfInterface%3Cstructure-1933299398-663-915-1933299398-609-916-1933299398-470-917-1933299398-0-1648%3E","description":"https://discord.com/developers/docs/resources/emoji#create-guild-emoji-json-params"},"AddUndefinedToPossiblyUndefinedPropertiesOfInterface<structure-1933299398-663-915-1933299398-609-916-1933299398-470-917-1933299398-0-1648`

Reference JSON: https://raw.githubusercontent.com/switchupcb/discord-api-spec/main/v9/json/rest/v9/emoji.json
TypeScript
```ts
/**
 * https://discord.com/developers/docs/resources/emoji#create-guild-emoji-json-params
 */
export type RESTPostAPIGuildEmojiJSONBody = AddUndefinedToPossiblyUndefinedPropertiesOfInterface<{
	/**
	 * Name of the emoji
	 */
	name: string;
	/**
	 * The 128x128 emoji image
	 *
	 * https://discord.com/developers/docs/reference#image-data
	 */
	image: string;
	/**
	 * Roles for which this emoji will be whitelisted
	 */
	roles?: Snowflake[];
}>;
```

**Comment by domoritz** [comment]
Yep, that's the is we auto generate because there is no know alias. I think this is working as intended.

**Comment by switchupcb** [comment]
Is there a way to provide an alias programmatically?

**Comment by domoritz** [comment]
Can you try adding a type for the generic param.
