### ISSUE TITLE
`typeof {value}` throws when generating schema

### ISSUE THREAD

**Issue by Magellol** [vega/ts-json-schema-generator#12]
Hey guys.

I'm trying to use a constant value as string literal types for an interface such as the following. Although it throws with the following output `Cannot read property 'type' of undefined`.

```javascript
const FOO = 'foo';

interface Bar {
  value: typeof FOO;
};
```

I was wondering if you'd knew what might cause that. Or am I trying to use something that isn't supported by this library? Thanks!

**Comment by domoritz** [comment]
I think I just haven't tested this case. If you send me a pull request with a test case, I will fix the test case.

**Comment by Magellol** [comment]
Opened #14 :)
