### ISSUE TITLE
Changelog usage

### ISSUE THREAD

**Issue by MrWook** [vega/ts-json-schema-generator#1206]
I wanted to update my packages and saw that this package went to 1.0.0 recently. Unfortunately there is no direct changelog about this major release.
The tag for this release states that the CI was skipped for some reason and the changelog inside the different branches are older than 5 month. The default branch is even 9 month old.
One could go into the 1.0.0 tag and see the changelog. With the comparison  feature one could even see the different between the 1.0.0 tag and older ones.

What i want to say is, it would be nice if the changelog of the default branch is up to date or/and the release page is correctly used instead of skipped.

**Comment by jvanoostveen** [comment]
I also check the release version on npm with the version mentioned in the repository to see if it might be a hijacked version (better safe than sorry). Currently there seems to be a mismatch with the published version and what is specified in the repository.

**Comment by domoritz** [comment]
Changelogs are supposed to be in releases but I had a branch hook failure in https://github.com/vega/ts-json-schema-generator/runs/5630512608?check_suite_focus=true so we didn't get one. @hydrosquall do you have an idea how we can retroactively get the changelog?

**Comment by hydrosquall** [comment]
> @hydrosquall do you have an idea how we can retroactively get the changelog?

Yes- I think this can be used to generate the text of the changelog between arbitrary release tags.

> auto changelog --from v0.20.1 --to v0.21.0

https://intuit.github.io/auto/docs/generated/changelog#examples

Once we have this, it can be pasted into the release notes when manually creating a release from https://github.com/vega/ts-json-schema-generator/releases/tag/v1.0.0

It also looks like a release wasn't created for [0.98](https://github.com/vega/ts-json-schema-generator/releases/tag/v0.98.0), so we could potentially create a release for that too.

**Comment by domoritz** [comment]
Can you try? I'm not able to run the command locally. 

<img width="953" alt="Screen Shot 2022-04-04 at 18 53 15" src="https://user-images.githubusercontent.com/589034/161645549-3c0fdbd8-e278-489a-a770-dbc5a810c491.png">

**Comment by hydrosquall** [comment]
Sure, what I did was make a new [PAT](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) which only had access to public repos, then pasted REDACTED into the script below. I also repeated this for the `0.97.0` to `.98.0` jumps.

```bash
GH_TOKEN=REDACTED yarn run auto changelog --from v0.98.0 --to v1.0.0
```

You then get this:

- -  - 

 :tada: This release contains work from new contributors! :tada:

Thanks for all your work!

:heart: Hadrien Milano ([@hmil](https://github.com/hmil))

:heart: Remi Cattiau ([@loopingz](https://github.com/loopingz))

:heart: Jason Dent ([@Jason3S](https://github.com/Jason3S))

:heart: Tom Mrazauskas ([@mrazauskas](https://github.com/mrazauskas))

#### 💥 Breaking Change


#### 🚀 Enhancement

- feat: support key remapping via `as` [#1174](https://github.com/vega/ts-json-schema-generator/pull/1174) ([@Jason3S](https://github.com/Jason3S))
- feat: support intrinsic string manipulation types [#1173](https://github.com/vega/ts-json-schema-generator/pull/1173) ([@Jason3S](https://github.com/Jason3S))
- feat: support template literals as types. [#1171](https://github.com/vega/ts-json-schema-generator/pull/1171) ([@Jason3S](https://github.com/Jason3S))
- feat: move private to protected to allow extending behavior [#1161](https://github.com/vega/ts-json-schema-generator/pull/1161) ([@loopingz](https://github.com/loopingz))
- feat: add support for never type [#1154](https://github.com/vega/ts-json-schema-generator/pull/1154) ([@hmil](https://github.com/hmil))

#### 🐛 Bug Fix

- feat!: allow JSDoc tags without explicit value (e.g. `@deprecated`) to default to `true` [#1172](https://github.com/vega/ts-json-schema-generator/pull/1172) ([@mrazauskas](https://github.com/mrazauskas))

#### 🔩 Dependency Updates

- chore(deps-dev): bump @typescript-eslint/eslint-plugin from 5.14.0 to 5.15.0 [#1164](https://github.com/vega/ts-json-schema-generator/pull/1164) ([@dependabot[bot]](https://github.com/dependabot[bot]))
- chore(deps-dev): bump @babel/core from 7.17.5 to 7.17.8 [#1162](https://github.com/vega/ts-json-schema-generator/pull/1162) ([@dependabot[bot]](https://github.com/dependabot[bot]))
- chore(deps-dev): bump auto from 10.34.1 to 10.34.2 [#1163](https://github.com/vega/ts-json-schema-generator/pull/1163) ([@dependabot[bot]](https://github.com/dependabot[bot]))
- chore(deps-dev): bump prettier from 2.5.1 to 2.6.0 [#1165](https://github.com/vega/ts-json-schema-generator/pull/1165) ([@dependabot[bot]](https://github.com/dependabot[bot]))
- chore(deps): bump @types/json-schema from 7.0.9 to 7.0.10 [#1166](https://github.com/vega/ts-json-schema-generator/pull/1166) ([@dependabot[bot]](https://github.com/dependabot[bot]))
- chore(deps-dev): bump @auto-it/conventional-commits from 10.34.1 to 10.34.2 [#1167](https://github.com/vega/ts-json-schema-generator/pull/1167) ([@dependabot[bot]](https://github.com/dependabot[bot]))
- chore(deps-dev): bump @typescript-eslint/parser from 5.14.0 to 5.15.0 [#1168](https://github.com/vega/ts-json-schema-generator/pull/1168) ([@dependabot[bot]](https://github.com/dependabot[bot]))
- chore(deps): bump commander from 9.0.0 to 9.1.0 [#1169](https://github.com/vega/ts-json-schema-generator/pull/1169) ([@dependabot[bot]](https://github.com/dependabot[bot]))
- chore(deps-dev): bump @auto-it/first-time-contributor from 10.34.1 to 10.34.2 [#1170](https://github.com/vega/ts-json-schema-generator/pull/1170) ([@dependabot[bot]](https://github.com/dependabot[bot]))
- chore(deps-dev): bump @typescript-eslint/eslint-plugin from 5.13.0 to 5.14.0 [#1157](https://github.com/vega/ts-json-schema-generator/pull/1157) ([@dependabot[bot]](https://github.com/dependabot[bot]))
- chore(deps-dev): bump vega from 5.21.0 to 5.22.0 [#1156](https://github.com/vega/ts-json-schema-generator/pull/1156) ([@dependabot[bot]](https://github.com/dependabot[bot]))
- chore(deps-dev): bump @typescript-eslint/parser from 5.13.0 to 5.14.0 [#1158](https://github.com/vega/ts-json-schema-generator/pull/1158) ([@dependabot[bot]](https://github.com/dependabot[bot]))
- chore(deps-dev): bump eslint from 8.10.0 to 8.11.0 [#1159](https://github.com/vega/ts-json-schema-generator/pull/1159) ([@dependabot[bot]](https://github.com/dependabot[bot]))
- chore(deps-dev): bump @typescript-eslint/parser from 5.12.1 to 5.13.0 [#1144](https://github.com/vega/ts-json-schema-generator/pull/1144) ([@dependabot[bot]](https://github.com/dependabot[bot]))
- chore(deps-dev): bump auto from 10.32.6 to 10.34.1 [#1145](https://github.com/vega/ts-json-schema-generator/pull/1145) ([@dependabot[bot]](https://github.com/dependabot[bot]))
- chore(deps-dev): bump @typescript-eslint/eslint-plugin from 5.12.1 to 5.13.0 [#1146](https://github.com/vega/ts-json-schema-generator/pull/1146) ([@dependabot[bot]](https://github.com/dependabot[bot]))
- chore(deps-dev): bump ts-node from 10.5.0 to 10.7.0 [#1147](https://github.com/vega/ts-json-schema-generator/pull/1147) ([@dependabot[bot]](https://github.com/dependabot[bot]))
- chore(deps-dev): bump @auto-it/conventional-commits from 10.32.6 to 10.34.1 [#1148](https://github.com/vega/ts-json-schema-generator/pull/1148) ([@dependabot[bot]](https://github.com/dependabot[bot]))
- chore(deps): bump typescript from 4.5.5 to 4.6.2 [#1149](https://github.com/vega/ts-json-schema-generator/pull/1149) ([@dependabot[bot]](https://github.com/dependabot[bot]))
- chore(deps-dev): bump @auto-it/first-time-contributor from 10.32.6 to 10.34.1 [#1150](https://github.com/vega/ts-json-schema-generator/pull/1150) ([@dependabot[bot]](https://github.com/dependabot[bot]))
- chore(deps-dev): bump eslint-config-prettier from 8.4.0 to 8.5.0 [#1151](https://github.com/vega/ts-json-schema-generator/pull/1151) ([@dependabot[bot]](https://github.com/dependabot[bot]))
- chore(deps): bump actions/checkout from 2 to 3 [#1143](https://github.com/vega/ts-json-schema-generator/pull/1143) ([@dependabot[bot]](https://github.com/dependabot[bot]))
- chore(deps-dev): bump @typescript-eslint/eslint-plugin from 5.12.0 to 5.12.1 [#1139](https://github.com/vega/ts-json-schema-generator/pull/1139) ([@dependabot[bot]](https://github.com/dependabot[bot]))
- chore(deps-dev): bump eslint from 8.9.0 to 8.10.0 [#1138](https://github.com/vega/ts-json-schema-generator/pull/1138) ([@dependabot[bot]](https://github.com/dependabot[bot]))
- chore(deps-dev): bump @types/node from 17.0.18 to 17.0.21 [#1140](https://github.com/vega/ts-json-schema-generator/pull/1140) ([@dependabot[bot]](https://github.com/dependabot[bot]))
- chore(deps-dev): bump @types/jest from 27.4.0 to 27.4.1 [#1141](https://github.com/vega/ts-json-schema-generator/pull/1141) ([@dependabot[bot]](https://github.com/dependabot[bot]))
- chore(deps-dev): bump @typescript-eslint/parser from 5.12.0 to 5.12.1 [#1142](https://github.com/vega/ts-json-schema-generator/pull/1142) ([@dependabot[bot]](https://github.com/dependabot[bot]))
- chore(deps): bump actions/setup-node from 2.5.1 to 3 [#1137](https://github.com/vega/ts-json-schema-generator/pull/1137) ([@dependabot[bot]](https://github.com/dependabot[bot]))
- chore(deps-dev): bump @typescript-eslint/parser from 5.11.0 to 5.12.0 [#1132](https://github.com/vega/ts-json-schema-generator/pull/1132) ([@dependabot[bot]](https://github.com/dependabot[bot]))
- chore(deps-dev): bump @babel/core from 7.17.2 to 7.17.5 [#1133](https://github.com/vega/ts-json-schema-generator/pull/1133) ([@dependabot[bot]](https://github.com/dependabot[bot]))
- chore(deps-dev): bump @types/node from 17.0.17 to 17.0.18 [#1134](https://github.com/vega/ts-json-schema-generator/pull/1134) ([@dependabot[bot]](https://github.com/dependabot[bot]))
- chore(deps-dev): bump @typescript-eslint/eslint-plugin from 5.11.0 to 5.12.0 [#1135](https://github.com/vega/ts-json-schema-generator/pull/1135) ([@dependabot[bot]](https://github.com/dependabot[bot]))
- chore(deps-dev): bump eslint-config-prettier from 8.3.0 to 8.4.0 [#1136](https://github.com/vega/ts-json-schema-generator/pull/1136) ([@dependabot[bot]](https://github.com/dependabot[bot]))

#### Authors: 6

- [@dependabot[bot]](https://github.com/dependabot[bot])
- Dominik Moritz ([@domoritz](https://github.com/domoritz))
- Hadrien Milano ([@hmil](https://github.com/hmil))
- Jason Dent ([@Jason3S](https://github.com/Jason3S))
- Remi Cattiau ([@loopingz](https://github.com/loopingz))
- Tom Mrazauskas ([@mrazauskas](https://github.com/mrazauskas))

**Comment by hydrosquall** [comment]
Both changelogs are now up to date. I used the "create release from tag" feature in the Github UI to paste the markdown generated by the above commands into the following pages

- https://github.com/vega/ts-json-schema-generator/releases/tag/v0.98.0
- https://github.com/vega/ts-json-schema-generator/releases/tag/v1.0.0

**Comment by domoritz** [comment]
Thank you. Seems strange to me that auto needs a token but oh well.
