### ISSUE TITLE
Support remote schemas via `$ref`

### ISSUE THREAD

**Issue by hmil** [vega/ts-json-schema-generator#1207]
Sometimes, one may need to include a sub-schema without re-defining it completely, using the `$ref` attribute.

An example of such situation is if the object itself contains a json schema. One may want to avoid the overhead of inlining the entire JSON schema spec by using a direct reference to the schema's URL like so:

```json
    "MyObject": {
      "properties": {
        "nested": {
          "$ref": "http://json-schema.org/draft-07/schema#"
        }
      },
      "type": "object"
    }
```

## Suggestion

One convenient way to achieve this would be to support a JSDoc annotation for this purpose:

```ts
interface MyObject {
    /**
     * @ref http://json-schema.org/draft-07/schema#
     */
    nested: JSONSchema7;
}
```

**Comment by domoritz** [comment]
I'd consider a pull request for this.
