### ISSUE TITLE
Ability to specify multiple types for conversion in the CLI

### ISSUE THREAD

**Issue by broofa** [vega/ts-json-schema-generator#1223]
Two feature requests here, actually...

1. 'Would be great to be able to specify multiple `--type` flags in the CLI to generate a schema that included each of the types.  E.g. `ts-json-schema-generator ... -t Foo -t Bar -t Baz`
2. Similarly, it would be nice to be able to exclude multiple types when using `--type *`.  E.g. by supplying `--ignore <type>` or `--ignore <pattern>`.   The use case for this is that I have a file that I'd like to generate a schema for all of the declared types, however there's one type (that I don't need a schema for) that has a function property and is thus triggering  #560. So, instead, I find myself having to write a script that runs the generator separately for each individual type.

**Comment by acolby** [comment]
@broofa what were you able to do to work around this? I'm about to get pretty hacking and would really like a more elegant approach. The fallback being the string literal 'unknown' would be much better the the current behavior.

I'm willing to contribute some cycles to figure something out here

Appreciate you digging into this!

**Comment by broofa** [comment]
@acolby I ended up using the `typescript-json-schema` module. 🤷

Given there's been no response from any of the code owners, I'm going to close this out.

**Comment by domoritz** [comment]
I don't have the need for this feature but would be happy to review a pull request if someone wants this feature.

**Comment by acolby** [comment]
Thank @broofa and I totally get where you're coming from @domoritz . Thanks for the awesome project.

I was able to work around my issue by augmenting the parser with a fall back parser:

```js
    function _parsers(parser) {
      class FallbackNodeParser {
        supportsNode(node) {
          return true;
        }
      createType(node, context) {
          return new tsj.UnknownType();
        } 
      }

      parser.childNodeParser.nodeParsers.push(new FallbackNodeParser());
    }
```

**Comment by domoritz** [comment]
That's neat. Thanks for sharing the snippet.
