### ISSUE TITLE
Valid circular reference breaks parser(s)

### ISSUE THREAD

**Issue by filipomar** [vega/ts-json-schema-generator#1238]
Attempting to generate a schema breaks when running the generator based on the types below:

```typescript
type Alpha = { stringProp: string; betaStringProp: Beta['stringProp']; }
export type Beta = { stringProp: string; alphaStringProp: Alpha['stringProp']; }
```
This is the output:

```
Reference type not set yet

      32 |     public getType(): BaseType {
      33 |         if (this.type == null) {
    > 34 |             throw new Error("Reference type not set yet");
         |                   ^
      35 |         }
      36 |         return this.type;
      37 |     }
```

I tracked it down to the parser failing to unravel the object and failing, due to its type not being available as it needs itself to be resovled first.

Now, I already developed a working solution that deals with a very narrow set of problems (IndexAccess with a literal access type, just as the example above), but while trying to make the solution more generic, to support all possible types of recursion I hit a few snags.

In order to fix this particular problem, what do you find it makes more sense?
- Push the non generic solution on a PR
- Pass a reference around the parsers with a list of the actually needed types and implement the appropriate behaviour on each possible parser
- Something else entirely I am not seeing

**Comment by domoritz** [comment]
Hmm, good catch and great digging. I think a proper solution to the problem would be great. How would you propose to fix the issue by passing around the list of neeed types?
