### ISSUE TITLE
Recursive types with Omit types leads to Reference Type Not Set Yet error since v1.0.0

### ISSUE THREAD

**Issue by ssc-hrep3** [vega/ts-json-schema-generator#1276]
Hi there

First of all, thank you for maintaining this great library. I just found an issue, which only occurs in the most recent version v1.0.0. With v0.95, it worked without any problems. Here is an example of the issue:

```
export type Item = {
  type: 'item';
};
export type Group = {
  type: 'group';
  members: Member[];
};
type Member = { depth: number } & (Item | Group);
export type RootNoMembers = Item | Omit<Group, 'members'>;
```
The error says `Reference type not set yet`. I assume, it has something to do with the recursive type in combination with the union types and `Omit<>`.

The error does **not** occur when I remove the `Omit<Group, 'members'>` and replace it with an explicit type `{ type: 'group' }`.

Do you have any idea, what could be the root cause of this?

**Comment by domoritz** [comment]
Huh, thanks for the issue. Could you try cloning this repo and do a binary search to identify the commit that causes the issue? There should be an associated pull request.

**Comment by bettercalljason** [comment]
I did the binary search as suggested and found the commit that causes the issue: 653fa77da0ce844227aab6fd82302ba15feafe2d. And this is the associated pull request: #985.

Before that, it works fine. We would love to upgrade to the latest ts-json-schema-generator version but this issue prevents it 😢 

Do you have an idea what could be the issue?

**Comment by domoritz** [comment]
@joshkel could you take a look at this issue and whether it was introduced in your pull request?

**Comment by domoritz** [comment]
Even this simple case leads to issues

```ts
export type Geometry = GeometryCollection;

export interface GeometryCollection<G extends Geometry = Geometry> {
    geometries: G[];
}

export type Type = GeometryCollection;
```

**Comment by domoritz** [comment]
Actually this

```ts

export interface GeoJsonObject {
    type: GeometryCollection["type"];
}

export interface GeometryCollection extends GeoJsonObject {
    type: "GeometryCollection";
}

export type Type = GeometryCollection;
```
