### ISSUE TITLE
'No root type "<type name>" found' error (SOLVED)

### ISSUE THREAD

**Issue by broofa** [vega/ts-json-schema-generator#1287]
I'm trying to extract a schema for a type defined in a 3rd party module. Specifically, I have the following file that imports `FormattingOptions` from  the `stylus-supremacy` module...

${projectRoot}/app.ts:
```ts
import stylusSupremacy, { FormattingOptions } from 'stylus-supremacy';
export type FooType = FormattingOptions;  // HACK! To provide a local reference to the type
```
If I do `tsj.createGenerator({tsconfig: 'tsconfig.json', type: 'FormattingOptions'})`, the process fails with "No root type "FormattingOptions" found".

I get a similar error if I use `type: 'stylusSupremacy.FormattingOptions'`.
Ditto for `type: `stylus-supremacy.FormattingOptions`.

However if I use `type: 'FooType'`, it works.

I guess my question is this: Is there a way to point `tsj` at the `FormattingOptions` type directly, or do I have to explicitly `export type [some alias name] = FormattingOptions` in order to get this to work.  (FWIW, I don't seem to have this issue in other projects that have a similar code structure - i.e. that import `interface` types from 3rd party modules.  I'm able to generate schemas from those without issue.)

**Comment by broofa** [comment]
**Solved**

'Turns out `stylus-supremacy` is exporting it's types using the `StylusSupremacy` namespace.   Using `type: 'StylusSupremacy.FormattingOptions` fixed the problem.

(My apologies for the recent notification spam. Also, thank you for creating this module!  The learning curve has been a little bumpy on my end, but the end results are very impressive!   The generated schemas are surprisingly good.  I'm particularly impressed with the `description` information it generates, which I was not expecting.)

**Comment by domoritz** [comment]
Oh great. I'm glad you found a solution.
