### ISSUE TITLE
Translating constraints from TypeScript JSDoc comments

### ISSUE THREAD

**Issue by Zamiell** [vega/ts-json-schema-generator#1327]
In JSON schema land, it is possible to specify a [number constraint](https://json-schema.org/understanding-json-schema/reference/numeric.html) for a property like this:

```
{
  "type": "number",
  "minimum": 0,
  "maximum": 100
}
```

In TypeScript land, there is no analog for this - you just have to specify the type of the variable as a `number`. (Tangent: It's possible to specify the type as `0 | 1 | 2 | 3 | etc.` all the way up to 100, but this isn't feasible in most cases.)

However, in the same way that `ts-json-schema-generator` reads the JSDoc comment and copies over the description of the interface, it would also be nice for `ts-json-schema-generator` to read the JSDoc comment and copy over the minimum and maximum values, if present.

I'm imagining something like this:

```ts
export interface Foo {
  /**
   * This is value 1.
   */
  value1: number,

  /**
   * This is value 2.
   * @min 1
   * @max 5
   */
  value2: number,
}
```

Is this currently possible somehow?

**Comment by domoritz** [comment]
Yep. It should already work: https://github.com/vega/ts-json-schema-generator/blob/cdd587e5f8db4d68bd3eb74d0d805f1e2ac664e1/src/AnnotationsReader/BasicAnnotationsReader.ts#L24
