### ISSUE TITLE
Get definition names for each node passed through `SchemaGenerator.createSchemaFromNodes`.

### ISSUE THREAD

**Issue by arthurfiorette** [vega/ts-json-schema-generator#1338]
I'm creating a custom cli application that already is parsing the code, that means I already have a `ts.Program`.

I'm currently using `SchemaGenerator.createSchemaFromNodes(nodesIAlreadyFilteredOut)` which returns a json schema of them. How can I find a specific json definition within the returned schema?

This exemplifies what I'm trying to do.

```ts
const nodes [..., nodeB, ...];

const schema = SchemaGenerator.createSchemaFromNodes(nodes);

// get the generated definition $id for nodeB.
const NAME = ?;

const nodeBDefinition = schema.definitions[NAME];
```

I don't care about the implementation, so anything should do. Since it will be executed at compile time.

Thanks!

**Comment by arthurfiorette** [comment]
@domoritz, is this possible?

**Comment by domoritz** [comment]
The names are inferred automatically for each type. I'd have to look through the code to see whether we store the mapping from node to name directly. Feel free to poke around. 

Closing as there is no immediate action item.
