### ISSUE TITLE
Class constructor properties are unaccounted for

### ISSUE THREAD

**Issue by sparebytes** [vega/ts-json-schema-generator#134]
Input:
```ts
export class DataBox {
    constructor(public data: string) {}
}
```

Output:
```js
{
  "$ref": "#/definitions/DataBox",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "DataBox": {
      "additionalProperties": false,
      "type": "object"
    }
  }
}
```

Expected:
```json
{
  "$ref": "#/definitions/DataBox",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "DataBox": {
      "additionalProperties": false,
      "properties": {
        "data": {
          "type": "string"
        }
      },
      "required": ["data"],
      "type": "object"
    }
  }
}
```

P.S. Sorry for the barrage of issues today. Attempting to integrate this into a large codebase and 95% of the scenarios I've encountered are already accounted for. This is that 5%

**Comment by domoritz** [comment]
This is a tricky one because we use the AST to generate the schema. 

Maybe we should remove support for classes since it isn't implemented correctly right now. 

I won't have cycles to fix this but I am happy to review a PR.

**Comment by sparebytes** [comment]
My vote is to keep what support there is and make a note where it falls short. The existing class support is significantly helping me with the refactor I'm doing. I doubt anyone expects classes to be first class citizens in the JSON Schema world anyway.

I'd love to help out so if I get a moment I'll see what I can do.

**Comment by domoritz** [comment]
👍 Looking forward to some PRs.

**Comment by kayahr** [comment]
@sparebytes Hope you didn't started with it already because I'm currently working on it and I'm nearly done.
