### ISSUE TITLE
Pass custom annotations to schema

### ISSUE THREAD

**Issue by sergei-dyshel** [vega/ts-json-schema-generator#1340]
I'm using TJS to generate a format which is superset of JSON schema. My JSDoc annotations contain some fields that I want to be automatically propagated to resulting schema.

For example, I want this code
```typescript
/**
 * some escription
 * @myvar myvalue
 */
key: string;
```

To generate the following schema:
```json
{
  "key": {
    "type": "string",
    "description": "some escription",
    "myvar": "myvalue",
  }
}
```

Currently I work around it by using custom fork where I change `BasicAnnotationsReader.textTags` to contain my custom flow, but this is too much hassle - since TSJ apparently doesn't support installing from github I have to run `yarn pack` and install TJS locally from resulting archive...

I would be nice to be able to do this without modifying the code.

**Comment by SeanKeenan-at** [comment]
I believe you can use [extraTags](https://github.com/vega/ts-json-schema-generator/blob/2a67697969c5396f6d1abd15880e13b310bbf109/src/Config.ts#L14), or --validationKeywords. See #246, along with [these tests](https://github.com/vega/ts-json-schema-generator/blob/cdd587e5f8db4d68bd3eb74d0d805f1e2ac664e1/test/valid-data-annotations.test.ts#L4-L14)
