### ISSUE TITLE
CLI fails to parse anything (Solved : Types have to be exported!)

### ISSUE THREAD

**Issue by Aderinom** [vega/ts-json-schema-generator#1375]
Platform : Windows 10
NodeVer : v17.9.0
ts-json-schema-generator Ver : 1.0.0
file.ts:
`
interface b {
  a: number;
}
`

Command :  `npx ts-json-schema-generator --path .\file.ts`
Outputs : 
`{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {}
}`

Command :  `npx ts-json-schema-generator --path .\file.ts -t b`
Outputs :  `Error: No root type "b" found`

Also tried with passing the tsconfig file as argument as well as trying with using the bin from node_modules directly.

**Comment by domoritz** [comment]
Can you add an export to the interface and try again?

**Comment by Aderinom** [comment]
> Not exported types, interfaces, enums are not exposed in the definitions section in the JSON schema

Oops. Thank you!
