### ISSUE TITLE
Publish-auto is failing

### ISSUE THREAD

**Issue by SeanKeenan-at** [vega/ts-json-schema-generator#1389]
It appears as if the underlying issue is with [auto](https://github.com/intuit/auto/issues/2248).

[See here for the first publish-auto that is failing](https://github.com/vega/ts-json-schema-generator/runs/6745375187?check_suite_focus=true). (Which seems unrelated to the auto issue).

The issue does reproduce locally (for me) if you run `yarn release`.

The impact of this is that `next` is not being kept up to date

**Comment by domoritz** [comment]
Yeah, I've seen it. It seems to be an issue with ts-node and the latest ts version (@hydrosquall found that: https://github.com/microsoft/TypeScript/issues/49257#issuecomment-1140632708). 

I filed https://github.com/intuit/auto/issues/2242 but no response so far. 

I don't want to roll back ts if I can avoid it so I've been just waiting.

**Comment by mohd-akram** [comment]
Might be able to use Yarn's [selective dependency resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) to override this.

**Comment by domoritz** [comment]
Updating ts-node did not help unfortunately.

**Comment by mohd-akram** [comment]
Per the [log](https://github.com/vega/ts-json-schema-generator/actions/runs/3091182660/jobs/5000940227), it seems this is due to an internal dependency of `auto` having an [outdated](https://github.com/EndemolShineGroup/cosmiconfig-typescript-loader/blob/v3.0.2/package.json#L44) ts-node.

**Comment by domoritz** [comment]
https://github.com/vega/ts-json-schema-generator/blob/next/yarn.lock#L73 looks like it's new enough. Where are you seeing an old version?

**Comment by hydrosquall** [comment]
I think @mohd-akram may be flagging the error  `cosmiconfig-typescript-loader`, which is a dependency of `auto`

https://github.com/vega/ts-json-schema-generator/blob/896292f9fb088b173a4c35ff562bf6788d908f0c/yarn.lock#L1100

In general, `yarn why` can be used to find out how many versions of a dependency are present, and how they came to be included.

![image](https://user-images.githubusercontent.com/9020979/191396620-1fe7c1cf-efd7-4db1-a02c-fbd4679b625c.png)


The resolutions approach he proposed may work, but there's another option:  this dependency is only being activated when it we write our config file in TS

https://github.com/vega/ts-json-schema-generator/blob/next/auto.config.ts

I think if we convert the config file to a JSON file (like https://github.com/vega/vega-lite/blob/next/.autorc.json ), and/or use selective resolution to resolve ts-node to 10^ across the board, we should be able to bypass any troubles created by the old version. 

Opened a PR to convert the config file to see if that's enough: https://github.com/vega/ts-json-schema-generator/pull/1413

**Comment by domoritz** [comment]
Looks like it's mostly fixed now. Thank you @hydrosquall!
