### ISSUE TITLE
Classes with default values don't work

### ISSUE THREAD

**Issue by Zamiell** [vega/ts-json-schema-generator#1390]
Hello, and thanks for the tool.

Unfortunately, classes seem to be broken. For example:

#### `foo.ts`
```ts
export class Foo {
  field1 = "someValue";
  field2?: string;
}
```

Feeding this file to `ts-json-schema-generator` will result in a schema that looks like this:

#### `foo-schema.json`
```json
{
  "$ref": "#/definitions/Foo",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Foo": {
      "additionalProperties": false,
      "properties": {
        "field2": {
          "type": "string"
        }
      },
      "type": "object"
    }
  }
}
```

As you can see, `field1` is completely missing and only `field2` is listed. It seems like the tool skips over any fields that are defined with a default value, which makes it mostly useless for people who want to generate a schema from a class. :(

**Comment by domoritz** [comment]
Good catch. Can you send a fix?

**Comment by Zamiell** [comment]
Sorry, I don't have the time. If you can fix it, I'd be greatly appreciative. Otherwise, I guess I will try to find a separate tool that works with classes. :(

**Comment by ThatOneAwkwardGuy** [comment]
Had a look, the type appears to get lost in the InterfaceAndClassNodeParser file, due to the
```
member.type
```
check, inside of
```
 .filter((member) => isPublic(member) && !isStatic(member) && member.type && !isNodeHidden(member))
```

doing this is an intermediary fix:
```
export class Foo {
  field1:string = "someValue";
  field2?: string;
}
```

Is this overly verbose? yup. But don't have enough experience with the codebase to solve this one.

update: #1407 should fix this

**Comment by domoritz** [comment]
Done with https://github.com/vega/ts-json-schema-generator/pull/1407
