### ISSUE TITLE
Upgrading from 1.0.0 to 1.1.0 causes `"additionalProperties": false` to be dropped.

### ISSUE THREAD

**Issue by Jason3S** [vega/ts-json-schema-generator#1416]
This is a preliminary report.

I'll investigate further to provide a simple repo case.

Using `git bisect`, the issue started with #1367

**Comment by Jason3S** [comment]
@daanboer,

I'll take a looks at the cause, but maybe you have an idea why `additionalProperties` gets dropped from some types.

**Comment by domoritz** [comment]
Good catch. Thanks for looking into it. I can make a new release when we have a fix.

**Comment by jscheid** [comment]
I'm commenting here but it might be an unrelated issue: just upgraded to 1.1.0 and getting lots of errors, with crazy deep nesting levels (hundreds of levels deep). This is at the top level:

```
Argument of type 'Draft<Immutable<TObservedState>>' is not assignable to parameter of type 'Objectish'.
```

The Draft and Immutable types come from the immer package.

**Comment by daanboer** [comment]
@Jason3S I am currently a bit short on time, but I can take a look if you provide a minimal example.

**Comment by Jason3S** [comment]
@daanboer,

I found the cause and have a quick fix. But, there might be some improvement.

Cause: Hidden types become NeverType and `NeverType.additionalProperties` is `undefined` by definition.

https://github.com/vega/ts-json-schema-generator/blob/065ac274946d33e153cff4eeecd52c889b45993b/src/NodeParser/HiddenTypeNodeParser.ts#L16

When combined with other types, `additionalProperties` bleeds into the final type:

https://github.com/vega/ts-json-schema-generator/blob/065ac274946d33e153cff4eeecd52c889b45993b/src/Utils/allOfDefinition.ts#L87-L92

Possible fix:

```ts
        if (
            (other.additionalProperties || other.additionalProperties === undefined) &&
            definition.additionalProperties == false &&
            !(baseType instanceof NeverType)
        ) {
            delete definition.additionalProperties;
        }

``` 

But a better fix might be to make a `HiddenType` that extends `NeverType` and a `HiddenTypeFormatter`:

```ts
export class HiddenTypeFormatter implements SubTypeFormatter {
    public supportsType(type: HiddenType): boolean {
        return type instanceof HiddenType;
    }
    public getDefinition(type: HiddenType): Definition {
        return { not: {}, additionalProperties: false };
    }
    public getChildren(type: HiddenType): BaseType[] {
        return [];
    }
}
```

**Comment by daanboer** [comment]
@Jason3S Nice find, personally I think it makes sense to introduce a `HiddenType`. However, I don't know whether it will need special casing in other regions of the code. Also, you can omit the `not: {}` in the return of `getDefinition` as `additionalProperties` is `false` anyway (and it just clutters the generated schema).

**Comment by Jason3S** [comment]
@domoritz,

Thank you for releasing 1.1.1.

**Comment by domoritz** [comment]
Thanks for the fix
