### ISSUE TITLE
Regression: Schema generated for referenced type seems to be wrong

### ISSUE THREAD

**Issue by andreashuber69** [vega/ts-json-schema-generator#144]
Please see [this commit](https://github.com/vega/ts-json-schema-generator/pull/135/commits/3941f0df441f205940e9da1b5ad4d21af7c9d5c3) for details.

This was introduced with a fairly recent change, because I did get the expected result with 0.47. @domoritz @kayahr Does this ring a bell? If not, I'll try to find the offending commit.

**Comment by domoritz** [comment]
Not immediately, no. Would be great to know what broke it.

**Comment by kayahr** [comment]
WASN'T ME! :) Well, it was me... Fix is incoming.
