### ISSUE TITLE
Configuration so that Optional Fields Allow null Values

### ISSUE THREAD

**Issue by Kkoile** [vega/ts-json-schema-generator#1446]
When having a typescript type with an optional value like the following:
```typescript
type MyType = {
 fieldA?: string;
}
```
it results in the following schema:
```json
{
  "$ref": "#/definitions/REF-0",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "REF-0": {
      "type": "object",
      "properties": {
        "fieldA": {
          "type": "string"
        }
      },
      "required": []
    }
  }
}
```
The problem is that the json schema validators I found so far don't allow `{fieldA: null}` for this json schema. In order to allow for `null` values the json schema would need to like this:
```json
{
  "$ref": "#/definitions/REF-0",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "REF-0": {
      "type": "object",
      "properties": {
        "fieldA": {
          "type": ["string", "null"]
        }
      },
      "required": []
    }
  }
}
```
I know that I can generate this schema by adjusting the typescript type to the following:
```typescript
type MyType = {
 fieldA?: string | null;
}
```
But I was wondering whether there is a way to configure optional values to automatically accept `null` as type?
Thanks for you help!

**Comment by domoritz** [comment]
Since that's now the semantics of Typescript, I don't think we should implement this. 

<img width="774" alt="Screenshot 2022-10-21 at 08 51 32" src="https://user-images.githubusercontent.com/589034/197212055-65e18730-84cb-4e01-8921-84e74af724cf.png">

**Comment by Kkoile** [comment]
I can understand your decision not to directly implement this requirement. I was also more looking for a way to extend this project so that the resulting schema can be manipulated.
After some experimenting I found it out on my own, by extending the `ObjectTypeFormatter`. This is what I did:
```ts
import { createFormatter, ObjectTypeFormatter, BaseType, ObjectProperty, UnionType, NullType } from "ts-json-schema-generator";

export class MyObjectTypeFormatter extends ObjectTypeFormatter {
  protected prepareObjectProperty(property: ObjectProperty): ObjectProperty {
    let propertyToUse = property;
    if (!property.isRequired()) {
      const types: BaseType[] = [];
      if (property.getType() instanceof UnionType) {
        types.push(...(property.getType() as UnionType).getTypes());
      } else {
        types.push(property.getType()!);
      }
      if (!types.find((type) => type instanceof NullType)) {
        types.push(new NullType());
      }
      propertyToUse = new ObjectProperty(property.getName(), new UnionType(types), property.isRequired());
    }
    return super.prepareObjectProperty(propertyToUse);
  }
}

// registering
const formatter = createFormatter(config, (ftm, circularReferenceTypeFormatter) => {
  ftm.addTypeFormatter(new MyObjectTypeFormatter(circularReferenceTypeFormatter));
});
```
@domoritz do you see any obvious flaws or edge cases I missed with my solution? It works with all of my test cases.
Feedback would be highly appreciated :-)
