### ISSUE TITLE
Cannot find module '.svg' 

### ISSUE THREAD

**Issue by erkin98** [vega/ts-json-schema-generator#1491]
Cannot find module './gti-logo-gray.svg' or its corresponding type declarations.
I created `custom.d.ts` file with following content and added to include field in tsconfig, it returns same result
![image](https://user-images.githubusercontent.com/20378722/206209507-a664b58f-abb7-46ad-9955-5abc1e4b9710.png)

**Comment by domoritz** [comment]
This doesn't look like an issue with this project. Please clarify and I can reopen.
