### ISSUE TITLE
Generating a json schema for functions in classes

### ISSUE THREAD

**Issue by rubenwolterbeek** [vega/ts-json-schema-generator#1495]
I am working on a Builder for a typescript sdk library and I am trying to extract all the sdk classes with their respective functions into a json that the Builder can use.

I am trying to accomplish this:
```
export class Form {
  propA?: string
  propB?: string

  funcA(value: boolean, text: string) {
     ....
  }
}
```

to
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Form": {
      "type": "object",
      "properties": {
        "propA": {
          "type": "string"
        },
        "propB": {
          "type": "string"
        },
        "NamedParameters<typeof funcA>": {
          "type": "object",
          "properties": {
            "value": {
              "type": "boolean"
            },
            "text": {
              "type": "string"
            }
          },
          "required": [
            "value",
            "text"
          ],
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    }
  }
}
```
But there seems to be no way to accomplish this. I saw some other issues on this topic, specifically [#98](https://github.com/vega/ts-json-schema-generator/issues/98) and #733 but both refer just to individual functions, not functions in classes.

Is there a way I can implement this myself or does anyone know an alternative?

**Comment by domoritz** [comment]
Individual functions and functions in classes are the same (in terms of feature for this generator), no?

**Comment by domoritz** [comment]
Closing since JSON schema has no official function support and we have discussed how to extend the generator in previous issues.

**Comment by rubenwolterbeek** [comment]
You are right, but what do I need to do to make the generator recognise functions in classes instead of skipping over them? I can't find the right place to modify the framework

**Comment by domoritz** [comment]
Probably somewhere in https://github.com/vega/ts-json-schema-generator/blob/next/src/NodeParser/InterfaceAndClassNodeParser.ts#L110 is a good point to put a breakpoint and to then step through the execution.

**Comment by rubenwolterbeek** [comment]
I think I made it work. If someone else finds this issue, my solution is in my fork of the library: https://github.com/The-TNT-Guy/ts-json-schema-generator. It's not pretty, but it works

Thank you for the fast reply @domoritz!
