### ISSUE TITLE
Schema generation fails for code containing keyof typeof enum

### ISSUE THREAD

**Issue by andreashuber69** [vega/ts-json-schema-generator#153]
Please see this PR: https://github.com/vega/ts-json-schema-generator/pull/152

It appears the problem lies in the fact that `TypeofNodeParser.createType` does not anticipate that the object returned by `symbol.valueDeclaration` neither has a `type` nor an `initializer` property.

**Comment by kayahr** [comment]
Looks easy to fix. I guess it would be a good idea to get rid of this `any` cast in this parser as well and use the `ts.is*()` type guards instead and then properly implement handing of enum declarations which is missing currently. I can give it a try.

@domoritz With this any-cast the code currently catches all nodes which might have a `type` or `initializer` property. The tests only cover variable declaration and property signature nodes so the tests are satisfied when explicitly checking for these two kind of nodes (And I don't know if there are more node types possible for typeof). In my opinion this is a cleaner approach but it might cause trouble for use cases which are not yet covered by tests but when someone reports this then it would be very easy to fix by just adding another type guard call (and a new test for this case). Any objections?

**Comment by andreashuber69** [comment]
> I guess it would be a good idea to get rid of this `any` cast in this parser as well and use the `ts.is*()` type guards instead 

Couldn't agree more, `any` casts should not be necessary in properly typed code.

Thanks for taking a shot at this, BTW. I looked into fixing this myself, but failed to find any hints how this can be implemented.

**Comment by domoritz** [comment]
The `any` casts are there because I wanted to make things work and the fewer we have, the better.

**Comment by andreashuber69** [comment]
Thank you, works as expected with enums declared in the same file. It fails however with an enum declared in a different file, see linked PR.
