### ISSUE TITLE
Support TypeScript 4.9 `satisfies` operator

### ISSUE THREAD

**Issue by GrantGryczan** [vega/ts-json-schema-generator#1532]
Creating a validator for a type that includes the `satisfies` operator causes an `UnknownNodeError` on the expression of kind `SatisfiesExpression`.

Ideally, `x satisfies y` should be treated the same as `x`.

**Comment by domoritz** [comment]
I guess we need to do some simplification in the parsing step here. Can you send a pull request?

**Comment by amyjko** [comment]
I ran into this today. I'll work on a pull request.
