### ISSUE TITLE
Properly process JSDoc descriptions

### ISSUE THREAD

**Issue by remcohaszing** [vega/ts-json-schema-generator#1544]
JSDoc descriptions use markdown. JSON schema descriptions use plain text, their format is undefined. It may represent just raw text, but it’s also often allowed to use markdown.

#514 broke markdown formatting. #697 resolves one specific symptom, but several situations are broken. For example I ran into this, because code blocks are broken.

The correct solution would be to parse the JSDoc as markdown, and strip meaningless newlines only. This should be pretty straight-forward using [remark](https://github.com/remarkjs/remark). Note that the remark ecosystem only exposes ESM packages. This means `ts-json-schema-generator` would need to move to native ESM to support it.

**Comment by domoritz** [comment]
Thanks for raising the issue. I think moving to ESM is fine as long as node supports it well enough so that we don't have to change the cli. Would you be open to send a pull request?

**Comment by remcohaszing** [comment]
Node.js 12 and greater support ESM fine. Users of the CLI won’t be affected, but users who `require()` the library will be. This is definitely semver major. IMO it would be nice to combine this with the update to TypeScript 5.

I have changed my mind a bit on the matter of handling newlines though. `remark` will output equivalent markdown, but not formatted the same as the input. So this might have even more unexpected side effects.

I have a new proposal. Given the following JSDoc:

```js
/**
 * This is markdown text, including **strong**, _emphasis_,
 * and `code`.
 *
 * ```js
 * console.log('Also markdown code blocks')
 * ```
 */
```

There will be an new option `processDescription`, which has 3 options:

`keep` (default) will keep the original description as-is.

```js
{
  description: `This is markdown text, including **strong**, _emphasis_,
and \`code\`.

\`\`\`js
console.log('Also markdown code blocks')
\`\`\``
}
```

`trim` will strip all formatting using [`mdast-util-to-string`](https://github.com/syntax-tree/mdast-util-to-string)

```js
{
  description: 'This is markdown text, including strong, emphasis, and code.'
}
```

`markdownDescription` will strip all formatting using [`mdast-util-to-string`](https://github.com/syntax-tree/mdast-util-to-string) in the description, but add a property `markdownDescription` that contains the original content with formatting. This non-standard property is used for example by VSCode.

```js
{
  description: 'This is markdown text, including strong, emphasis, and code.',
  markdownDescription: `This is markdown text, including **strong**, _emphasis_,
and `code`.

\`\`\`js
console.log('Also markdown code blocks')
\`\`\``
}
```

**Comment by remcohaszing** [comment]
> Would you be open to send a pull request?

Yes, but I want to make sure the solution we came up with is the right one. :)

**Comment by domoritz** [comment]
Would that mean that by default we would not touch the comment and keep multiple new lines? That would be a regression from current behavior, no?

**Comment by remcohaszing** [comment]
I would argue #508 / #514 caused a regression and reverting that behaviour is the fix.

Regardless, I think this option to allow the user to pick a behaviour suits most users. None of these options match the current behaviour, because current behaviour is to strip newlines without knowing context.

If this is going to be part of a major release, I wouldn’t worry too much about breaking old behaviour.

It’s also possible to choose another default. Also I’m not super happy with the names I came up with, suggestions are welcome.

**Comment by domoritz** [comment]
I'm not so worried about breaking behavior as long as Vega-Lite still works as expected. In general, I like to avoid config options as they increase the combinatorial space of what we need to test and maintain. I like having one good and smart option if possible.

**Comment by GeekyEggo** [comment]
+1 in favour of supporting `markdownDescription`.

I like the proposed solution from @remcohaszing, i.e. introducing a `--processDescription <keep|trim|markdownDescription>` option. If this were to be introduced as part of a major version, I would even consider suggesting the `"markdownDescription"` be the default behaviour, e.g. writing both the `description` and `markdownDescriptiono` fields. With JSDocs natively supporting Markdown, this would align well.
