### ISSUE TITLE
discriminator: simpler OpenAPI schema

### ISSUE THREAD

**Issue by mdesousa** [vega/ts-json-schema-generator#1551]
It looks like `ajv` now supports the OpenAPI [discriminator keyword](https://ajv.js.org/json-schema.html#discriminator), which seems to have better support and is a bit simpler than `if-then-else`.

```
{
  type: "object",
  discriminator: {propertyName: "foo"},
  required: ["foo"],
  oneOf: [
    {
      properties: {
        foo: {const: "x"},
        a: {type: "string"},
      },
      required: ["a"],
    },
    {
      properties: {
        foo: {enum: ["y", "z"]},
        b: {type: "string"},
      },
      required: ["b"],
    },
  ],
}
```

@daanboer @domoritz @mvanniekerkSQ  i know you have been contributing to this feature (thanks for that by the way!)
how do you feel about switching to this approach?

**Comment by domoritz** [comment]
I think we need to wait for others like vscode to catch up and support it before we can use it. This also doesn't seem like an official json schema property, right? I'd be okay with adding it as an additional hint but not to replace existing logic at this point.

**Comment by mdesousa** [comment]
you are right... even though ajv is supporting it, it's not json schema yet... it's in the OpenAPI spec. the additional hint sounds like a good option 👍
