### ISSUE TITLE
Multiple definition error with generic types

### ISSUE THREAD

**Issue by tommitytom** [vega/ts-json-schema-generator#161]
When using the new mode where you don't have to specify a type, generics that are defined multiple times cause an error.  Test case:

`test.ts`:
```
export interface Foo<T> {}

export interface Bar {
	item: Foo<string>;
}

export interface Baz {
	item: Foo<string>;
}
```
Command line: `ts-json-schema-generator --path test.ts`
Error: `Error: Type "Foo<string>" has multiple definitions.`

Note that if I define a type that contains both, something like
```
export interface Both {
	v1: Bar;
	v2: Baz;
}
```
and run this on the command line: `ts-json-schema-generator --path test.ts --type Both` everything works as expected.

**Comment by domoritz** [comment]
That's definitely a bug. Would you be able to send a PR to fix it?

**Comment by domoritz** [comment]
The original example works now. 

```ts
export interface Foo<T> {}

export interface Bar {
    item: Foo<string>;
}

export interface Baz {
    item: Foo<string>;
}

export interface MyType {
    v1: Bar;
    v2: Baz;
}
```
