### ISSUE TITLE
jsdoc @example & @examples are both output into "examples" field

### ISSUE THREAD

**Issue by JoshuaCarter** [vega/ts-json-schema-generator#1619]
In short, I want pic below:

![Screenshot from 2023-03-28 16-42-16](https://user-images.githubusercontent.com/8869081/228139469-38fc5d26-5bed-4fb6-88fd-2078557ef1f8.png)

But can only have pic below:

![Screenshot from 2023-03-28 16-43-04](https://user-images.githubusercontent.com/8869081/228139540-6c921c9c-37ea-4594-8ff0-c5ad187d3766.png)

https://github.com/vega/ts-json-schema-generator/blob/fad197f4f32d070a9fb0e8228cbb98ee70d9f83c/src/AnnotationsReader/ExtendedAnnotationsReader.ts#L91-L94

Code above reads in the `@example` jsdoc field and outputs it as `examples: ...`. The `@examples` field seems to be automatically/generically output as the `examples: ...` field.

From what I can see, the `getExampleAnnotation` method should **not** read in the `@example` jsdoc field, and **should** read in the `@examples` jsdoc field. Or perhaps both should be explicitly handled?

**Comment by cedvdb** [comment]
@JoshuaCarter are you going to submit a PR ?


It seems to me it should return { example: examples[0] } at the end if there is only one example.

**Comment by arthurfiorette** [comment]
Closing this because of https://github.com/vega/ts-json-schema-generator/pull/1705#issuecomment-2133981951.

Feel free to reopen if needed
