### ISSUE TITLE
Inline imports aren't parsed correctly

### ISSUE THREAD

**Issue by stilic** [vega/ts-json-schema-generator#1644]
Hello!

I'm currently trying to implement `ts-json-schema-generator` on [a TypeScript project](https://github.com/Stilic/server/blob/openapi/scripts/schema.js).
I came accros an issue where inline imports can't be parsed like normal imports (they are considered as unknown nodes).

I attached a log in case you want to see how the error looks like:
[npm.txt](https://github.com/vega/ts-json-schema-generator/files/11247368/npm.txt)

**Comment by domoritz** [comment]
Thanks for the report. Can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the issue?

**Comment by stilic** [comment]
> Thanks for the report. Can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the issue?

I just made a repo that demonstrate the issue:
https://github.com/Stilic/tjsg-import-example
(use `npm run generate` to generate the schema).

**Comment by domoritz** [comment]
I see. Can you replace `import("./Banana")` with a traditional import?

**Comment by stilic** [comment]
I can, yes.

**Comment by domoritz** [comment]
Thanks for the issue and I'm glad there is a workaround

**Comment by stilic** [comment]
> Thanks for the issue and I'm glad there is a workaround

It works correctly with classic imports.
