### ISSUE TITLE
Ignore specific types

### ISSUE THREAD

**Issue by stilic** [vega/ts-json-schema-generator#1645]
I'm struggling with an issue where some useless types are detected and being added to the schema.
I am trying to make [my script](https://github.com/Stilic/server/blob/openapi/scripts/schema.js) able to skip the parsing of the types mentionned [here](https://github.com/vega/ts-json-schema-generator/files/11280593/npm.txt).
Is there a way to do that?

**Comment by domoritz** [comment]
Unfortunately we can't help with this issue. Please file a bug report with a minimal reproducible example.

**Comment by Stilic** [comment]
> 

I was asking a question. It isn't a bug in the library itself.
