### ISSUE TITLE
Force the program to ignore specific types

### ISSUE THREAD

**Issue by stilic** [vega/ts-json-schema-generator#1646]
Hi,
Is there a way to tell the program to skip the detection of certain types (such as the ones listed in [this array](https://github.com/Stilic/server/blob/e70cd75fe065ed5876c70dce4b41856e40db6f38/scripts/schema.js#L37))?

**Comment by domoritz** [comment]
You could try changing the types using a type macro. Otherwise, you'd maybe need to make a change to the code in this library to support skipping types.

**Comment by freedmand** [comment]
Could you clarify how a type macro approach would work? Also just wanted to chime in that the ability to ignore specific types, either with an annotation or regex-like option would be useful. If I have some spare time I could look at PR'ing

**Comment by domoritz** [comment]
My macro I meant a type that uses conditional types to exclude some other type (similar to `Omit`).
