### ISSUE TITLE
Type has multiple definitions when reused in union

### ISSUE THREAD

**Issue by lykahb** [vega/ts-json-schema-generator#166]
```
export type s = string
export type n = number
export type sn = s | n

Type "s" has multiple definitions.
```

I don't think this schema has name conflict. `sn` should only create a new name `sn` and get compiled into something like this

```
...
"sn": {"anyOf": [{"$ref": "#definitions/s"}, {"$ref": "#definitions/n"}]}
```

**Comment by domoritz** [comment]
Thanks for the bug report. Would you be able to debug it and send a PR?

**Comment by lykahb** [comment]
When children of `sn` are iterated, their ids match the past definitions. I do not have enough knowledge about the project to fix this. It looks like `appendRootChildDefinitions` logic would have to be rewritten. Also the `rootTypes` may need to hold more information about the type structure - whether the subtypes are referenced or inlined.

The rootTypes variable at `createSchema` is
```
[
  {
    "name": "s",
    "type": {
      "id": "alias-metadata.ts-0-23-metadata.ts-0-75",
      "type": {}
    }
  },
  {
    "name": "n",
    "type": {
      "id": "alias-metadata.ts-23-47-metadata.ts-0-75",
      "type": {}
    }
  },
  {
    "name": "sn",
    "type": {
      "id": "alias-metadata.ts-47-75-metadata.ts-0-75",
      "type": {
        "types": [
          {
            "name": "s",
            "type": {
              "id": "alias-metadata.ts-0-23-metadata.ts-0-75",
              "type": {}
            }
          },
          {
            "name": "n",
            "type": {
              "id": "alias-metadata.ts-23-47-metadata.ts-0-75",
              "type": {}
            }
          }
        ]
      }
    }
  }
]
```

**Comment by AndrewLeedham** [comment]
@lykahb Can you provide a repro or the options you are using. With the defaults, the outputted schema for:
```
export type s = string;
export type n = number;
export type sn = s | n;
```
is
```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$ref": "#/definitions/sn",
    "definitions": {
        "n": {
            "type": "number"
        },
        "s": {
            "type": "string"
        },
        "sn": {
            "anyOf": [
                {
                    "$ref": "#/definitions/s"
                },
                {
                    "$ref": "#/definitions/n"
                }
            ]
        }
    }
}
```
which seems right to me.

**Comment by lykahb** [comment]
@AndrewLeedham Your output is correct. I think the difference is that you are convert only `sn` type, whereas I ran it with `*`.

It is 0.51.0 from npm run with `npx ts-json-schema-generator --path test.ts --type '*'`

**Comment by slinkardbrandon** [comment]
I just ran into this as well, our team is creating several types & interfaces for exports.

While this issue exists we'll have to write the JSON schemas manually.

Can I provide any additional details to help point this in the right direction?

**Comment by domoritz** [comment]
A small test case would be great. Are you also using `*`? Since I don't use `*` myself, it would be great if you could try to send a PR to fix the issue.

**Comment by HoldYourWaffle** [comment]
I could *maybe* look into fixing this, but since I'm on a deadline right and need to learn the codebase first that could take some time.

A temporary workaround could be comparing the "already existing" schema definition with the newly generated one, only throwing an error if there's a mismatch.
Something like this:
```ts
// SchemaGenerator.ts around line 70

children.reduce((definitions, child) => {
	const name = child.getName();
	const newDef = this.typeFormatter.getDefinition(child.getType());
	if (name in definitions && JSON.stringify(definitions[name]) !== JSON.stringify(newDef)) {
		throw new Error(`Type "${name}" has multiple definitions.`);
	} else {
		definitions[name] = newDef;
	}
	return definitions;
}, childDefinitions);
```

**Comment by domoritz** [comment]
Great idea @HoldYourWaffle

**Comment by HoldYourWaffle** [comment]
I don't have the code in front of me now, but do you want me to create a PR with the above code changes?
If I remember correctly they functioned perfectly, although they definitely feel like a massive hack.

**Comment by domoritz** [comment]
I don't have any need for this right now so I'd rather wait for a proper fix.

**Comment by tommitytom** [comment]
Think it's the same issue as this: https://github.com/vega/ts-json-schema-generator/issues/161

**Comment by HoldYourWaffle** [comment]
That looks very similar indeed

**Comment by domoritz** [comment]
The original test case now works.

```ts
export type S = string;
export type N = number;
export type MyType = S | N;

```

```json
{
  "$ref": "#/definitions/MyType",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "MyType": {
      "anyOf": [
        {
          "$ref": "#/definitions/S"
        },
        {
          "$ref": "#/definitions/N"
        }
      ]
    },
    "N": {
      "type": "number"
    },
    "S": {
      "type": "string"
    }
  }
}
```
