### ISSUE TITLE
String property handling

### ISSUE THREAD

**Issue by AndrewLeedham** [vega/ts-json-schema-generator#167]
The current way that schema is generated for string properties seems wrong, properties that include non JS characters e.g. `-` have wrapping strings included in the outputted schema, for example the schema for:
```typescript
export interface Example {
    'with-dash': string;
    without: string;
}
```
would be generated as:
```json
{
  "$ref": "#/definitions/Example",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Example": {
      "additionalProperties": false,
      "properties": {
        "'with-dash'": {
          "type": "string"
        },
        "without": {
          "type": "string"
        }
      },
      "required": [
        "'with-dash'",
        "without"
      ],
      "type": "object"
    }
  }
}
```
Note that the `with-dash` property is stored as `'with-dash'` this is technically valid schema but would be for a property in JSON like `{"'with-dash'": "value"}`. I created a [minimal repro](https://github.com/AndrewLeedham/repros/tree/master/packages/ts-json-schema-generator-string-property) with the above code and found that [AJV](https://ajv.js.org/) did not like the schema outputted from this module, it needs `with-dash` not `'with-dash'`.

**Comment by domoritz** [comment]
Yep, that's a bug. Can you help debug and send a PR to fix it?
