### ISSUE TITLE
Expose parsing of a symbol

### ISSUE THREAD

**Issue by cedvdb** [vega/ts-json-schema-generator#1704]
For my use case I need to go from an AST Symbol to json schema. It seems like this library expects a file, it would be nice if a lower level `transformSymbolToJsonSchema(symbol: ts.Symbol)` or `transformNodeToJsonSchema(node: ts.Node)` was added.

Note: The symbol I'm trying to parse is an interface, but it might be generated and not actually live in a file.

**Comment by domoritz** [comment]
It's already supported: https://github.com/vega/ts-json-schema-generator/pull/1386.
