### ISSUE TITLE
Bun.sh support

### ISSUE THREAD

**Issue by janwilmake** [vega/ts-json-schema-generator#1733]
I recently migrated my entire project to [bun.sh](https://bun.sh) but I'm relying on ts-json-schema-generator for some JSON schema generation. However, many files return errors, and this is the one I keep seeing everywhere that I did not get in node.js:

```
TypeError: undefined is not an object (evaluating 'aliasedSymbol.declarations.filter')
```

It'd be great if anyone here could help me getting this to work in Bun. I don't understand much of this codebase, so I'm afraid I need some direction at least to make any PR's. Or if there's any workarounds, some help would be highly appreciated.

Edit: As a workaround, I've returned any in this scenario, so it doesn't crash. Check: https://github.com/vega/ts-json-schema-generator/pull/1737/files

**Comment by domoritz** [comment]
I don't think I have the cycles to support bun from my side but I'm happy to review prs that fix issues.

**Comment by janwilmake** [comment]
Fixed: https://github.com/vega/ts-json-schema-generator/pull/1737
