### ISSUE TITLE
Issue Generating JSON Schema for Types with Indexed Access References

### ISSUE THREAD

**Issue by hash004** [vega/ts-json-schema-generator#1768]
## Description

When attempting to generate a JSON schema for a TypeScript type that uses indexed access references from another file, `ts-json-schema-generator` does not produce the expected output. Instead, it returns a schema with an empty `not` object.

### `intermediary.ts`

```typescript
import { paths, components } from "./api";

export type MetadateDto = components["schemas"]["MetadateDto"];
```

### `api.d.ts`
```typescript
export interface components {
  schemas: {
    MetadateDto: {
      /** Format: uuid */
      id?: string;
      name?: string | null;
    };
  }
}
```

### Command Used:
```bash
npx ts-json-schema-generator --path './types/intermediary.ts' --type 'MetadateDto'
```
### Expected Output:
A valid JSON schema representing the MetadateDto type.
```json
{
  "$ref": "#/definitions/MetadateDto",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "MetadateDto": {
      "additionalProperties": false,
      "properties": {
        "id": {
          "description": "Format: uuid",
          "type": "string"
        },
        "name": {
          "type": [
            "string",
            "null"
          ]
        }
      },
      "type": "object"
    }
  }
}
```
### Actual Output:
```json
{
  "$ref": "#/definitions/MetadateDto",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "MetadateDto": {
      "not": {}
    }
  }
}
```

### Workaround
Flattening the type references (i.e., defining the type directly in intermediary.ts without referencing api.d.ts) does produce the expected schema. However, this is not a sustainable solution for larger projects with interrelated types.

**Comment by mariusflorescu** [comment]
any updates on this?

**Comment by mariusflorescu** [comment]
I have changed from `d.ts` file to a `.ts` file, and at least I get some error messages now.

`"'path' is referenced directly or indirectly in its own type annotation."`


`Property 'definitions' does not exist on type '((Without<(Without<{ path: any; op: "add" | "replace" | "test"; value: unknown; }, { path: any; op: "remove"; }> & { path: any; op: "remove"; }) | (Without<{ path: any; op: "remove"; }, { path: any; op: "add" | "replace" | "test"; value: unknown; }> & { ...; }), { ...; }> & { ...; }) | (Without<...> & ((Without<...>...'.`

**Comment by arthurfiorette** [comment]
Couldn't reproduce your issue at [2.3.0-next.2](https://www.npmjs.com/package/ts-json-schema-generator/v/2.3.0-next.2)
