### ISSUE TITLE
Support @required and $data annotations.

### ISSUE THREAD

**Issue by georeith** [vega/ts-json-schema-generator#1788]
I want to validate that my normalized data structure is correct and that every value in `steps` exists as a key in `stepDefinitions`:

```ts
export type UserTest {
   steps: string[];
  /**
   * @required { $data: "#/steps" }
   */
   stepDefinitions: Record<string, StepDefinition>;
}
```

However the `@required` tag is ignored although it is a base keyword in AJV for objects. If I enable it via `extraTags` I then get this error:

```
Error: schema is invalid: data/definitions/UserTest/properties/stepDefinitions/required must be array
```

Is what I'm trying to do possible with this library currently?

**Comment by domoritz** [comment]
Sorry, I don't have cycles to look into answering questions. If you want an enhancement to this library, can you send a pull request?

**Comment by georeith** [comment]
> Sorry, I don't have cycles to look into answering questions. If you want an enhancement to this library, can you send a pull request?

I'm trying to gauge whether it is an existing feature or not first as I couldn't find documentation on the tags and what syntax is supported. 

Maybe I could have framed the question better but there is no need to be snarky. I framed the question as a yes or no answer I'm not asking you to do my homework. 

By your response I presume it's no.

**Comment by georeith** [comment]
My bad this is working as I wanted as long as `"required"` is passed to `extraTags` the error above is an AJV validation issue, this is creating the Schema as I wanted. 👍

**Comment by domoritz** [comment]
Awesome. Your issue and question were totally valid btw. I wanted to give you a realistic expectation what I'll be able to do right now as I'll travel after next week. 

Is required a valid json schema tag? If yes, it might be correct to support it by default.

**Comment by georeith** [comment]
Thanks, sorry if I read too much into that it had been a long day and my question was confusing because I had conflated the AJV error as coming from this library which then confused me about what was/wasn't supported.

Yeah its a valid tag for `object`: https://json-schema.org/understanding-json-schema/reference/object#required

The usage of it with `{ $data: jsonPointer }` is an AJV specific thing as `$data` never made it into the official spec: https://github.com/json-schema-org/json-schema-spec/issues/51

I've made a PR to add it here: https://github.com/vega/ts-json-schema-generator/pull/1789 with some test cases for the above.
