### ISSUE TITLE
Incorrect schema for unions

### ISSUE THREAD

**Issue by domoritz** [vega/ts-json-schema-generator#181]
```ts
export interface Base {
    a: "hello" | "world";
}

export interface Base2 {
    a: "hello" | "typescript";
}

export type MyType = Base & Base2;

const a: MyType = {
    a: "world",
};
```

Actual:

```json
{
  "$ref": "#/definitions/MyType",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "MyType": {
      "additionalProperties": false,
      "properties": {
        "a": {
          "enum": [
            "hello",
            "typescript",
            "world"
          ],
          "type": "string"
        }
      },
      "required": [
        "a"
      ],
      "type": "object"
    }
  }
}
```

Expected

```json
{
  "$ref": "#/definitions/MyType",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "MyType": {
      "additionalProperties": false,
      "properties": {
        "a": {
          "enum": [
            "hello"
          ],
          "type": "string"
        }
      },
      "required": [
        "a"
      ],
      "type": "object"
    }
  }
}
```

**Comment by domoritz** [comment]
I think instead of concatenating arrays of values, we should use their intersection. This would be correct for type intersections and extend, I think.

**Comment by domoritz** [comment]
I think this is an example for https://github.com/vega/ts-json-schema-generator/issues/58.

**Comment by AndrewLeedham** [comment]
So it should essentially do an intersection i.e. https://lodash.com/docs/4.17.14#intersection for `IntersectionType`, concat for `UnionType` and take b's value when extending interfaces?

**Comment by domoritz** [comment]
For union types, we already generate

```
{
  "$ref": "#/definitions/MyType",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Base": {
      "additionalProperties": false,
      "properties": {
        "a": {
          "enum": [
            "hello",
            "world"
          ],
          "type": "string"
        }
      },
      "required": [
        "a"
      ],
      "type": "object"
    },
    "Base2": {
      "additionalProperties": false,
      "properties": {
        "a": {
          "enum": [
            "hello",
            "typescript"
          ],
          "type": "string"
        }
      },
      "required": [
        "a"
      ],
      "type": "object"
    },
    "MyType": {
      "anyOf": [
        {
          "$ref": "#/definitions/Base"
        },
        {
          "$ref": "#/definitions/Base2"
        }
      ]
    }
  }
}
```

I believe that is already correct.

**Comment by AndrewLeedham** [comment]
Correct so:

Union types are currently fine they do `array.concat`, but with rest:
https://github.com/vega/ts-json-schema-generator/blob/master/src/TypeFormatter/UnionTypeFormatter.ts#L44

Extending is currently fine as it take b via:
https://github.com/vega/ts-json-schema-generator/blob/master/src/TypeFormatter/ObjectTypeFormatter.ts#L25

However Intersection types are currently doing the same as Union types here:
https://github.com/vega/ts-json-schema-generator/blob/master/src/TypeFormatter/IntersectionTypeFormatter.ts#L22
So rather that passing `arrayConcat?: boolean` maybe it should be `arrayIntersection? boolean` and replace the `array.concat` behaviour with intersection like the lodash implementation.

**Comment by domoritz** [comment]
What if we always do an intersection? That should be correct for union types and for extending.

**Comment by domoritz** [comment]
I found another bug:

```ts
export interface A {
    foo: number;
}

export interface Base {
    a: A;
}

export interface Base2 {
    a: A | null;
}

export type MyType = Base & Base2;
```

```json
{
  "$ref": "#/definitions/MyType",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "A": {
      "additionalProperties": false,
      "properties": {
        "foo": {
          "type": "number"
        }
      },
      "required": [
        "foo"
      ],
      "type": "object"
    },
    "MyType": {
      "additionalProperties": false,
      "properties": {
        "a": {
          "$ref": "#/definitions/A",
          "anyOf": [
            {
              "$ref": "#/definitions/A"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "a"
      ],
      "type": "object"
    }
  }
}
```

Which is invalid JSON schema.

**Comment by AndrewLeedham** [comment]
> What if we always do an intersection? That should be correct for union types and for extending.

We could but, b would always have to be part of a, otherwise it is invalid TypeScript, so always taking b would be more efficient as we wouldn't have to do an intersection operation for each comparison in an extension scenario.

**Comment by domoritz** [comment]
You're right. I'm not too concerned about efficiency but won't say no.

**Comment by domoritz** [comment]
I often flip union (|) and intersection (&) types in my head 😞. It's also really warm here today (32C 🔥).

**Comment by AndrewLeedham** [comment]
Easily done. It is very hot here in the UK as well currently 31C, supposed to be reaching 34C on Thursday, not looking forward to that... 😴

**Comment by AndrewLeedham** [comment]
> I found another bug:
> 
> ```ts
> export interface A {
>     foo: number;
> }
> 
> export interface Base {
>     a: A;
> }
> 
> export interface Base2 {
>     a: A | null;
> }
> 
> export type MyType = Base & Base2;
> ```
> 
> ```json
> {
>   "$ref": "#/definitions/MyType",
>   "$schema": "http://json-schema.org/draft-07/schema#",
>   "definitions": {
>     "A": {
>       "additionalProperties": false,
>       "properties": {
>         "foo": {
>           "type": "number"
>         }
>       },
>       "required": [
>         "foo"
>       ],
>       "type": "object"
>     },
>     "MyType": {
>       "additionalProperties": false,
>       "properties": {
>         "a": {
>           "$ref": "#/definitions/A",
>           "anyOf": [
>             {
>               "$ref": "#/definitions/A"
>             },
>             {
>               "type": "null"
>             }
>           ]
>         }
>       },
>       "required": [
>         "a"
>       ],
>       "type": "object"
>     }
>   }
> }
> ```
> 
> Which is invalid JSON schema.

**Comment by domoritz** [comment]
Are you working on this?

**Comment by AndrewLeedham** [comment]
I am working on the intersection issue yes. Not sure if https://github.com/vega/ts-json-schema-generator/issues/181#issuecomment-514236720 is directly related, perhaps best tracked as a separate issue?
