### ISSUE TITLE
Generate a schema with an enum only includes the enums numeric values

### ISSUE THREAD

**Issue by pauldambra** [vega/ts-json-schema-generator#1818]
I've made a minimal example here https://github.com/pauldambra/json-schema-enum-example

But to copy the example here 

```
export declare enum CanvasContext {
  "2D" = 0,
  WebGL = 1,
  WebGL2 = 2,
}

export type canvasMutationParam = {
  id: number;
  type: CanvasContext;
};
```

generates

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "CanvasContext": {
      "enum": [
        0,
        1,
        2
      ],
      "type": "number"
    },
    "canvasMutationParam": {
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "number"
        },
        "type": {
          "$ref": "#/definitions/CanvasContext"
        }
      },
      "required": [
        "id",
        "type"
      ],
      "type": "object"
    }
  }
}
```

So the context of 2D, WebGL, WebGL2 is lost.

Is that a bug? Is it something I can work around?

**Comment by domoritz** [comment]
I think that's technically correct since an object that satisfies the interface needs to use numbers. What would you expect?

**Comment by pauldambra** [comment]
I'm relatively fresh to json schema so it may simply be a misunderstanding on my part.

I'd love to keep the context in the schema... So that you don't lose the human meaning of the enum, and wasn't sure if it was a config problem on my part.

For example in the not-example code we have an enum

```
export declare enum EventType {
    DomContentLoaded = 0,
    Load = 1,
    FullSnapshot = 2,
    IncrementalSnapshot = 3,
    Meta = 4,
    Custom = 5,
    Plugin = 6
}
```

and in that more complete example the definitions section has

```
  "definitions": {
    "CanvasContext": {
      "enum": [0, 1, 2],
      "type": "number"
    },
    "EventType.Custom": {
      "const": 5,
      "type": "number"
    },
```

So that where the enum is used we have

```
            "type": {
              "$ref": "#/definitions/EventType.Custom"
            }
```

**Comment by pauldambra** [comment]
Ah, wait... maybe I see. In one case only one value of the enum will ever be present in usage. So the schema can reference it directly.

In the other, any of the values of the enum might be present and so (I guess) the references don't get defined

It would be nice to have

```
"definitions": {
    "CanvasContext.2D: {
        const: 0
       type: number
    },
    "CanvasContext.WebGL: {
        const: 1
       type: number
    },
    "CanvasContext.WebGL2: {
        const: 2
       type: number
    },
    "CanvasContext": {
      "enum": [
 "$ref": "#/definitions/CanvasContext.2D",
 "$ref": "#/definitions/CanvasContext.WebGL",
 "$ref": "#/definitions/CanvasContext.WebGL2"
],
      "type": "number"
    },
```

but so long as I'm not missing a trick in config, then I'm happy :)

**Comment by domoritz** [comment]
I see. Yeah, we're not using that format right now. This would need to be implemented. You might get something closer to what you want with a type intersection and aliases.
