### ISSUE TITLE
Documentation of annotations ?

### ISSUE THREAD

**Issue by NotSqrt** [vega/ts-json-schema-generator#1819]
Hello,

I've discovered the `@discriminator` annotation in this example : https://github.com/vega/ts-json-schema-generator/blob/898525113e9763f592664232a50824ca4da64d02/test/valid-data/discriminator/main.ts

Is there a list / documentation of the available annotations somewhere ?

Thanks a lot !

**Comment by domoritz** [comment]
Should be in the readme. If not, that's a documentation bug that the pull request author for the feature should resolve.

**Comment by GKersten** [comment]
@domoritz I am just trying to get a hang of this library, you mention the documentation for the annotations should be in the readme, but the readme in the root of this repository does not seem to mention anything regarding annotations. To me this question asked here is still valid, but maybe I am missing something?

Could you point me to any documentation regarding the annotations we can use? So far only thing I was able to find are the "valid-data" tests to use as a reference:
https://github.com/vega/ts-json-schema-generator/tree/next/test/valid-data

**Comment by domoritz** [comment]
I agree. I made a new issue with the specific documentation request https://github.com/vega/ts-json-schema-generator/issues/2045.
