### ISSUE TITLE
Question about the goal of this package

### ISSUE THREAD

**Issue by gallofeliz** [vega/ts-json-schema-generator#1842]
``Hello,

I use this package to write applications that wait for configuration using Typescript types as reference and validating with Ajv with type casting.

However, during my developments, I identifyed illogic behavior.

A simple example :

```
interface MyConfig {
   welcomeDate: Date
}

function runApp(config: MyConfig) {
    console.log("Welcome ! We are the " + config.welcomeDate.toISOString()
}
```

Simple, right ? Now, the config comes from somewhere, and I need to validate it why AJV.

```
    const somewhereConfig = JSON.parse(...)

   const config = ajv.validate(somewhereConfig)
```

Here, the logic is that config is MyConfig. Yes... the logic is ts MyConfig -> JsonSchema -> ts MyConfig

But what happen when I create Json schema with MyConfig ?

```
{
  '$id': 'MyConfig',
  '$schema': 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  properties: { welcomeDate: { type: 'string', format: 'date-time' } },
  required: [ 'welcomeDate' ],
  additionalProperties: false,
  definitions: {}
}
```

Cool. Seems right.

So my Json is '{"welcomeDate": "2024-01-07T00:00:00Z"}'. Right ?

But unfortunally, welcomeDate will still be ... A string. It's logic, JSON does not handle Native Dates, and JSON Schema is a tool to describe/validate JSON (I quote "JSON Schema enables the confident and reliable use of the JSON data format." from the website).

So my first question is : what is your use case of this tool ? 
And my second : Do you have an idea of how I can bridle this tool to limit to what JSON Schema can really handle, with goal when validating a JSON, that the JSON is a VALID typescript origin interface.

Other example :

```
class MyClass {
    public public: string

    constructor() {
        this.public = 'public'
    }

    public doIt() {

    }
}

interface MyConfig {
    myClass: MyClass
}
```

As I can test, typescript does not care about Classes really, but about interface. So that is valid :
```
const test: MyClass = {
    public: 'ok',
    doIt() {}
}
```

It is not possible to declare function with JSON Schema. So, we will not ensure MyClass is used (but typescript neither, so it is okay), and it is not possible in reality, like Date. And what happen ?

```
{
  '$id': 'MyConfig',
  '$schema': 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  properties: { myClass: { '$ref': '#/definitions/MyClass' } },
  required: [ 'myClass' ],
  additionalProperties: false,
  definitions: {
    MyClass: {
      type: 'object',
      properties: { public: { type: 'string' } },
      required: [ 'public' ],
      additionalProperties: false
    }
  }
}
```

Here, the JSON '{"myClass": {"public": "hello}}' will be validated, and the application will receive a simple object without doIt().

Do you understand my point ? My first idea was to create mappers about Date (after validation with Ajv, create a Date object from the date string to be Typescript type compatible), but the problem is very large. Some weeks ago, I used "Buffer" and validating with AJV a real javascript object with a real Buffer was KO.

So I would like to throw an Error if the requested transformation TS->JSONSCHEMA is not possible, defined as the ability to make the opposite with data), but I don't know how to do. I tested with parser and formatter as documented but It add capacities, not remove.

Thanks.

Regards.

**Comment by domoritz** [comment]
I use this package to generate https://github.com/vega/schema/tree/master/vega-lite for https://github.com/vega/vega-lite. Functions and dates are not really an issue there and yes, they cannot be perfectly represented. The philosophy behind this package is to be somewhat robust to types and do a best effort of representing the data structures in serialized JSON. The package is not designed be used to validate whether an object is perfectly JSON serializable. 

I think this answers the questions so I'll close the issue but feel free to ask follow up questions here.

**Comment by gallofeliz** [comment]
Okay, thanks for your answer :)
