### ISSUE TITLE
Add support for HTML-like (Vue, Svelte) files that have <script lang="ts"> elements

### ISSUE THREAD

**Issue by effulgentsia** [vega/ts-json-schema-generator#1898]
A nice enhancement would be if this library could support `.vue`, `.svelte`, and similar HTML-like files that have a `<script lang="ts">` element embedded within them. Just processing the contents of that element as typescript and ignoring anything else in such a file would be sufficient I would think.

**Comment by domoritz** [comment]
I think this functionality could be in a wrapper that uses this library. So in order to keep functionality scoped, I don't think we should add it here. 

If you build such a wrapper, we can link to it, though.
