### ISSUE TITLE
Argument of type 'Config' is not assignable to parameter of type 'CompletedConfig' in ts-json-schema-generator 2.0.0

### ISSUE THREAD

**Issue by danmichaelo** [vega/ts-json-schema-generator#1918]
After upgrading to ts-json-schema-generator 2.0.0, I got an error when initializing the generator programmatically:

```
const schemaGenerator = createGenerator({
    path: sourcePath,
    tsconfig: tsconfigPath,
    type: "*",
    encodeRefs: false,
  });
```

```
Argument of type '{ path: string; tsconfig: string; type: string; encodeRefs: false; }' is not assignable to parameter of type 'CompletedConfig'.
  Type '{ path: string; tsconfig: string; type: string; encodeRefs: false; }' is missing the following properties from type 'Omit<Required<Config>, "path" | "type" | "schemaId" | "tsconfig">': minify, expose, topRef, jsDoc, and 8 more.ts(2345)
```

It works if I add all the properties, but I'm not sure if this change was intentional?

(Typescript: 5.4.5)

**Comment by domoritz** [comment]
I thought it would be cleaner to expect full configs in some of the initialization methods but I think it makes sense to support partial configs in createGenerator. I sent a patch and will release it in a bit.

**Comment by nocodehummel** [comment]
Unfortunately it looks like this is still a blocking issue in release 2.1.0.
