### ISSUE TITLE
"foo" | "bar" | string; should not only map to a string

### ISSUE THREAD

**Issue by domoritz** [vega/ts-json-schema-generator#1921]
We should preserve string literals for better autocomplete. 

Right now 

```ts
export type MyType = "foo" | "bar" | string;
```

just results in 

```json
{
  "$ref": "#/definitions/MyType",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "MyType": {
      "type": "string"
    }
  }
}
```

This makes sense since the literals are strings. See https://github.com/microsoft/TypeScript/issues/29729 for why TS behaves this way.

It would be nice to recognize when string literals and strings are merged and not merge them. 

See https://github.com/YousefED/typescript-json-schema/issues/164 and https://github.com/vega/ts-json-schema-generator/issues/20. 

Also https://github.com/uwdata/mosaic/pull/358

**Comment by arthurfiorette** [comment]
Typescript itself resolves `"foo" | "bar" | string` to `string`.

You can use `"foo" | "bar" | (string & {})` to handle it correctly. This is what frameworks do when they need to support autocomplete AND any string.

![image](https://github.com/vega/ts-json-schema-generator/assets/47537704/27ee6c42-e98f-403c-b366-70764a60084c)

![image](https://github.com/vega/ts-json-schema-generator/assets/47537704/63ffdc4a-bac7-4df6-9fe6-5d7e84e4b1e6)

**Comment by domoritz** [comment]
`"foo" | "bar" | (string & {})` feels like a hack so I wonder whether we should just always have the string literals in the json schema. Alternatively, we could try to detect the `(string & {})` pattern.

**Comment by arthurfiorette** [comment]
I also don't like `string & {}` but diverging from typescript feels a no go at least for me.

Can `(string & {})` be detected in an easy way?

**Comment by domoritz** [comment]
I haven't checked.

**Comment by jheer** [comment]
I would very much like to have support for autocomplete "hacks" like `string & {}` or `string & Record<never,never>`. This would enable proper JSON schema generation in the Mosaic project.

I dug in a bit and it seems one place to potentially handle this is in the `IntersectionTypeFormatter` class. I tried inserting the following around line 33. The idea is to catch a type paired with `{}` and propagate the intended type forward. (The existing code path appears to assume an object, and I think tries to aggregate a collection of properties, which fails here when confronted with literals.)

```ts
            // handle autocomplete hacks like `string & {}`
            if (nonArrayLikeTypes.length == 2) {
                const types = nonArrayLikeTypes.filter(x => !isEmptyObject(x));
                if (types.length === 1) {
                    return this.childTypeFormatter.getDefinition(types[0]);
                }
            }
```

where `isEmptyObject` is simply the following (you might have a better/cleaner/more general idea of how to do this):

```ts
function isEmptyObject(x) {
    const t = x instanceof AliasType ? x.type : x;
    return t instanceof ObjectType && !t.additionalProperties && !t.properties.length;
}
```

This works in my limited tests **except** the output may include redundant types (e.g., a template string may ground to a literal that was already included for autocomplete purposes), so after such processing any union types need to be rechecked for repeated definitions.

OR: An entirely different approach (that I have not tried to implement) might be to instead allow Type AST transforms: a custom (opt-in?) transform could walk the type tree prior to formatting and rewrite nodes where the above pattern occurs, and also perform consolidation for any immediately surrounding union types.

Happy to take a stab at a PR if any of these directions are deemed desirable.

**Comment by domoritz** [comment]
I tried `export type MyType = "foo" | "bar" | (string & {});` and never even get into `IntersectionTypeFormatter`. It seems to already be gone by the time I'm in the `UnionNodeParser`. 

<img width="448" alt="Screenshot 2024-04-18 at 23 34 36" src="https://github.com/vega/ts-json-schema-generator/assets/589034/6e1a5c4d-0047-41d6-9802-1f0746b954d1">

I'm thinking the cleanest approach might be to mark the `StringType` somehow to signal to the `LiteralUnionTypeFormatter` to leaves the literals in the enum. I'm playing with this (and generally simplifying the string literal union handling) in https://github.com/vega/ts-json-schema-generator/pull/1927.

**Comment by Jason3S** [comment]
@domoritz,

This is an awesome feature improvement. At the same time, I wish it was behind a feature flag where I could opt in / out. It exploded the size of the generated schema and caused validation issues.

**Comment by domoritz** [comment]
Let's see whether we can fix the issues. I'm not a fan of too many feature flags since it makes testing and development way harder.
