### ISSUE TITLE
Improved Promise handling to support packages like Prisma

### ISSUE THREAD

**Issue by arthurfiorette** [vega/ts-json-schema-generator#1923]
At #1386, I added basic support for `Promise` unwrapping. Since then promises have evolved and types like `Awaited` have been added and a awaited api have been added in the tsc api.

I think the most evident use case is with [Prisma](https://www.prisma.io/), which all ORM methods return a `PrismaPromise` class:

```ts
export declare interface PrismaPromise<T> extends Promise<T> {
    [Symbol.toStringTag]: 'PrismaPromise';
}
```

Every type, just by extending or having the `Promise` as a base type, when used inside a `async function` or within the `Awaited` type, gets unwraped:

The above example with prisma can be represented in the following way:

![image](https://github.com/vega/ts-json-schema-generator/assets/47537704/6feb227c-7508-44b7-a49c-d3282ded0b67)

![image](https://github.com/vega/ts-json-schema-generator/assets/47537704/e44d80fb-02c8-4ba2-af2c-b12a6b179db4)

`checker.getAwaitedType` api exists, but is unfortunately not yet public. https://github.com/nonara/ts-expose-internals can be set up to help us.

My current test case of nodes to be supported is the following:

```ts
export type Original = { a: string; b: number[] };

export type PromiseAlias = Promise<Original>;

export class PromiseClass extends Promise<Original> {}

export interface PromiseInterface extends Promise<Original> {}

export type LikeType = PromiseLike<Original>;

export class LikeClass implements PromiseLike<Original> {
    then<TResult1 = Original, TResult2 = never>(
        onfulfilled?: ((value: Original) => TResult1 | PromiseLike<TResult1>) | null | undefined,
        onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | null | undefined
    ): PromiseLike<TResult1 | TResult2> {
        return {} as any;
    }
}

export abstract class LikeAbstractClass implements PromiseLike<Original> {
    abstract then<TResult1 = Original, TResult2 = never>(
        onfulfilled?: ((value: Original) => TResult1 | PromiseLike<TResult1>) | null | undefined,
        onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | null | undefined
    );
}

export interface LikeInterface extends PromiseLike<Original> {}

// Prisma has a base promise type just like this
export interface WithProperty extends Promise<Original> {
    [Symbol.toStringTag]: "WithProperty";
}
```

I'm open to PR it if you want.

**Comment by domoritz** [comment]
Always open to PRs. This is not something I need for my use case.
