### ISSUE TITLE
Cannot migrate to version 2 due to typescript error type CompletedConfig

### ISSUE THREAD

**Issue by nocodehummel** [vega/ts-json-schema-generator#1932]
Using version 2.1.0 I have the same issue as the typescript error reported in #1918.

Typescript error for the config on `createFormatter`, `createProgram` and `createParser` that all require type `CompletedConfig`. Config is created according the README.

```
const config: Config = {
  path: "src/{modules/**/!(*spec.ts),lib/options.ts}",
  tsconfig: "tsconfig.json",
  type: "*",
};
```

**Comment by domoritz** [comment]
That's expected now. Please pass in ...DEFAULT_CONFIG to resolve this issue.

**Comment by nocodehummel** [comment]
Workaround to resolve the typescript error.

```
const config: CompletedConfig = {
  ...DEFAULT_CONFIG,
  path: "src/{modules/**/!(*spec.ts),lib/options.ts}",
  tsconfig: "tsconfig.json",
  type: "*",
};
```
