### ISSUE TITLE
Dist types now require @types/ts-expose-internals

### ISSUE THREAD

**Issue by sebbi08** [vega/ts-json-schema-generator#1967]
With the latest version the dist d.ts now requires the @types/ts-expose-internals. But they are only included as devDependency and therefor lead to error on build.

![image](https://github.com/vega/ts-json-schema-generator/assets/9070136/3d1b12ca-247f-40b4-a8d9-3e2bcad5a819)

Solution would be to move the dependency to non dev or remove the types from build

**Comment by arthurfiorette** [comment]
Where is this error being thrown?

This is probably because you have `"skipLibCheck": false` in your tsconfig, is there a reason for also type checking your dependencies?

**Comment by domoritz** [comment]
Dependencies should type check if possible.

**Comment by arthurfiorette** [comment]
Hmm, somehow tsc is adding this directive on every dts file emitted...

![image](https://github.com/vega/ts-json-schema-generator/assets/47537704/9f4a3ca2-3578-4f10-ab15-2c31314022bf)

Have to say, never saw something like this before, I cannot even find documentation about it.

**Comment by arthurfiorette** [comment]
I think typescript is adding this triple slash directive every time `ts` is imported/used. As the `ts-expose-internals` library extends the `typescript` namespace, it thinks without this definition some code would be invalid (which is incorrect).

We could simply add `ts-expose-internals` as a dependency, but this would fuck up every library that uses this package by also having the extended types for them.

I'm currently looking up for a solution but this is an undocumented behavior of typescript. Probably having to disable type check or manually removing these `/// ...` references are the solution here....

**Comment by sebbi08** [comment]
Hi i have seen that in some files the import of typescript got changed from `import ts from "typescript";` to `import type ts from "typescript";` might this be the problem ?

**Comment by arthurfiorette** [comment]
I don't think so, `import type` is just a way to say that all imports are only used in the type land and aren't present in the final js code.

**Comment by domoritz** [comment]
I think it makes sense that you get the `/// ...` ref import when you have a type only import. That's probably what's going on so I think we should make `ts-expose-internals` a dependency or remove it from the package.

**Comment by sebbi08** [comment]
HI yes that fixed the problem thanks for the quick solution
