### ISSUE TITLE
CLI - ENOENT: no such file or directory, open 'package.json'

### ISSUE THREAD

**Issue by yoursunny** [vega/ts-json-schema-generator#1976]
Since v2.2.0, the CLI command does not work if it's invoked in a directory without a `package.json` file.

## Snippet to Reproduce

**package.json**

```json
{
  "private": true,
  "packageManager": "pnpm@9.1.3+sha512.7c2ea089e1a6af306409c4fc8c4f0897bdac32b772016196c469d9428f1fe2d5a21daf8ad6512762654ac645b5d9136bb210ec9a00afa8dbc4677843ba362ecd",
  "dependencies": {
    "ts-json-schema-generator": "2.2.0"
  }
}
```

**tsconfig.json**

```jsonc
{
  "compilerOptions": {
    "allowImportingTsExtensions": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "importHelpers": true,
    "module": "es2022",
    "moduleResolution": "Node",
    "noEmit": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noUncheckedIndexedAccess": true,
    "noUnusedLocals": true,
    "resolveJsonModule": true,
    "strict": true,
    "target": "ES2022"
  },
  "include": [
    "def/*.ts"
  ]
}
```

**def/waypoint.ts**

```ts
export interface Waypoint {
  lat: number;
  lng: number;
}
```

## Error Message

```shell
ubuntu@N0:~/tjsg$ cd def
ubuntu@N0:~/tjsg/def$ $(corepack pnpm bin)/ts-json-schema-generator --path waypoint.ts --type Waypoint --out waypoint.schema.json
node:fs:448
    return binding.readFileUtf8(path, stringToFlags(options.flag));
                   ^

Error: ENOENT: no such file or directory, open 'package.json'
    at Object.readFileSync (node:fs:448:20)
    at file:///home/ubuntu/tjsg/node_modules/.pnpm/ts-json-schema-generator@2.2.0/node_modules/ts-json-schema-generator/dist/ts-json-schema-generator.js:9:27
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'package.json'
}

Node.js v20.13.1
```

## Cause Analysis

The offending line is:
https://github.com/vega/ts-json-schema-generator/blob/08282297320642e02d46c23ac3f8f4d6d8b9ab64/ts-json-schema-generator.ts#L11
This was introduced in #1964.

It reads the content of `package.json` into `pkg` variable, which is then used to display the version number of ts-json-schema-generator package:
https://github.com/vega/ts-json-schema-generator/blob/08282297320642e02d46c23ac3f8f4d6d8b9ab64/ts-json-schema-generator.ts#L54

For this purpose, the command should be reading `path.join(import.meta.dirname, "package.json")` rather than `package.json` in current working directory, because:

* If current working directory does not have `package.json` file, it leads to ENOENT error.
* If current working directory has `package.json` file, the command would display the version number of the downstream package, instead of the version number of ts-json-schema-generator package.

**Comment by arthurfiorette** [comment]
https://github.com/vega/ts-json-schema-generator/pull/1975 might solved this issue already, could you try with `v2.3.0-next.2`?

**Comment by yoursunny** [comment]
I already tried v2.3.0-next.2 and it also suffers from this issue.

**Comment by arthurfiorette** [comment]
[v2.3.0-next.3](https://github.com/vega/ts-json-schema-generator/releases/tag/v2.3.0-next.3) 🚀
