### ISSUE TITLE
Bug: "Has multiple definitions" export issue

### ISSUE THREAD

**Issue by renotoaster** [vega/ts-json-schema-generator#198]
"Type A has multiple definitions" even on the simplest interface use case.
1. Make `test.ts`:
```typescript
export interface A {
  type: string
}

export interface B {
  model: A
}
```

2. Run with `ts-json-schema-generator -p ./test.ts`
3. Result: `Error: Type "A" has multiple definitions.`

If B is _not_ exported (not an option, naturally), the error goes away.

Interestingly this works:
```
export interface A {
  type: string
}

interface B {
  model: A
}

export { B }
```

The resulting JSON from the working example seems to result in a version where there are no refs for the sub-interfaces. This works as a schema, but does muddy the result a bit.

Update: using `export { A, B }` doesn't produce any output to definitions.

**Comment by domoritz** [comment]
This issue is related to https://github.com/vega/ts-json-schema-generator/issues/166. If love your help with fixing this.

**Comment by domoritz** [comment]
Here is a simple example that also causes a problem

```ts
export type A = B;
export type B = number;
```

Run with `yarn run run -p test.ts`.

Note that the issue goes away if I set the desired type. With `yarn run run -p test.ts -t A` I get

```json
{
  "$ref": "#/definitions/A",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "A": {
      "$ref": "#/definitions/B"
    },
    "B": {
      "type": "number"
    }
  }
}
```
