### ISSUE TITLE
Generator crashed when no package version is set

### ISSUE THREAD

**Issue by jkoenig134** [vega/ts-json-schema-generator#1986]
I want to generate json schemas inside a package where in it's `package.json` no `version` is specified.

in https://github.com/vega/ts-json-schema-generator/blob/next/ts-json-schema-generator.ts#L52 you seem to use the version of **my** `package.json` instead of yours and therefore the generator fails with the following error:

```
<path>/node_modules/ts-json-schema-generator/dist/ts-json-schema-generator.js:35
    .parse(process.argv)
    ^

TypeError: Cannot read properties of undefined (reading 'parse')
    at file:///<path>/node_modules/ts-json-schema-generator/dist/ts-json-schema-generator.js:35:5
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)

Node.js v20.13.1
```

**Comment by domoritz** [comment]
Is this fixed by https://github.com/vega/ts-json-schema-generator/pull/1979?

**Comment by jkoenig134** [comment]
@domoritz I think so, but when will this be released?

**Comment by domoritz** [comment]
Great. It's already in prerelease so I just need to make time to make another release.

**Comment by jkoenig134** [comment]
works great, thanks for releasing so quickly! 🎉
