### ISSUE TITLE
Breaking changes from v1 to v2

### ISSUE THREAD

**Issue by mathiasbockwoldt** [vega/ts-json-schema-generator#1996]
I am working on a large piece of software that uses this great package. Currently, we are using v1.5, but I would like to upgrade to the latest version (currently v2.3).
Is there any list of breaking changes that come with this change in the major version number? The release notes just say "💥 Breaking Change", but no details as to what parts are not backwards-compatible.

**Comment by domoritz** [comment]
The update should be smooth. The only breaking change I think was https://github.com/vega/ts-json-schema-generator/pull/1910. Somehow the changelog generation can't handle !.
