### ISSUE TITLE
Support for `"format": "uri-reference"`

### ISSUE THREAD

**Issue by Mearman** [vega/ts-json-schema-generator#1997]
From the docs it doesn't look like it's currently possible to generate a type with `"format": "uri-reference"`
Handling `URL` type works perfectly, but my use case needs a relative URI.

**Comment by domoritz** [comment]
Happy to review a pull request for this request.

**Comment by arthurfiorette** [comment]
hey @Mearman, you can do the following:


```ts
/** @format uri-reference */
export type URI = string
```

**Comment by Mearman** [comment]
Discovered that after. Thank you.
