### ISSUE TITLE
Changing the outputed type

### ISSUE THREAD

**Issue by thejuan** [vega/ts-json-schema-generator#205]
I maybe misunderstanding `@asType`, but I'm trying to change the outputed type of a complex object to just be object in the schema and can't get it.

```
IMyInterface {
  name: string

/**
* @asType object
*/
  complex: SomeComplexObject
}
```

It still attempts to generate definitions for SomeComplexObject, rather than just setting the type to object?

**Comment by domoritz** [comment]
[It looks like we're only testing it for integers](https://github.com/vega/ts-json-schema-generator/search?q=asType&unscoped_q=asType). Could you check whether it works there and where we might have a bug?

**Comment by thejuan** [comment]
Yes, it works for me for changing number to integer like tests. Can also change string to integer. So looks like a bug when its a reference type.

**Comment by domoritz** [comment]
Thanks for looking into this. I've honestly not really used this feature.

**Comment by thejuan** [comment]
NP. I've worked around it for now. Can look at a PR if it comes up again for us.

**Comment by havsar** [comment]
Seems to be working for me for object => string overriding. Can we close this?

**Comment by domoritz** [comment]
I'll close it but we can reopen if it's still an issue.
