### ISSUE TITLE
Path always invalid

### ISSUE THREAD

**Issue by ChrisKHil** [vega/ts-json-schema-generator#2060]
Hello, so im really trying to use the schema-generator in a big Project to generate Schemas for interfaces for the purpose of validating data from an external source. However no matter how i define the paths in the Config (absolute, relative, backslash, forward slash) i always get an Error: [webpack-dev-middleware] HookWebpackError: ENOENT: no such file or directory, scandir.

Obviously if the basic functionality was bugged like that you would know. But i just cant get this to work:

schema-generator.ts:
`
import { Config, createGenerator } from "ts-json-schema-generator";

export class SchemaGenerator {

    private static config: Config = {
        path: "AllInterfaces.ts", // i moved this into the project root to eliminate risk of misspelling the path
        tsconfig: "tsconfig.json",
        type: "*",

    };

    public static generateSchema() {
        const schema = createGenerator(this.config).createSchema();
    }
}
`

**Comment by domoritz** [comment]
Use the cli instead. This sounds like a webpack error which is with the handler. 

Either way, I'm not able to debug your code via GitHub issues.
