### ISSUE TITLE
Array types are not generating in schema

### ISSUE THREAD

**Issue by joshua-aparavi** [vega/ts-json-schema-generator#2078]
When defining array types like the example below, the type isn't being generated in the schema.

Problem code example:
```
export type GET = {
  securityObject: IDatabase.ISimpleObject;
  clientObject: IDatabase.ISimpleObject;
  inheritedFrom: IDatabase.IObject;
  permissions: string[];
}[];
```

Schema generated from above type declaration:

```
"GET": {
	"type": "object",
	"properties": {},
	"title": "PID_EFFECTIVE"
},
```

As you can see, the generated type is set to object, and the properties are empty. The confusing part is when a property of a type is declared as an array it generates it fine. It seems as though it's only breaking for top level schema generation.

**Comment by arthurfiorette** [comment]
Hi @joshua-aparavi, thanks for this bug request, are you up to create a PR fixing this? remember to add unit tests.

**Comment by joshua-aparavi** [comment]
I used the unit tests to confirm the functionality works correctly. No changes needed.
