### ISSUE TITLE
imports of raw files (not modules) make ts-json-schema-generator terminate with error

### ISSUE THREAD

**Issue by massifrg** [vega/ts-json-schema-generator#2084]
In my code there are imports like these:

```ts
import hardCodedConfigInitJson from './editor-config.json?raw';
import defaultCSS from '../../../../staticResources/configs/default/default.css?raw';
import package_json from '../../../package.json?raw';
```

They are not modules, it's simply the content of those files imported as a string into `hardCodedConfigInitJson` and `defaultCSS`.

They cause ts-json-schema-generator to terminate with errors (names and paths have been modified a bit in the log):

```
 ... /src/config/hardcodedConfigs.ts:1:37
    1 import hardCodedConfigInitJson from './editor-config.json?raw';
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Cannot find module './editor-config.json?raw' or its corresponding type declarations.
...  /src/config/hardcodedConfigs.ts:2:31
    2 import defaultCSS from '../../../../staticResources/configs/default/default.css?raw';
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Cannot find module '../../../../staticResources/configs/default/default.css?raw' or its corresponding type declarations.
...  /src/version.ts:1:26
    1 import package_json from '../../../package.json?raw';
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Cannot find module '../../../package.json?raw' or its corresponding type declarations.
```

Is there a workaround?

**Comment by domoritz** [comment]
What's ?raw? I don't think that's supported in typescript without extra configs. I'd say if the files don't exist, this is expected.

**Comment by arthurfiorette** [comment]
@massifrg although `?raw` is a property that only some bundlers understand, they all have a dts file that is loaded somewhere to make TS compiler happy. 

You need to make sure the file ts-json-schema-generator is importing this file as well. You might be able to see which file it is by following the reference of `./editor-config.json?raw`, for example, in your editor.

**Comment by massifrg** [comment]
Thank you for your answers.

Eventually I found a workaround: a `// @ts-ignore` comment over those imports makes ts-json-schema-generator happy again, and I get my json schema.

```ts
// @ts-ignore
import hardCodedConfigInitJson from './editor-config.json?raw';
// @ts-ignore
import defaultCSS from '../../../../staticResources/configs/default/default.css?raw';
// @ts-ignore
import package_json from '../../../package.json?raw';
```

BTW, that `?raw` is [managed by vitejs](https://vite.dev/guide/assets#importing-asset-as-string).
