### ISSUE TITLE
Definitions is empty for simple input

### ISSUE THREAD

**Issue by max-leuthaeuser** [vega/ts-json-schema-generator#210]
Even for this simple input: 
```typescript
declare function Abs(input: string): string;
export = Abs;
```
the result of `ts-json-schema-generator --path "index.d.ts"`
is empty:
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
  }
}
```

**Comment by domoritz** [comment]
Thank you for filing the issue. JSON schema does not support functions and so your schema is empty. See https://github.com/vega/ts-json-schema-generator/issues/98
