### ISSUE TITLE
Unknown node "ObjectLiteralExpression"

### ISSUE THREAD

**Issue by HoldYourWaffle** [vega/ts-json-schema-generator#221]
Parsing a type like this:
```ts
const Literal = {
	a: 'asdfasdf',
	b: 2342354
}

export type LiteralType = typeof Literal;
```

Gives this error:
```
Error: Unknown node "{" (ts.SyntaxKind = 189)
```

SyntaxKind 189 is `ObjectLiteralExpression`.

I hope this is sufficient information.

**Comment by domoritz** [comment]
You need to implement a `ObjectLiteralExpressionParser`.

**Comment by domoritz** [comment]
Supported now.
