### ISSUE TITLE
any type should set additionalProperties to true

### ISSUE THREAD

**Issue by thejuan** [vega/ts-json-schema-generator#240]
```
interface AnyMaps {
    prop1: any;
    prop2: { [id:key]: any }
    prop3: Array<any>
}
```

I would expect all of these to add additionalProperties:true to the definition to match the definition of any?

**Comment by domoritz** [comment]
I agree. It would be sensible to do that.

**Comment by thejuan** [comment]
I'll look at a PR. Any guidance to where this should be done?

**Comment by domoritz** [comment]
Create a test case that covers the cases above and then update the logic for additionalProperties. Have a look at how to use the debugger in VSCode to make development easier.
