### ISSUE TITLE
Custom annotations issue

### ISSUE THREAD

**Issue by bruceflowers** [vega/ts-json-schema-generator#246]
I'm having difficulty getting custom annotations working in my project.

Following this example:
https://github.com/vega/ts-json-schema-generator/blob/master/test/valid-data/annotation-custom/main.ts

...and using `--jsDoc "extended"`, I don't see any of those values in the output. Is there something else I should be aware of?

Thanks in advance!

**Comment by domoritz** [comment]
You need to pass the list if custom annotations. See the test at https://github.com/vega/ts-json-schema-generator/blob/ba8a1c5ff59c0c885bac37eba664454ac634f8cf/test/valid-data.test.ts#L174

**Comment by bruceflowers** [comment]
@domoritz i see - is there a way to do that with the CLI?
