### ISSUE TITLE
CLI: --validationKeywords syntax

### ISSUE THREAD

**Issue by bruceflowers** [vega/ts-json-schema-generator#247]
References https://github.com/vega/ts-json-schema-generator/issues/246

@domoritz for `--validationKeywords`, what's the syntax for an array of values?

**Comment by domoritz** [comment]
Looks like a list of values probably with space in between `foo bar baz`. See https://github.com/vega/ts-json-schema-generator/blob/master/ts-json-schema-generator.ts#L20.

**Comment by bruceflowers** [comment]
i looked at that line before, and assumed that would be a possible combination, but:

`--validationKeywords customComplexProperty customMultilineProperty`

only yields `customComplexProperty`... :\

**Comment by domoritz** [comment]
Ahh, looks like the way the parser works, you have to say `--validationKeywords customComplexProperty --validationKeywords customMultilineProperty`. That's not very pretty so let's fix this.

**Comment by domoritz** [comment]
The code needed to instead use a comma-separated list. 

```ts
    .option(
        "-k, --validationKeywords <items>",
        "Provide additional validation keywords to include as a comma separated list",
        value => value.split(",")
    )
```

**Comment by bruceflowers** [comment]
i'm fine with the usage that currently works - but yes in the future, i'd imagine it's more intuitive to support a comma-separated list.

**Comment by bruceflowers** [comment]
and thank you for your answers!
