### ISSUE TITLE
Don't include unused extended properties. 

### ISSUE THREAD

**Issue by domoritz** [vega/ts-json-schema-generator#27]
In https://github.com/vega/ts-json-schema-generator/commit/1061ba159636d806469b34103a37d918b228d042, we removed unused defs. But we should do the same for extended properties.

**Comment by kanitw** [comment]
https://github.com/vega/vega-lite/pull/4528/files#r255318289 is probably an instance of this.

**Comment by domoritz** [comment]
What are you refrerring to?

**Comment by domoritz** [comment]
Fixed in master
