### ISSUE TITLE
tuple validation

### ISSUE THREAD

**Issue by marcoqu** [vega/ts-json-schema-generator#28]
Hi,
when generating a schema for a tuple-like structure, I noticed some issues:

    type Test = [number, number]

generates a schema that allows for additional values, while it shouldn't.

```
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "definitions": {
        "Test": {
            "type": "array",
            "items": [
                {
                    "type": "number"
                },
                {
                    "type": "number"
                }
            ],
            "minItems": 2,
            "additionalItems": {
                "anyOf": [
                    {
                        "type": "number"
                    },
                    {
                        "type": "number"
                    }
                ]
            }
        }
    },
    "$ref": "#/definitions/Test"
}
```

also, 

    type Test = [number, number, number|undefined]

requires at least three values, while it should require at least 2 and at most three.

Anyways, great project.

**Comment by domoritz** [comment]
Yes, that's a bug. I don't know how easy it is to get this information from the AST but I'd love to get a PR for this.

**Comment by marcoqu** [comment]
I could have a look, but it looks like the additionalItems property was [explicitely added](https://github.com/vega/ts-json-schema-generator/blob/2170b163de5971458907d589d3253ab02184e87e/src/TypeFormatter/TupleTypeFormatter.ts#L23), while I think tuples should not allow additionalItems. But maybe there's something I'm missing.

```
return {
    type: "array",
    items: tupleDefinitions,
    minItems: tupleDefinitions.length,
    ...(tupleDefinitions.length > 1 ? {additionalItems: {anyOf: tupleDefinitions}} : {}),
};
```

could become

```
return {
    type: "array",
    items: tupleDefinitions,
    minItems: tupleDefinitions.length,
    maxItems: tupleDefinitions.length,
};
```

And then one would need to look into the `undefined` items in the tail of the tuple to lower the minItems count?

**Comment by domoritz** [comment]
Thanks for looking into this!

In this library, I chose not to add many options and have the most correct defaults. If you want more options, they could be added to https://github.com/YousefED/typescript-json-schema. I hope that makes sense.

**Comment by marcoqu** [comment]
Ok, thanks!  
Since I see you are involved in both, can i ask you what's the difference between this project and YousefED/typescript-json-schema?

**Comment by domoritz** [comment]
Good question! YousefED/typescript-json-schema uses `typeAtLocation` while this project uses the AST itself. Using the AST is more complicated but tracks aliases better. I use this project for Vega-Lite and that's my main use case. I'm not going to fix anything unless it is relevant for Vega-Lite. YousefED/typescript-json-schema has a lot more customization options and the code is much shorter. However, since it is less complex, it sometimes does not work as well. Both projects benefit from each other. For instance, I try to share test cases where I can and if there is a fix that applies to both projects, I usually copy it over.

**Comment by marcoqu** [comment]
Got it.  
I'm using this for a [vscode extension](https://marketplace.visualstudio.com/items?itemName=marcoq.vscode-typescript-to-json-schema) for generating json schemas from types. I believe for the moment I'll maintain a close [fork](https://github.com/marcoqu/ts-json-schema-generator) of your version since it seems to be the most complete.

Thanks!

**Comment by domoritz** [comment]
I see. Well, let me ask then, would you be willing to help me maintain this library? that is, respond to issues about tuples and help resolve issues around tuples when there is a new typescript version? The changes you made could be useful in Vega-Lite as well.
