### ISSUE TITLE
encoded definition names cause problems with AJV

### ISSUE THREAD

**Issue by thejuan** [vega/ts-json-schema-generator#283]
#277 encoded both the $ref uri and the definition name.
AJV can't find the definition in this scenario https://github.com/epoberezkin/ajv/issues/1134 but it doesn't fail schema validation.

They expect the definition name to be unencoded at the moment, but AWS expects the definition name to be encoded (limited testing).

We may want to match AJV behaviour for now?
Would involve encoding where we generate `$ref`'s rather than in the parser

**Comment by domoritz** [comment]
We should match what the standard says and potentially file issues with AJV or AWS.

**Comment by thejuan** [comment]
Unfortunately standards are often open to interpretation. I can't see a clear answer in the spec.

**Comment by domoritz** [comment]
I'd stick to AJV for now then and first convince them to change anything since they are pretty popular and can affect how the standard is interpreted by many.
