### ISSUE TITLE
Programatic usage need more arguments then the example file.

### ISSUE THREAD

**Issue by victorperin** [vega/ts-json-schema-generator#345]
`jsDoc` and `topRef` properties must be defined (they are not optional).

The Readme example seems to ignore it. When you run in inside a ts  file, it throw this type error:
```
error TS2739: Type '{ path: string; tsconfig: string; type: string; expose: "export"; }' is missing the following properties from type 'Config': topRef, jsDoc
```

**Comment by domoritz** [comment]
Thanks for filing the issue. Can you send a pull request to fix it?
