### ISSUE TITLE
Type-Only Imports and Exports

### ISSUE THREAD

**Issue by GlenCFL** [vega/ts-json-schema-generator#350]
TypeScript 3.8 includes a new feature which helps guarantee that type erasure is occurring, called [Type-Only Imports and Exports](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#-type-only-imports-and-export).

This would be a valid file with TypeScript 3.8:
```ts
interface Test {
    a: string;
}

export type {
    Test
}
```
The issue being that generating a schema using `type: "*"` would generate an empty JSON object `{}`, with `type: "Test"` simply not finding the root type (`No root type "Test" found`).

**Comment by arthurfiorette** [comment]
already fixed
