### ISSUE TITLE
`--type *` or `omitting --type` doesn't work as README describes

### ISSUE THREAD

**Issue by ulivz** [vega/ts-json-schema-generator#355]
## Summary

At the build time I don't know what the interfaces of a file exposes, so I use `--type *`, but got following error:

```
NoRootTypeError: No root type "undefined" found
```

## Reproduction

1. Create `index.ts`:

```ts
export interface Shape {
  /**
   * The size of the shape.
   *
   * @minimum 0
   * @title 12313
   * @type integar
   */
  size: number;
}
```

2. all of following examples don't work:

```bash
npx typescript-to-json-schema --path index.ts --expose 'export' --type * 
npx typescript-to-json-schema --path index.ts --expose 'export' 
npx typescript-to-json-schema --path index.ts --expose 'all' 
```

And I must pass the `--type` option explicitly

```bash
npx typescript-to-json-schema --path index.ts --expose 'export' --type Shape // work

```

**Comment by domoritz** [comment]
Try `npx typescript-to-json-schema --path index.ts --expose 'export' --type '*'`

**Comment by ulivz** [comment]
@domoritz Thanks for the response, it still doesn't work:

![image](https://user-images.githubusercontent.com/23133919/76343305-dfaaff00-633a-11ea-87ec-5002370f3205.png)

**Comment by domoritz** [comment]
Hmm, can you step through the code and see where things are going wrong? Thanks!

**Comment by Guergeiro** [comment]
`ts-json-schema-generator --path index.ts --expose 'export' --out 'test.json'` ✔️

`ts-json-schema-generator --path index.ts --expose 'export' --out 'test.json' --type '*'` ✔️

`ts-json-schema-generator --path index.ts --expose 'export' --out 'test.json' --type *` ❌
(Error: No root type "index.js" found)

For me, [ts-json-schema-generator](https://github.com/vega/ts-json-schema-generator) has `--type` as an optional. Isn't it better to move this issue to [typescript-json-schema](https://github.com/YousefED/typescript-json-schema)?

**Comment by domoritz** [comment]
`npx ts-json-schema-generator -p test.ts` works. Closing as using the wrong library.
