### ISSUE TITLE
Support for: Union Types from Array Literals

### ISSUE THREAD

**Issue by berteundamman** [vega/ts-json-schema-generator#358]
In TypeScript you can do this to derive a union type automatically from an array type:

```typescript
const Arr = ["ABC", "DEF"] as const;
export type UnionFromArray = typeof Arr[number];
```

This is equivalent to `export type RawUnion = "ABC" | "DEF"`, however, the first yields an UnknownNodeError "Error: Unknown node "["ABC", "DEF"] as const" (ts.SyntaxKind = 217) ", this in particular is the 'as const', but also the array literal is not supported.

I can work around this by defining the union directly, but this leads to double declarations that need to be kept in sync.

**Comment by domoritz** [comment]
Thanks for filing the issue. Can you send a pull request to fix it?

**Comment by domoritz** [comment]
Works as of https://github.com/vega/ts-json-schema-generator/pull/387
