### ISSUE TITLE
CLI example doesn't seem to work unless you remove quotes around path

### ISSUE THREAD

**Issue by aaroncowie** [vega/ts-json-schema-generator#392]
The CLI example

`./node_modules/.bin/ts-json-schema-generator --path 'my/project/**.*.ts' --type 'My.Type.Full.Name'`

outputs "NoRootNamesError: No source files found".

Removing the quotes around path seems to fix it (unsure why).
My invocation:
`ts-json-schema-generator --path 'src/**.*.ts' --type 'MyTypeName'`
switched to
`ts-json-schema-generator --path src/**.*.ts --type 'MyTypeName'`

This is on windows if that is relevant.

I tried outputting config.path in program.js createProgram() and it output `<MY_PROJECT_DIR>\'src\**.*.ts'`.

**Comment by domoritz** [comment]
That’s a problem with the behavior of the windows shell. I’m not supporting windows so I’ll close this.

**Comment by aaroncowie** [comment]
Makes sense, thanks.
Do you mind if I create a pull request to modify the documentation to indicate that?

Something along the lines of:
"Note that windows is not officially supported and the above command may need modification"

**Comment by domoritz** [comment]
That would be great. Thanks!
