### ISSUE TITLE
Better typings for tuples

### ISSUE THREAD

**Issue by domoritz** [vega/ts-json-schema-generator#40]
We should support things like

```ts
export type A = [number, number]
```

and maybe

```ts
export type A = [number, number, number?]
```

**Comment by marcoqu** [comment]
I'm working on it.
I should have a pull request soon covering
export type A = [number, number]
export type A = [number, number, number?]
export type A = [number, number, ...number[]]
export type A = []

This also makes --strict-tuples obsolete.
Should we remove it?

**Comment by HoldYourWaffle** [comment]
Was this fixed by #28, #29 and #42?

**Comment by marcoqu** [comment]
Yes, I suppose this should be closed

**Comment by domoritz** [comment]
Thanks
