### ISSUE TITLE
String array by date format

### ISSUE THREAD

**Issue by imjuni** [vega/ts-json-schema-generator#402]
Thank for good tool!

I want set format date in array item, see below

```ts
{
  checkins: {
    type: "array",
    items: {
      type: "string",
      format: "date",
    },
    minItems: 1,
    maxItems: 100,
  }
}
```

So I create interface 

```ts
interface MyRequest {
  /**
   * @minItems 1
   * @maxItems 100
   * @format date
   */
  checkins: string[];
}
```

But created that

```ts
{
  checkins: {
    type: "array",
    items: {
      type: "string",
    },
    minItems: 1,
    maxItems: 100,
    format: "date",
  },
}
```

How can I fix this?

**Comment by domoritz** [comment]
Hmm, it should work. The keyword is defined in https://github.com/vega/ts-json-schema-generator/blob/ccd47c5f00f67942e69b86f9fb087035c4afed0a/src/AnnotationsReader/BasicAnnotationsReader.ts#L11. Can you debug the issue?

**Comment by imjuni** [comment]
@domoritz Thank you for your feedback.

I found my miss. 

AS-IS
```ts
interface MyRequest {
  /**
   * @minItems 1
   * @maxItems 100
   * @format date
   */
  checkins: string[];
}
```

TO-BE
```ts
/**
 * @format date
 */
type TCheckIn = string;

interface MyRequest {
  /**
   * @minItems 1
   * @maxItems 100
   */
  checkins: TCheckIn[];
}
```

I split formatted string type at MyRequest interface. After `ts-json-schema-generator` works very well. 

Thank you.
