### ISSUE TITLE
How to specify multiple symbols?

### ISSUE THREAD

**Issue by kalpeshhpatel** [vega/ts-json-schema-generator#421]
Similar to this method https://github.com/YousefED/typescript-json-schema/blob/920cf97b98889a3887bbfc0b1f1dbc6d24e88cfb/typescript-json-schema.ts#L1114

Do we have an equivalent way here, where I can specify a list of Symbols across different files in the project and create JSON schema out of it?

**Comment by domoritz** [comment]
I'm not sure and I'd have to look into the code as well. But it's not a feature I intend to implement myself. If you want it, please send a pull request.
