### ISSUE TITLE
Types aren't being found unless they're exported

### ISSUE THREAD

**Issue by tamj0rd2** [vega/ts-json-schema-generator#422]
```typescript
const config: Config = { expose: 'all', skipTypeCheck: true, topRef: true, jsDoc: 'extended' }
const generator = new TsSchemaGenerator(program, createParser(program, config), createFormatter(config))
```

types.ts
```
interface MyType {
  greeting: string
}

export {}
```

Calling `generator.createSchema('MyType')` only works if I export MyType. Is this a bug or have I misread how the `expose` flag is supposed to work?

**Comment by domoritz** [comment]
Hmm, maybe at least the root type needs to be exported. Take a look at https://github.com/vega/ts-json-schema-generator/tree/master/test/config/expose-all-topref-true where a non-exported type is in the schema. I don't have time to look deeper into this issue but I can provide pointers and merge pull requests with fixes.

**Comment by tamj0rd2** [comment]
Do you think this is OK to be merged in now?
