### ISSUE TITLE
Excluding functions

### ISSUE THREAD

**Issue by zEh-** [vega/ts-json-schema-generator#438]
# There seems to be no way to exclude functions

## Generating this type throws `unknown type "function"`
... which isn't directly a bug, but our use-case is having shared types between the CMS(JSON Schema) and PatternLibrary components (w/ additional nested fields incl. functions).
```typescript
type X = {
  a: () => void
}
```

### 2) Is there some way to do this when generating like providing `{ type: 'RemoveFunctions<MyOriginalType>' }` option?
The only way I found to get around this is wrapping the original type with:
```typescript
type RemoveFunctions<T> = {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  [P in keyof T]: T[P] extends (..._: any) => any
    ? never
    : T[P] extends Record<string, unknown>
    ? RemoveFunctions<T[P]>
    : T[P]
}
```

### ~~3) Generics everywhere~~
Nested generic types and dynamically checking with `T extends ForPatternLibrary` results in ts2352 and the likes, as TS doesn't support sidecasting.
<br>
_P.S. Thanks for this project as it helped reduce manual duplication!_

**Comment by domoritz** [comment]
Looks like you already found a solution in 2). You can try to add `@hidden` and see whether it works (https://github.com/vega/ts-json-schema-generator/pull/330).
