### ISSUE TITLE
Annotations do not support @ symbol

### ISSUE THREAD

**Issue by robertdempsey** [vega/ts-json-schema-generator#445]
I may be able to have a crack at this myself soon, but it seems that when you use the @ symbol in your text for an annotation (I've noticed this specifically for the `pattern` attribute, the text after and including the @ symbol is chopped off

**Comment by domoritz** [comment]
Can you send an example?

**Comment by robertdempsey** [comment]
Sorry, I didn't have much time when I posted this, but I can send a quick example now until I get a bit more time tonight.

Basically the type is this:

```
/**
* @pattern ^[aA-zZ0-9 \-_ =+!#$@%&()\[\];'.,]*\.(?!gif)\w{3,5}$
*/
type Filename = string;
```

But the property in the schema will look like:

```
"filename": {
          "anyOf": [
            {
              "pattern": "^[aA-zZ0-9 \\-_ =+!#$",
              "type": "string"
            },
            {
              "$ref": "#/definitions/Url"
            }
          ]
        },
```

Notice how it's cut off after the $ symbol?

If you take out the "@" symbol: 

```
/**
* @pattern ^[aA-zZ0-9 \-_ =+!#$%&()\[\];'.,]*\.(?!gif)\w{3,5}$
*/
type Filename = string;
```

you get the full pattern:

```
"filename": {
       "filename": {
          "anyOf": [
            {
              "pattern": "^[aA-zZ0-9 \\-_ =+!#$%&()\\[\\];'.,]*\\.(?!gif)\\w{3,5}$",
              "type": "string"
            },
            {
              "$ref": "#/definitions/Url"
            }
          ]
        },
```

**Comment by domoritz** [comment]
Thanks for the steps. I won’t fix this issue anytime soon but would be happy to review a pull request.

**Comment by robertdempsey** [comment]
No worries. Hopefully I'll get a chance to work on it soon. Cheers.

**Comment by robertdempsey** [comment]
So this is kind of an issue with jsDoc and the fact that jsDoc annotations start with @

I've found if you escape it with a backtick you can make this work. Like so:

```
/**
* @pattern ^[aA-zZ0-9 \-_ `@~=+!#$%&()\[\];'.,]*\.(?!gif)\w{3,5}$
*/
type Filename = string;
```

Note the backtick before the @

You can close this issue if you like @domoritz , cheers

**Comment by domoritz** [comment]
Ahh, so this may be an issue that's outside of our control then.

**Comment by Livven** [comment]
@robertdempsey Putting a `` ` `` before the `@` does make it work but the `` ` `` is included in the output. Any idea how to get around that (without manually modifying the generated schema afterwards)?

**Comment by robertdempsey** [comment]
Hey @Livven , fortunately for us, I needed the backtick in my expression as well. I'll have a play around now to see if I can exclude it

**Comment by robertdempsey** [comment]
For reference, this is where I found the workaround, maybe it'll help you

https://github.com/microsoft/TypeScript/pull/32138

**Comment by robertdempsey** [comment]
@Livven it's not pretty, but I've found that you can add a negative lookahead for the ` character like so:

/**
* @pattern ^(?!.*[`])[aA-zZ0-9 -_ ``@~=+!#$\^%&()[\];'\.,]*\.(?!gif)\w{3,5}$
*/
type Filename = string;

Notice the (?!.*[`]) after the ^ - this means that even though you are allowing ` in the following section, it won't return a match if ` is in your test string. The only thing is now you have to have two backticks to escape your @ symbol

Hope this helps

**Comment by Livven** [comment]
That is an interesting solution! I ended up writing a small script to patch the generated schema though, as that seemed less brittle than this workaround.

I feel a bit bad here but seriously, thanks. Maybe for another escaping fun fact, you can use multiple backticks to include backticks in inline code, e.g. this ``` `` ` `` ``` renders as `` ` ``. The number of opening and closing backticks has to match, and a space can be used to separate "delimiter" and "content" backticks.

**Comment by robertdempsey** [comment]
Ah, I was wondering how to put backticks in my markdown here! `` ` ``. Thanks for the tip, hah.

Yeah, patching the schema is not really a fun solution. We'll probably have to raise an issue with TypeScript as it's their method that fails at parsing the @ symbol without a backtick to escape it. Although, the backtick escaping it was their solution to that problem. Can't win for now I guess.
