### ISSUE TITLE
[Help] Array Type Checker

### ISSUE THREAD

**Issue by jmaicaaan** [vega/ts-json-schema-generator#450]
Hi, thank you for the tool!

I'm also trying to understand/learn reading AST. And I find it hard to determine if a specific property is an array. How did you determine it? I get lost in the source code 😅

**Comment by domoritz** [comment]
Have a look at astexplorer (link in read me). It was super helpful for me to understand how the ast works.

**Comment by jmaicaaan** [comment]
Thanks for your reply @domoritz ! I'm wondering because AST helps me as well but I don't think the code can easily check if a specific node or value declaration type is an array and that's why I'm getting lost in the process. I was able to retrieve the type of primitive values but not the Array type - and I get those type using the typeFlags.
