### ISSUE TITLE
Use without Filesystem?

### ISSUE THREAD

**Issue by paulbijancoch** [vega/ts-json-schema-generator#451]
Hey Guys, great work here, btw.
Is this package capable of running with only a string input?
To be precise: I want to run a serverless function, which takes a string including the typescript and then return the JSON schema by this package.

It would be great to know since I couldn't figure it out by looking at your code.

A little offtopic, but if you don't know them already, you may want to take a look at Quicktype.io

**Comment by domoritz** [comment]
Thanks! I don't think we have support for taking strings right now. The main thing to change would be to convince the typescript compiler to load a string.

I'd be happy to look at a pull request if you get to add support for loading strings. 

Quicktype actually uses this library ;-)
Also check out https://github.com/vega/ts-json-schema-generator, which I have been focusing on for the last few years.
