### ISSUE TITLE
support encoding refs with definitions

### ISSUE THREAD

**Issue by royAmmerschuber** [vega/ts-json-schema-generator#458]
there are some tools who dont support ref encoding but also try to validate the schema against the current metaschema. 
in these cases the schemas will be invalid if you use generics even if you disable `encodeRefs`. so it would be nice to have a third option wich replaces the name in the `$ref` and the `definitions` with something valid.

**Comment by domoritz** [comment]
You can post process your json schema to adjust it for these tools.
