### ISSUE TITLE
Add ecosystem in README.md

### ISSUE THREAD

**Issue by imjuni** [vega/ts-json-schema-generator#478]
Hi, 

I create ts-json-schema-generator ecosystem at [simple-tjscli](https://github.com/imjuni/simple-tjscli)

That is very helpful tool for create jsonschema in typescript project.

If you want add ecosystem in README.md (like [axios](https://github.com/axios/axios/blob/master/ECOSYSTEM.md) package), I create pull-request.

Thank you.

**Comment by domoritz** [comment]
Thanks for the link. I won't have the cycles to maintain a list but people can easily look through libraries that depend on this library and thereby find your tool.
