### ISSUE TITLE
Programatic usage using a string as input

### ISSUE THREAD

**Issue by g5becks** [vega/ts-json-schema-generator#490]
Hi, I have a use case that requires I pass the source code to be generated as a raw string instead of as a file of file path. Is this possible in any way?

I looked briefly through the code but couldn't find anything.

Thanks.

**Comment by domoritz** [comment]
We did not design the API to support this use case. I think you would need to find a way to parse a typescript program coming from a string rather than files. Take a look at the code and feel free to post any question you may run into.

**Comment by g5becks** [comment]
@domoritz 

> I think you would need to find a way to parse a typescript program coming from a string rather than files.

In the program that I am using this for, [This](https://ts-morph.com/setup/adding-source-files#by-string) the method that I am using to parse the program from a string.
