### ISSUE TITLE
TypeError: Cannot read property '$ref' of undefined

### ISSUE THREAD

**Issue by Igoreso** [vega/ts-json-schema-generator#491]
Hi. I'm using version 0.70.2 but from what I see latest codebase has same issue.

In short, `removeUnreachable` expects that `rootTypeDefinition` can be undefined, but `addReachable` doesn't handle this.

I'm not exactly sure what exactly causes this but I can try to reproduce on some small type this if needed.

**Comment by domoritz** [comment]
Please send an example to reproduce the issue. 

Similar to #471.

**Comment by Igoreso** [comment]
Interestingly, I cannot seem to reproduce it in isolated scenario. Is generator stateful? Once I started creating new instance before each `createSchema` call, it stopped failing with this error.

**Comment by domoritz** [comment]
> Is generator stateful? 

Not that I know.

**Comment by domoritz** [comment]
Closing as there is no repro.
