### ISSUE TITLE
Support for inferred types

### ISSUE THREAD

**Issue by jonnyberanek** [vega/ts-json-schema-generator#513]
Whenever trying to utilize inferred types, this error is thrown: 
```
Error: Unknown node "FirestoreToSerializable<FirestoreService.CreateAuthor>" (ts.SyntaxKind = 184) at C:/proj-path/src/functions/admin/content/body.schema.d.ts(13,36)
```

After searching, it appears that SyntaxKind #184 is indeed `InferType`. After looking through the source code it appears that there is not a node parser for inferred types. I'm not too familiar with the inner workings of the project, what kind of additions would be needed to support inferred types?

**Comment by domoritz** [comment]
You need to implement an InferTypeParser and then parse into the right type for it. The easiest way is to create a small test program and then use the debugger to step through the execution and fix where things fail.

**Comment by jirutka** [comment]
Can you please give us some hints on how to implement InferTypeParser?

**Comment by domoritz** [comment]
Take a look at what properties `InferType` has. 

Then take for example https://github.com/vega/ts-json-schema-generator/blob/master/src/NodeParser/AnyTypeNodeParser.ts. It knows how to handle a particular type, and then generates the correct type (here `AnyType`).

I haven't thought more about how exactly to handle `InferType`. That's an exercise fro the reader.

**Comment by jirutka** [comment]
> That's an exercise for the reader.

After reading this, I was quite sure that you’re from academia. And hey, you really are! :smile: So do I, sorta.

**Comment by domoritz** [comment]
Hello, fellow academic. 

I guess I should clarify that I mean "That's an exercise for the reader" somewhat sarcastically (because many books leave out too many steps when they use the phrase). There are actually a lot of steps left.
