### ISSUE TITLE
Cannot execute binary

### ISSUE THREAD

**Issue by larshp** [vega/ts-json-schema-generator#541]
after npm install of the latest version(0.76.0), there is an error when running `ts-json-schema-generator`

![image](https://user-images.githubusercontent.com/5888506/95647307-b28c1e00-0ace-11eb-91ce-e95419e4f542.png)

**Comment by larshp** [comment]
0.75.0 contains more files under dist, 

![image](https://user-images.githubusercontent.com/5888506/95647377-2cbca280-0acf-11eb-9b16-0ec05760e518.png)

**Comment by domoritz** [comment]
Ups, I'll fix it.

**Comment by domoritz** [comment]
Fixed in v0.76.1

**Comment by larshp** [comment]
thanks, tested and it works 👍
