### ISSUE TITLE
Support for Schema generation in the browser

### ISSUE THREAD

**Issue by erichiller** [vega/ts-json-schema-generator#559]
I've been using `ts-json-schema-generator` as a CLI tool during development and it works great. I now have the need to use the tool in the browser. I'm trying to type TypeScript into a input and then take that input string run it through `ts-json-schema-generator` and display the outputted JSON Schema.
I've haven't been able to figure out how to do this (or even if it's possible), so depending on whether or not it is possible, this is a feature request either for documentation on how to do it, or the ability to do it. (it being use in the browser).

**Comment by domoritz** [comment]
It hasn't been a goal for me but I'm happy to review a pull request toward this goal.

**Comment by erichiller** [comment]
Ok let me take a look, I'll post back here

**Comment by arthurfiorette** [comment]
This is entirely possible now, I'm doing this in some internal docs without any problem. You just need to bundle typescript correclty, most of `ts-json-schema-generator` dependencies are for its CLI, the internal code works flawlessly only with typescript.

https://github.com/vega/ts-json-schema-generator#programmatic-usage
