### ISSUE TITLE
Support for `unknown` keyword

### ISSUE THREAD

**Issue by vfernandestoptal** [vega/ts-json-schema-generator#56]
We are starting to use `unknown` instead of `any` in some of our types.
Do you think it makes sense to add support for it? Should it be treated the same as `any`?
Should the any-related classes be updated to also recognize the `unknown` keyword or should it have new separate implementation classes?

Thanks

**Comment by domoritz** [comment]
Thanks for the issue. Yes, after reading the docs on unknown, I think we should treat it as any. Would you send a PR?
