### ISSUE TITLE
Make typescript a peer dependency?

### ISSUE THREAD

**Issue by tamj0rd2** [vega/ts-json-schema-generator#575]
Would it be possible to make typescript a peer dependency instead of a dependency of this project? I have a tool that uses your library as a dependency (the programmatic API specifically), but any time my users want to upgrade their typescript version, I have to install the latest version of ts-json-schema-generator.

One way to solve this would be to separate ts-json-schema-generator into 2 separate npm packages. One for the core/programmatic API and one for CLI use. Is that something you'd be open to doing? I'd be happy to help with it

**Comment by tamj0rd2** [comment]
> So you only need to update when you switch to a new version of ts (not a patch)

Ah ok, that makes sense. Here's [the library](https://github.com/tamj0rd2/ncdc/blob/master/package.json) in question. The library uses Typescript as a peer dependency so that when typescript has new features, users can update their typescript version while still making use of my library. But unless I update the version of ts-json-schema-generator that my library uses, the functionality of my library doesn't work for users who update their typescript versions. I hope that describes the issue a bit better.

> We could still make it a peer dependency and I'm happy to review a pull request towards that goal.

Cool! Does the solution I mentioned in my first comment about splitting it up into 2 npm packages make sense, or would you prefer it done a different way?

**Comment by domoritz** [comment]
I don't want to maintain two packages so let's go with the peer dependency approach.
