### ISSUE TITLE
v0.78.0 not working with Typescript 4.1.2

### ISSUE THREAD

**Issue by tamj0rd2** [vega/ts-json-schema-generator#576]
I think this possibly might need another release? I've installed the latest version, but the version of typescript is still stuck at 4.0.5. I've tried deleting and recreating my node_modules version but it still doesn't work.

I've noticed that although your package.json has the latest typescript version, the package.json included in the release still uses `~4.0.5`

https://github.com/vega/ts-json-schema-generator/releases/tag/v0.78.0

```jsonc
{
  // ...,
  "dependencies": {
    "@types/json-schema": "^7.0.6",
    "commander": "^6.2.0",
    "fast-json-stable-stringify": "^2.1.0",
    "glob": "^7.1.6",
    "json-stable-stringify": "^1.0.1",
    "typescript": "~4.0.5"
  }
}
```

**Comment by domoritz** [comment]
0.79 is out
