### ISSUE TITLE
Custom formatters not working as intended?

### ISSUE THREAD

**Issue by nekosaur** [vega/ts-json-schema-generator#596]
I'm not sure if my understanding of how custom formatters should work is incorrect, or if they are not working as they should?

Say I want to customize how enums are formatted and follow the instructions (which by the way are missing the creation of `parser`)

```ts
export class MyEnumTypeFormatter implements SubTypeFormatter { ... }

const config = {
    path: "path/to/source/file",
    tsconfig: "path/to/tsconfig.json",
    type: "*",
};

const formatter = createFormatter(config, fmt => {
    fmt.addTypeFormatter(new MyEnumTypeFormatter());
});

const program = createProgram(config);
const parser = createParser(program, config); // This line missing from instructions
const generator = new SchemaGenerator(program, parser, formatter, config);
const schema = generator.createSchema(config.type);

const schemaString = JSON.stringify(schema, null, 2);
fs.writeFile(output_path, schemaString, (err) => {
    if (err) throw err;
});
```

But nothing happens. Enums are not formatted using my custom formatter. After having a quick look at the [PR](https://github.com/vega/ts-json-schema-generator/pull/565), the augmentor is run after all the default formatters are added, and then in `ChainTypeFormatter.getTypeFormatter` the array of formatters is just iterated through until a match is found. So how would my custom formatter ever be used when the default one will always be found earlier in the array?

**Comment by domoritz** [comment]
@fwal

**Comment by fwal** [comment]
@nekosaur Your assumption regarding the order of execution of the augmentor was correct and will correct this shortly. Also thanks for pointing out the mistake in the readme.
