### ISSUE TITLE
[REG 0.81->0.82] validationKeywords fails

### ISSUE THREAD

**Issue by orgads** [vega/ts-json-schema-generator#607]
I see from git log that it has been changed to validation-keywords without backwards compat.

**Comment by domoritz** [comment]
Yep, keywords use - instead of camel case. That was a mistake in the api. Since we are pre 1.0, this is okay according to semantic versioning.

**Comment by orgads** [comment]
Well, it broke our build. At least state it in the release notes.

**Comment by domoritz** [comment]
Ah I'm sorry about that. I haven't had the cycles to write full release in the past. If you can, please fix your dependencies and I will continue to keep breaking changes to a minimum.

**Comment by orgads** [comment]
I adapted the build command. Thanks.
