### ISSUE TITLE
How do I validate an object against the schema?

### ISSUE THREAD

**Issue by MrDrummer** [vega/ts-json-schema-generator#621]
Apologies in advance if this is a stupid question, but, suppose I have generate a schema. I want to validate data against the schema (e.g. from an endpoint or database)

Does this package support this? If not, what package supports the format outputted by this package?

I tried the `jsonschema` package, which works on simple single-level models, but for anything more complex, it doesn't throw any errors when it should.

**Comment by domoritz** [comment]
Use Ajv. It's the most accurate and fastest validation I have used. We also use it in the tests.
