### ISSUE TITLE
add $id support

### ISSUE THREAD

**Issue by satvik-s** [vega/ts-json-schema-generator#622]
the generated schemas do not have an option to include `$id`. as a result, if multiple schemas are being generated and read in through `ajv`, it ends in an error because it does not allow multiple schemas with same `$id`. Is it possible to add an option to provide support for `$id` from the CLI?

**Comment by domoritz** [comment]
Happy to review a pull request.

**Comment by satvik-s** [comment]
@domoritz ready for review #624

**Comment by domoritz** [comment]
Thank you.

**Comment by satvik-s** [comment]
@domoritz hey, will the npm package publish happen soon?
