### ISSUE TITLE
With strict null checks, array values or properties ignore `undefined`

### ISSUE THREAD

**Issue by ali-habibzadeh** [vega/ts-json-schema-generator#623]
This bug exists in the original lib too but posting here too since the bug exists in this one too: https://github.com/YousefED/typescript-json-schema/issues/209

When you have `something?: number | undefined;` in an array the schema becomes:

`{"type":"object","properties":{"something":{"type":"number"}`

and undefined just goes puff!

**Comment by domoritz** [comment]
Thank you for the issue. 

```ts
export interface MyType {
  something?: number | undefined;
}
```

generates

```json
{
  "$ref": "#/definitions/MyType",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "MyType": {
      "properties": {
        "something": {
          "type": "number"
        }
      },
      "type": "object"
    }
  }
}
```

which I think is correct since the type of something is `(property) MyType.something?: number` if strict null checks are false by default. The `?` and `| undefined` are redundant and just make the property not required. 

With strict null checks, I am not getting the `undefined` either, which it probably should. I think JSON schema has `undefined`.

Happy to review a pull request to support strict null checks correctly in this case.

**Comment by domoritz** [comment]
Hmm, turns out we don't correctly handle undefined for 

```ts
export type MyType = number | undefined;
```
 
either, which is always

```json
{
  "$ref": "#/definitions/MyType",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "MyType": {
      "anyOf": [
        {
          "type": "number"
        },
        {
          "not": {
          }
        }
      ]
    }
  }
}
```

regardless of strict null checks. 

The semantics are tricky here, though. Technically, undefined should be allowed for `number` when strict null checks are off. However, we don't generate a schema that allows undefined. I think in most cases that's what people would expect, though.

Oh the joys of re-implementing the semantics of TypeScript.

**Comment by ali-habibzadeh** [comment]
Tried it with `"strictNullChecks": false,` and it had no impact. Undefineds are still missing. How did you try it?

**Comment by domoritz** [comment]
Strict null checks make a difference to the semantics and change whether the generated schema matches the semantics or not. In the first example, I argue that the schema is correct when (as is the default) strict null checks are false.

**Comment by ali-habibzadeh** [comment]
How can it be correct when an optional field becomes required in the schema? That's the opposite of what is written in the source.

**Comment by domoritz** [comment]
`something` does not appear in the required properties so you don't have to define it (i.e. it is undefined). http://json-schema.org/understanding-json-schema/reference/object.html#required-properties

**Comment by domoritz** [comment]
Actually, I just realized that `undefined` is not a valid value in JSON so I think what we do is actually correct already, no?  A property that has the value undefined in JSON is just a property that is not defined. 

Technically, undefined can be defined as but nothing can be assigned to it. 

```
       {
          "not": {
          }
        }
```

Do you agree?

**Comment by ali-habibzadeh** [comment]
I somewhat agree with your statement but the problem is that currently the schema is invalid.

I have a type that is like this:

```
type anchors = Array<{
          href: string | null;
          resolvedHref: string | null | undefined;
          alt: string | null | undefined;
          title: string | undefined | null;
          target: string | undefined | null;
          hreflang: string | undefined | null;
          anchorText: string | undefined | null;
          cleanAnchorText: string | undefined;
          isRelNofollow: boolean | undefined;
          isRelSponsored: boolean | undefined;
          isRelUgc: boolean | undefined;
          isRelNoreferrer: boolean | undefined;
          isRelNoopener: boolean | undefined;
        }>;
```

And the generated schema is:

```
"type": {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "$ref": "#/definitions/anchors",
        "definitions": {
          "anchors": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "href": { "type": ["string", "null"] },
                "resolvedHref": { "type": ["string", "null"] },
                "alt": { "type": ["string", "null"] },
                "title": { "type": ["string", "null"] },
                "target": { "type": ["string", "null"] },
                "hreflang": { "type": ["string", "null"] },
                "anchorText": { "type": ["string", "null"] },
                "cleanAnchorText": { "type": "string" },
                "isRelNofollow": { "type": "boolean" },
                "isRelSponsored": { "type": "boolean" },
                "isRelUgc": { "type": "boolean" },
                "isRelNoreferrer": { "type": "boolean" },
                "isRelNoopener": { "type": "boolean" }
              },
              "required": ["href"],
              "additionalProperties": false
            }
          }
        }
      },
```

As you can see no `not` is provided. So what I have marked as possibly undefined is now something that is required.

```
{
          "not": {
          }
        }
        ```

**Comment by domoritz** [comment]
Why isn't it enough for alt not to be in the list of required fields?

**Comment by ali-habibzadeh** [comment]
Also there is no logic to it currently. 

Here is another example which totally ignore the required array:

ts type
```
{
    name: "pageH1s";
    value: Array<{ textContent: string | null | undefined; textContentLength: number | null | undefined }>;
  },
```

becomes
```
"pageH1s": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "textContent": { "type": ["string", "null"] },
                "textContentLength": { "type": ["number", "null"] }
              },
              "additionalProperties": false
            }
          }
```

**Comment by ali-habibzadeh** [comment]
You are correct about that. totally ignored that as I was expecting it to be consistent with non array types

**Comment by domoritz** [comment]
Is there anything left to do here then?
