### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by ali-habibzadeh** [vega/ts-json-schema-generator#629]
How can I using `createGenerator`'s `createSchema` pass an option like `-id` in order to ensure the output has `$id` too. It seems to be missing by default as stated in the CLI docs too.

**Comment by domoritz** [comment]
You can pass `-i myID` to `ts-json-schema-generator`.

**Comment by ali-habibzadeh** [comment]
Which function takes this argument? I could not find it in the docs.

It's only mentioned in CLI version.

**Comment by domoritz** [comment]
Ah yeah, this is for the Cli. If you don't use the cli, you pass the options to the generator as shown in the reader.

**Comment by ali-habibzadeh** [comment]
By reader you mean `AnnotationsReader`?

**Comment by domoritz** [comment]
Sorry, autocorrect. I meant readme: https://github.com/vega/ts-json-schema-generator#programmatic-usage.

**Comment by ali-habibzadeh** [comment]
I did look at the options and using few of them but can't workout which one makes the output have $id.

```
path?: string;
    type?: string;
    tsconfig?: string;
    expose?: "all" | "none" | "export";
    topRef?: boolean;
    jsDoc?: "none" | "extended" | "basic";
    sortProps?: boolean;
    strictTuples?: boolean;
    skipTypeCheck?: boolean;
    encodeRefs?: boolean;
    extraTags?: string[];
    additionalProperties?: boolean;
  ```

**Comment by domoritz** [comment]
use schemaID: https://github.com/vega/ts-json-schema-generator/blob/f7da0e6ef02ce747b430331dc39284826b9c55e5/src/Config.ts#L4
