### ISSUE TITLE
Support to generate schema without required properties

### ISSUE THREAD

**Issue by marcelNogueira** [vega/ts-json-schema-generator#636]
I saw that it was possible to generate schema without the required properties array on YousefED/typescript-json-schema. But I can't found anything about this here. As you plan to join the modules into one single generator, is it possible here too? If not, do you plan to support this?

**Comment by domoritz** [comment]
I don't have plans for that feature. You could postprocess the schema to remove the required annotations. I would also be happy to review a pull request if you want to add this feature here but I would ask for an extensive test suite since it's not a use case I have in my application (Vega-Lite).
