### ISSUE TITLE
Add test case to ensure compatibility with vega-lite TopLevelSpec schema

### ISSUE THREAD

**Issue by sramam** [vega/ts-json-schema-generator#671]
An implicit assumption of using vega/ts-json-schema-generator is that we need to not add regressions to the `vega-lite` schemas.

When added capabilities to `ts-json-schema-generator`, the `vega-lite` constraint exposes corner cases that one is forced to add code to handle.

Due to the complexity of the Vega type-system, it is difficult and sometimes impossible to create minimal tests that exercise such code, ultimately causing degradation of test coverage and causing the CI system to fail. 

An automated test would make this dependency explicit, making it easier to ensure coverage.

**Comment by domoritz** [comment]
Done in master
