### ISSUE TITLE
Type across different packages

### ISSUE THREAD

**Issue by mdesousa** [vega/ts-json-schema-generator#696]
Hi, thanks for this great library... it has been very helpful for our project.
I was wondering if there is a way do generate json schemas for types across different packages. In our case, we have some core types with the appropriate comments and decorators... however, these are lost when the package is built (generated definition files don't keep comments). Therefore, json-schemas generated for dependent types in other packages are incomplete.

Any suggestions on how to handle this? Thanks.

**Comment by domoritz** [comment]
I don't think comments are always removed. For example, we have them in https://cdn.jsdelivr.net/npm/vega-lite@5.0.0/build/src/compile/axis/assemble.d.ts. Alternatively, ts might pick up the comments from ts if you use declarationMap. 

Either way, this is something the library you use has to do.

**Comment by mdesousa** [comment]
Thanks for the answer... we do use declaration map, and the comments did not get picked up from the original source.
We were also thinking that we could generate a json-schema from the original package, and then have ts-json-schema-generator use external references to that schema file... is that possible?

**Comment by domoritz** [comment]
> we do use declaration map, and the comments did not get picked up from the original source

Too bad. I was hoping ts would do that. 

Can you compile the declarations to include comments? I think that would be the easiest.
