### ISSUE TITLE
wrong export of literal type

### ISSUE THREAD

**Issue by satvik-s** [vega/ts-json-schema-generator#698]
TS interface
```
const a = 'test-key';
export interface TagArray {
    [a]: string
}
```
is exported to
```
  "definitions": {
    "TagArray": {
      "additionalProperties": false,
      "properties": {
        "[a]": {
          "type": "string"
        }
      },
      "required": [
        "[a]"
      ],
      "type": "object"
    }
  }
```

`[a]` does not get resolved to `test-key` in the exported schema

**Comment by domoritz** [comment]
Good catch. Can you send a pull request to fix this?

**Comment by satvik-s** [comment]
I was trying to dive into the node parsers to figure out where/how the fix would go in but not luck yet. Are you aware of what the fix might look like or where it would go in?

**Comment by domoritz** [comment]
You can add a breakpoint in the parser and step through the execution.

**Comment by satvik-s** [comment]
I _think_ the problem is lack of parsing support for `SyntaxKind.ComputedPropertyName`. Will dig more and see if I can get a fix out

**Comment by satvik-s** [comment]
The name of a node is usually `kind:78 (SyntaxKind.Identifier)` but in above case, it is `kind:158 (SyntaxKind.ComputedPropertyName)`. From AST, I am not able to see a way to get back to `test-key` from `[a]` yet

**Comment by satvik-s** [comment]
the problem lies here https://github.com/vega/ts-json-schema-generator/blob/70afc127513129deca87188c596364bae4b8d6b9/src/NodeParser/InterfaceAndClassNodeParser.ts#L132 but with the AST, I do not see a way to be able to resolve the reference

**Comment by domoritz** [comment]
Sometimes we use ts's type inference to get at the right type. The problem with always doing that is that aliases disappear as ts does structural typing in many places. You can look around the code base  a bit to find out how we resolve types.
