### ISSUE TITLE
How to use this with Typescript Dates

### ISSUE THREAD

**Issue by jonathannorris** [vega/ts-json-schema-generator#712]
I'm having an issue trying to use this package with Typescript `Date` types and `ajv` to try and do run-time type validation using the resulting JSON Schemas.  The core of the issue is that when you create a Type with a `Date`:

```typescript
export type TestType = {
    readonly createdAt: Date
}
```

That will create a JSON Schema with a `date-time` format:

```json
{
  "$ref": "#/definitions/TestType",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "TestType": {
      "additionalProperties": false,
      "properties": {
        "createdAt": {
          "format": "date-time",
          "type": "string"
        }
      }
    }
  }
}
```

However, when you try and use `ajv` to validate a Typescript TestType object:
```typescript
const test: TestType = { createdAt: new Date() }
ajv.validate(test)
```

you will get the following error:
```
Invalid TestType type: data/createdAt should be string
```

And you face the opposite issue where you are trying to validate an incoming JSON Object as the Typescript type using `ajv` and `createdAt` is a `string` not a `Date`. Any thoughts on how to handle for this properly?

**Comment by domoritz** [comment]
You've discovered the biggest challenge with this schema generator: we have to consolidate two different semantics. The semantics of JSON (schema) and Typescript. JSON actually does not have a date type and so `{ createdAt: new Date() }` is not actually valid JSON.

I'm very open to making changes to this library by the way. Let me know if you have any further questions. 

If you don't mind, I will close this issue as it is inherently not fixable.

**Comment by jonathannorris** [comment]
@domoritz thanks for the response. 

The one thought I had was to somehow define a `date-type` string in the Typescript type, that would still output the JSON schema as `date-type`, Typescript would treat it as a `string` and AJV would validate it as a `date-type` string. Would it be possible to get schema generator to output a string as a `date-type` format?

**Comment by domoritz** [comment]
What's a date-type string?

**Comment by jonathannorris** [comment]
I was refering to the `format` of the JSON Schema:

```
"properties": {
  "createdAt": {
    "format": "date-time",
    "type": "string"
  }
}
```

Basically, is it possible with this library to output a custom type in the same format as a Date? So that typescript would still treat the value as a `string` for compile-time validation, but at run-time AJV would validate it as a `date-time` string?

```typescript
type StringDateTime = String

export type TestType = {
    readonly createdAt: StringDateTime
}
```

**Comment by domoritz** [comment]
Typescript does structural typing so `type StringDateTime = String` just defines an alias and not a new type. Maybe I'm missing something. I'm happy to review a pot if you want to take a stab at it.

**Comment by xdumaine** [comment]
I wonder if it would be possible to use a ts-doc directive to add the `format` to string types, e.g.,:

```ts
type Foo = {
  /**
  @format date-time
  */
  createdAt: string
}
```

And generate:

```json
"properties": {
  "createdAt": {
    "format": "date-time",
    "type": "string"
  }
}
```

**Comment by domoritz** [comment]
I think that's already supported. The syntax might be a bit different.
