### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by acornwall** [vega/ts-json-schema-generator#723]
When trying to generate the below schema, `ts-json-schema-generator` (v0.89.0) fails with `TypeError: Cannot read property '0' of undefined`.

```typescript
const makeDefaultItem = () => ({vendorable: false});

export const PaintJobItems = {
  paintJobBrush: makeDefaultItem(),
};

export type PaintJobItemsType = typeof PaintJobItems;
```

Removing the method and including the type directly (below) doesn't generate the error and generates a valid schema:
```typescript
export const PaintJobItems = {
  paintJobBrush: {vendorable: false},
};

export type PaintJobItemsType = typeof PaintJobItems;
```

This seems to be an issue with `CallExpressionParser` here: https://github.com/vega/ts-json-schema-generator/blob/master/src/NodeParser/CallExpressionParser.ts#L19. Changing that line to:
```typescript
if ("typeArguments" in type && type.typeArguments) {
```
fixes the issue.

**Comment by domoritz** [comment]
Thanks for reporting the issue and suggesting a fix. Can you send a pull request?
