### ISSUE TITLE
Support for If, else, then 

### ISSUE THREAD

**Issue by ymszzq** [vega/ts-json-schema-generator#747]
https://json-schema.org/understanding-json-schema/reference/conditionals.html

Seems like neither vega/ts-json-schema-generator  or YousefED/typescript-json-schema supports this feature. 
(https://github.com/YousefED/typescript-json-schema/issues/353)

**Comment by domoritz** [comment]
How would you express it in typescript?

**Comment by soundquiet** [comment]
Same issues! any ideas now?

**Comment by domoritz** [comment]
Since there is no proposal for how this would be expressed in typescript, I'm going to close this issue.
