### ISSUE TITLE
Conflict with built-in generic Parameters

### ISSUE THREAD

**Issue by pavel-yasiukevich** [vega/ts-json-schema-generator#756]
From #735 

Hello @domoritz and @simonlovesyou

I don't find usage of name "Parameters" correct since result of this expression conflicts with the result of built-in "Parameters" generic type expression in TS (object vs array). I suggest to change "Parameters" to "NamedParameters" or something like that. This will allow us to use complex notation "Parameters< typeof func >[0]" corretly for both cases.

```ts
export const func = (required: string, optional?: string, ...rest: string[])  => 'string';

export type FuncParams = Parameters<typeof func>; // FuncParams is named tuple
```

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "NamedParameters<typeof func>": {
      "type": "object",
      "properties": {
        "required": { "type": "string" },
        "optional": { "type": "string" },
        "rest": { 
          "type": "array",
          "items": { "type": "string"},
          "format": "rest"
        }
      }
    },
    "FuncParams": {
      "type": "array",
      "items": [
        {
          "type": "string",
          "title": "required"
        },
        {
          "type": "string",
          "title": "optional"
        },
        {
          "type": "array",
          "items": { "type": "string"},
          "title": "rest",
          "format": "rest"
        }
      ],
      "minItems": 1
    }
  }
}
```

**Comment by domoritz** [comment]
Hmm, good points. named tuples weren't really a thing until recently. Can you send a pull request? 

@simonlovesyou, what do you think?

**Comment by domoritz** [comment]
Awesome. @pavel-yasiukevich @simonlovesyou can you put together a pull request? I can do a review and make a release.

**Comment by simonlovesyou** [comment]
Shall we close this issue @domoritz @pavel-yasiukevich ?
