### ISSUE TITLE
Compatibility with inferred types from zod

### ISSUE THREAD

**Issue by matt-pawley** [vega/ts-json-schema-generator#758]
Hi, our codebase for various reasons has a mix of [zod](https://github.com/colinhacks/zod) types and typescript types. 

We are hoping to generate JSON schema from the typescript types (which in turn use inferred zod types). However upon trying we get the following error `TypeError: Cannot read property 'types' of undefined` which is thrown [here](https://github.com/vega/ts-json-schema-generator/blob/master/src/NodeParser/CallExpressionParser.ts#L21)

A minimal reproducible example is below:

```typescript
// foo.ts

import * as zod from 'zod';

const Foo = zod.number();
type FooType = zod.infer<typeof Foo>;

export interface Example {
  foo: FooType;
}
```

Can be ran with `npx ts-json-schema-generator --path ./foo.ts --type Example`

Appreciate this is probably out of the remit of this library, but would it be something you would be open to having a PR for? If so, could point me in the right direction to fix ?

**Comment by domoritz** [comment]
Thanks for the issue. To debug this, I suggest inlining
The types. Then use the debugger to get a stack trace and see where the error is thrown. Yes, I'm happy about prs!

**Comment by zmk-punchbowl** [comment]
@matt-pawley we're running into a similar issue (using https://github.com/env0/serverless-openapi-typescript). Did you end up finding a way forward?

This is the error we're getting when a type that uses zod infer is encountered. In this case `types` is the property that is undefined.

```
TypeError: Cannot read properties of undefined (reading 'map')
    at CallExpressionParser.createType (.../node_modules/ts-json-schema-generator/dist/src/NodeParser/CallExpressionParser.js:25:71)
```

**Comment by timothympace** [comment]
I also ran into this and found a fix for the problem: https://github.com/vega/ts-json-schema-generator/pull/1947

I don't understand the purpose of the `FIXME` in the first place, but it seems like a good idea to fully validate the type before trying to use methods that might not exist.
