### ISSUE TITLE
it wil parse to empty if the file doesn't have the namespace

### ISSUE THREAD

**Issue by michael8512** [vega/ts-json-schema-generator#807]
file: global.d.ts
**case 1:**
interface Cluster {
  id: number;
  name: string;
  displayName: string;
}

**case 2:**
declare namespace TS {
  interface Cluster {
    id: number;
    name: string;
    displayName: string;
  }
}

execute "node_modules/.bin/ts-json-schema-generator --path './global.td.ts'"

**result of case 1:**
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
  }
}

**result of case 2:**
{
  "$ref": "#/definitions/TS.Cluster",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "TS.Cluster": {
      "additionalProperties": false,
      "properties": {
        "displayName": {
          "type": "string"
        },
        "id": {
          "type": "number"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "name",
        "displayName"
      ],
      "type": "object"
    }
  }
}

**Comment by domoritz** [comment]
I think you need to add an export to your first case.
