### ISSUE TITLE
ts-json-schema-generator  installed on vercel production that can't find typescript lib.d.ts

### ISSUE THREAD

**Issue by arvinxx** [vega/ts-json-schema-generator#808]
I make an API using `ts-json-schema-generator ` to generate mock data from typescript interface.
the repo is here: https://github.com/arvinxx/api/blob/master/api/code/ts-to-mock-data.ts

it can work well on local but failed on production deployed by vercel host service.

Here is the error result.
![image](https://user-images.githubusercontent.com/28616219/121411463-3e27b880-c996-11eb-8350-acf8a25e8126.png)

```
Cannot find global type 'Array'.

Cannot find global type 'Boolean'.

Cannot find global type 'Function'.

Cannot find global type 'IArguments'.

Cannot find global type 'Number'.

Cannot find global type 'Object'.

Cannot find global type 'RegExp'.

Cannot find global type 'String'.

File '/var/task/node_modules/ts-json-schema-generator/node_modules/typescript/lib/lib.d.ts' not found.
The file is in the program because:
Default library for target 'es5'
```

And here is another same problem with [transform.tools](https://transform.tools/typescript-to-json-schema) project: https://github.com/ritz078/transform/issues/259

**Comment by domoritz** [comment]
That sounds like a problem with vercel. I don't think I can help here.
