### ISSUE TITLE
Support async for programmatic schema generation

### ISSUE THREAD

**Issue by jgillick** [vega/ts-json-schema-generator#811]
When creating the schema programmatically, it would be nice to do it as an asynchronous call.

```js
const schema = await tsj.createGenerator(config).createSchema(config.type);
```

Would this be possible.

**Comment by domoritz** [comment]
I'm probably missing something but why do you want schema generation to be async when it can be sync?

**Comment by jgillick** [comment]
I'm using  in on an express server for API data serialization. In practice the schema is generated once at server start-up and saved to memory. However, it would be ideal if the process was not blocking during the startup process.

**Comment by domoritz** [comment]
Then you need to move the computation to a separate thread/worker. To separate concerns, this should not be done in this library.
