### ISSUE TITLE
failed when file contains global type symbol

### ISSUE THREAD

**Issue by michael8512** [vega/ts-json-schema-generator#819]
it will throw en error when file test.d.ts contains the global type "ILabel". How to deal with this problem. I can fix this when I import the global.d.ts in file test.d.ts. I hope a better way please.

test.d.ts
declare namespace TEST {
  interface {
    name: string;
    label: ILabel;
  }
}

global.d.ts 
interface ILabel {
  id: number;
  name: string;
  module: string;
  color: string;
}

**Comment by domoritz** [comment]
Please describe the error and what you have tried so far. Also, make sure to provide a minimal example.

**Comment by michael8512** [comment]
> Please describe the error and what you have tried so far. Also, make sure to provide a minimal example.
https://github.com/michael8512/ts-json-test.git

you can try with this minimal example. The name 'ILabel', which is defined in interface/global.d.ts, will not be found. And this will throw an error 'Cannot find name 'ILabel''.

**Comment by domoritz** [comment]
What command do you run? How does ts find the global file?

**Comment by michael8512** [comment]
> What command do you run? How does ts find the global file?

by tsconfig.json, the global Type if global.d.ts can be find, in other files.
use command 'npm run schema', it will throw an error 'Cannot find name 'ILabel''

**Comment by domoritz** [comment]
What's the non script for schema?

**Comment by michael8512** [comment]
> What's the non script for schema?

what do you mean???

**Comment by domoritz** [comment]
Npm script. Sorry, auto correct.

**Comment by michael8512** [comment]
> Npm script. Sorry, auto correct.

So what should I do with the global type symbol?

**Comment by domoritz** [comment]
My question was, what `npm run schema` actually executes. If you don't tell the schema generator about the tsconfig file, it may not be able to find the file with the global types.

**Comment by domoritz** [comment]
I'm fairly certain this is not an issue with the schema generator so I'll close this issue. I can reopen if it turns out that I am wrong.
