### ISSUE TITLE
Custom formatter supporting circular refs

### ISSUE THREAD

**Issue by gadicc** [vega/ts-json-schema-generator#820]
Is there any way to currently do this?

I'm a bit new to the project but from what I understand, my augmentor function needs access to `circularReferenceTypeFormatter` too.  Would you accept a PR that passes that as the 2nd argument?

Quoting relevant parts of [formatter.ts](https://github.com/fwal/ts-json-schema-generator/blob/master/factory/formatter.ts):

```ts
export function createFormatter(config: Config, augmentor?: FormatterAugmentor): TypeFormatter {
    const chainTypeFormatter = new ChainTypeFormatter([]);
    const circularReferenceTypeFormatter = new CircularReferenceTypeFormatter(chainTypeFormatter);

    if (augmentor) {
        augmentor(chainTypeFormatter);
    }

    chainTypeFormatter
        .addTypeFormatter(new AnnotatedTypeFormatter(circularReferenceTypeFormatter))
        
    //...
    
    return circularReferenceTypeFormatter;
}
```

Would you accept a PR to call:

```ts
  augmentor(chainTypeFormatter, circularReferenceTypeFormatter);
```

Or am I missing something obvious?
If I am, I'll commit to make a PR that helps explain this case in the docs.

**Comment by gadicc** [comment]
@fwal tagging you since you did the initial custom formatter support, hope that's ok.

**Comment by domoritz** [comment]
I see that being useful. Yes, please send a pull request with tests and potentially docs.

**Comment by gadicc** [comment]
@domoritz, thanks for your super quick reply and sorry that I only had a chance to look at this again now.  Submitted the above PR.  Many thanks.

Lastly, a massive thanks for all your work on this project which has been critically helpful in my own!
