### ISSUE TITLE
Support for emitting schemas using older json schema versions

### ISSUE THREAD

**Issue by hrapp-benchmate** [vega/ts-json-schema-generator#853]
Hi,
it would be great to have a cli option to choose the JSON schema version that should be generated.
As I understand right now it only supports v7 draft but a lot of use cases rely on an older version (ie v4 draft).

Does the lib generally support to be extended in such a way or not ?

**Comment by domoritz** [comment]
I don't plan to support older versions. You can use an older version of the library or make a fork for Draft v4.

**Comment by hrapp-benchmate** [comment]
thanks for your quick response.
Just wanted to gauge if there's a broader interest in it - fair enough !

**Comment by domoritz** [comment]
If you make a fork for v4, I am happy to link to it from the readme.

**Comment by alexbjorlig** [comment]
I have spent most of the day making ts-json-schema-generator compatible with the BSON types in our project, only to learn that MongoDB atlas expects the schema to be Draft v4 😅 Did you end up creating a fork @hrapp-benchmate?

I'm trying to understand how a fork would look like, but currently just reading up and trying to understand the library.

**Comment by hrapp-benchmate** [comment]
I'm sorry but nope - our org decided to go a different route and not using the lib at all.

**Comment by alexbjorlig** [comment]
Thanks for the update. Do you mind sharing the approach to generating JSON schemas your organization decided to adopt?

**Comment by hrapp-benchmate** [comment]
the approach is not using it :-) aka using unvalidated JSON and handwritten openapi specs.
