### ISSUE TITLE
Remove empty definitions object

### ISSUE THREAD

**Issue by remcohaszing** [vega/ts-json-schema-generator#878]
A JSON schema generated by this package, contains a `definitions` field, which may hold reusable JSON schema definitions.

This field doesn’t serve any purpose if it’s empty. I suggest to remove it if it’s empty.

**Comment by domoritz** [comment]
Happy to review a pull request to add this feature.

**Comment by remcohaszing** [comment]
Cool, you can expect a pull request soon’ish. :smile:

**Comment by arthurfiorette** [comment]
Removing the `definitions` will break a lot of tools that uses the generated schema. If the definitions is empty, there's no need to run this tool anyways :/
