### ISSUE TITLE
Throw if JSDoc annotations can’t be parsed

### ISSUE THREAD

**Issue by remcohaszing** [vega/ts-json-schema-generator#879]
Currently if JSDoc annotations can’t be parsed, they are silently ignored.

https://github.com/vega/ts-json-schema-generator/blob/76deba14de3fa29e7798a41627730cb0c6f459d8/src/AnnotationsReader/BasicAnnotationsReader.ts#L98-L104

I suggest to add an option to throw on invalid annotations.

**Comment by domoritz** [comment]
I don't think we need an option but we could throw an error by default.

**Comment by remcohaszing** [comment]
I would like that, but that would make it a beaking change.

**Comment by domoritz** [comment]
We are pre 1.0 so breaking changes are ok. I try to avoid breaking changes that affect a lot of people.

**Comment by arthurfiorette** [comment]
A lot of people use this library to generate json schemas with types that not always are them who writes it.

This option would break a lot of implementations just by one type having an extra annotation from a standard like https://tsdoc.org/ or others.
