### ISSUE TITLE
[Question/Help] Annotation support and known limitations

### ISSUE THREAD

**Issue by newt10** [vega/ts-json-schema-generator#881]
Is there a list of annotations that this library support?
I am having trouble with typescript-json-schema with certain annotations like
```
interface A {
  data: {
    on: Hex | ConfigPauseHexCode[] | ConfigRepeatHexCode[];
    off: Hex;
  };
}

/**
 * @pattern ^[0-9a-fA-F]*$
 */
export type Hex = string;

export interface ConfigRepeatHexCode {
  data: string;
  sendCount: number;
  interval: number;
  pause?: number;
}

export interface ConfigPauseHexCode {
  data: string;
  pause?: number;
}
```

The generated schema does have the pattern requirement as expected.
I am exploring to replace the library with this one and wanted to confirm if this library supports it.

**Comment by domoritz** [comment]
@pattern should work: https://github.com/vega/ts-json-schema-generator/blob/80bba1cb2b893edc81fce08accddae76390d5156/test/valid-data/type-conditional-jsdoc/main.ts.

Make sure you enable the right settings to expose the jsdocs.
