### ISSUE TITLE
Support Omit 

### ISSUE THREAD

**Issue by domoritz** [vega/ts-json-schema-generator#93]
See https://github.com/vega/vega-lite/pull/4850#discussion_r272783413

**Comment by MarcusRiemer** [comment]
Huh, I just stumbled over exactly the same issue. Is there any ETA for this issue?

**Comment by domoritz** [comment]
We found a workaround so it's not on our critical path right now. I'm happy to look at pull requests for it, though.

**Comment by domoritz** [comment]
Omit is implemented with Exclude so we should support that first. See #71.

**Comment by kayahr** [comment]
As conditional types and therefor Exclude are implemented now I guess this issue can be closed? Unfortunately there is no real description here, just a link to vega-lite internals. If there are still Omit-structures which are not working properly yet then it would be nice to add them here so I can try to fix the remaining problems.

**Comment by domoritz** [comment]
Vega-Lite's Omit

```ts
type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;
```

Omit in Typescript 3.5

```ts
type Omit<T, K extends keyof any> = Pick<T, Exclude<keyof T, K>>;
```

Here is a simple use case. 

```
/**
 * A Person.
 */
type Person = {
    /**
     * Their Name.
     */
    name: string;
    age: number;
    location: string;
};

/**
 * Quantum person.
 */
type QuantumPerson = Omit<Person, "location">;

// equivalent to
// type QuantumPerson = {
//     name: string;
//     age: number;
// };
```

It all works as expected for me so I'll close this.
