### ISSUE TITLE
Custom parser based on an existing NodeParser

### ISSUE THREAD

**Issue by timhumble** [vega/ts-json-schema-generator#939]
I've been trying to write a custom parser, in order to support BSON ObjectId and Decimal128 types. The idea is that ObjectId should be parsed as StringType() and Decimal128 as NumberType().

Both of these two types, in the AST match ```ts.SyntaxKind.TypeReference```. The problem that I'm having is that I don't want to lose the parsing which is already done in TypeReferenceNodeParser.ts.

If I create a custom parser, according to the instructions in the README, it overrides TypeReferenceNodeParser, so I lose support for dates, arrays, etc. 

What I would really like to do is to be able to extend TypeReferenceNodeParser, so that I check for the custom types within my own CreateType and then call the parent CreateType if there is no match. However, after several tries, I figure that I'm going about it the wrong way, so wanted to ask the correct approach to achieve this, if it is actually possible.

For now my temporary solution is simply to fork the repo and to add the following lines to TypeReferenceNodeParser:

```ts
...
        else if (typeSymbol.escapedName === "ObjectId") {
            return new StringType() //could later return AnnotatedType
        } else if (typeSymbol.escapedName === "Decimal128") {
            return new NumberType()
        } else ...
```

I appreciate any advice or pointers on how to tackle this.

**Comment by domoritz** [comment]
> Both of these two types, in the AST match ts.SyntaxKind.TypeReference.

Hmm, I don't think they are. Can you show a relevant example in astexplorer?

**Comment by timhumble** [comment]
Sure, here's the example that I was working with: https://astexplorer.net/#/gist/5333b4774b93caf02a12e721c35809e1/574201367a3a50901e23384210dbb61c8a45976b

In case it also helps, here is the existing JSON Schema output from running ts-json-schema-generator without any modifications given the following input:

```ts
import { ObjectId } from 'bson'
export interface ITest {
    _id: ObjectId
}
```
It currently produces:

```json
"_id": {
                "type": "object",
                "properties": {
                  "_bsontype": {
                    "type": "string",
                    "const": "ObjectId"
                  },
                  "id": {
                    "type": "object",
                    "additionalProperties": {
                      "type": "number"
                    },
                    "properties": {
                      "BYTES_PER_ELEMENT": {
                        "type": "number"
                      },
                      "buffer": {
                        "type": "object",
                        "properties": {
                          "byteLength": {
                            "type": "number"
                          }
                        },
                        "required": [
                          "byteLength"
                        ],
                        "additionalProperties": false
                      },
                      "byteLength": {
                        "type": "number"
                      },
                      "byteOffset": {
                        "type": "number"
                      },
                      "length": {
                        "type": "number"
                      }
                    },
                    "required": [
                      "BYTES_PER_ELEMENT",
                      "buffer",
                      "byteLength",
                      "byteOffset",
                      "length"
                    ],
                    "description": "Raw data is stored in instances of the Buffer class. A Buffer is similar to an array of integers but corresponds to a raw memory allocation outside the V8 heap.  A Buffer cannot be resized. Valid string encodings: 'ascii'|'utf8'|'utf16le'|'ucs2'(alias of 'utf16le')|'base64'|'binary'(deprecated)|'hex'"
                  },
                  "generationTime": {
                    "type": "number"
                  }
                },
                "required": [
                  "_bsontype",
                  "id",
                  "generationTime"
                ],
                "additionalProperties": false
              }
```

**Comment by domoritz** [comment]
Can you rewrite the example so it doesn't reference a library? Otherwise, ASTExplorer cannot resolve the reference.

**Comment by timhumble** [comment]
The difficulty is that BSON ObjectId and Decimal128 are both taken from the bson library, so I'm not sure how I would be able to do that within ASTExplorer.

**Comment by domoritz** [comment]
You can copy the relevant type declarations.

**Comment by julienvincent** [comment]
Having done something very similar myself a few months ago, I can post my solution to the problem:

```ts
import * as generator from 'ts-json-schema-generator';
import * as ts from 'typescript';

export class BSONType extends generator.BaseType {
  static ID = '__BSON_TYPE__';
  private readonly name: string;
  constructor(name: string) {
    super();
    this.name = name;
  }
  public getId(): string {
    return BSONType.ID;
  }
  public getName() {
    return this.name;
  }
}

const createBSONTypeParser = (name: string): generator.SubNodeParser => {
  return {
    supportsNode(node: ts.TypeReferenceNode) {
      if ('typeName' in node) {
        if ('right' in node.typeName) {
          return node.typeName.right?.escapedText === name;
        }
      }
      return false;
    },
    createType() {
      return new BSONType(name);
    }
  };
};

// ===

const parser = generator.createParser(program, config, (parser) => {
  parser.addNodeParser(createBSONTypeParser('ObjectId'));
  parser.addNodeParser(createBSONTypeParser('Timestamp'));
  // ...
});
```

You can then write a formatter that consumes the `BSONType` and outputs whatever JSON-Schema you want

**Comment by timhumble** [comment]
@julienvincent - I really appreciate you sharing that with me, it helped a lot.

In the end, I had to make a modification (not sure if the spec changed somewhere), but what works for me is:

```ts
...
supportsNode(node: ts.TypeReferenceNode) {
  if ('typeName' in node) {
    if ('escapedText' in node.typeName) {
      return node.typeName?.escapedText === name;
    }
  }
  return false;
}
...
```

**Comment by julienvincent** [comment]
That modification would be necessary due to the way you are constructing your schema type:

```ts
import * as bson from 'bson';

// Would require checking `.right`
type Schema = {
  _id: bson.ObjectId
}

// ===

import { ObjectId } from 'bson';

// Would not require checking `.right`
type Schema = {
  _id: ObjectId
}
```

**Comment by timhumble** [comment]
Makes perfect sense. Thanks.
