### ISSUE TITLE
Generate MongoDB's JSON schema implementation (from typescript interfaces)

### ISSUE THREAD

**Issue by alexbjorlig** [vega/ts-json-schema-generator#955]
My objective is to generate a JSON schema from a typescript interface, for usage in MongoDB validation.

According to the [MongoDB webpage](https://docs.mongodb.com/manual/reference/operator/query/jsonSchema/), they;

> ...includes the addition of the bsonType keyword, which allows you to use all BSON types in the $jsonSchema operator. bsonType accepts the same string aliases used for the $type operator.

Is this something other people had success with?

**Comment by domoritz** [comment]
There are some comments about BSON in the issues so I think it would be a perfect fit.

**Comment by alexbjorlig** [comment]
This [issue](https://github.com/vega/ts-json-schema-generator/issues/939)?

**Comment by domoritz** [comment]
Yes, for example. Another way might be to use a js doc annotation to override the type explicitly. That is, if you have access to the sources you want to generate a schema for.

**Comment by alexbjorlig** [comment]
Thanks for the comment @domoritz  - I will give it a try. Was hoping for some "quick" solution to get output like the below.

```typescript
  _id: { bsonType: 'string' },
  date: { bsonType: 'date' },
  isOverdue: { bsonType: 'bool' },
  groupId: { bsonType: 'objectId' },
```
