### ISSUE TITLE
JSDoc parser ignores empty annotations

### ISSUE THREAD

**Issue by stevenlandis-rl** [vega/ts-json-schema-generator#972]
If I define a type like this:
```typescript
/**
 * @customEmptyAnnotation
 */
export interface MyObject {}
```

I would expect the schema to look like this with an empty string for the empty annotation:
```json
{
  "$ref": "#/definitions/MyObject",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "MyObject": {
      "customEmptyAnnotation": "",
      "additionalProperties": false,
      "type": "object"
    }
  }
}
```

However the actual schema does not include the annotation:
```json
{
  "$ref": "#/definitions/MyObject",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "MyObject": {
      "additionalProperties": false,
      "type": "object"
    }
  }
}
```

This happens when I add `customEmptyAnnotation` to `extraTags`. I also tried setting `jsDoc` to `basic` and `extended`.

Do we want to support empty annotations?

**Comment by domoritz** [comment]
Not sure what the use case is so I don't care either way.

**Comment by stevenlandis-rl** [comment]
One use case could be to mark a type as deprecated:
```ts
/**
* @deprecated
*/
type MyType = string;
```

**Comment by domoritz** [comment]
That makes sense. I wonder whether the generated property should be an empty string or a boolean, though. Empty string probably makes sense. Wanna send a pull request?

**Comment by stevenlandis-rl** [comment]
Yep, working on it now.
