### ISSUE TITLE
Allow a custom annotation parser?

### ISSUE THREAD

**Issue by stevenlandis-rl** [vega/ts-json-schema-generator#977]
There is no specification for translating JSDoc annotations to JSON Schema annotations.

There are many places for ambiguity. Should text be parsed as JSON? Should empty annotations default to an empty string or True? Should newlines be removed from descriptions?

Since there are many different ways to parse JSDoc annotations, it would be nice to have a new optional argument in the config to create a schema generator with custom JSDoc parsing.

Here are a few of my ideas:
```ts
// idea A: get docs from node
function getAnnotationsFromNode({
  node: ts.Node
}): Annotations {
  // ...
}

// idea A: get docs from parts of a node
function getAnnotationsFromJsDoc({
  description: string,
  tags: ts.JSDocTagInfo[]
}): Annotations {
  // ...
}

// idea C: pass many different pieces of information
function getAnnotations({
  node: ts.Node,
  description: string,
  tags: ts.JSDocTagInfo[],
  checker: ts.TypeChecker
}): Annotations {
  // ...
}

// idea D: extend AnnotationsReader
class MyAnnotationsReader extends AnnotationsReader {
  getAnnotations(node: ts.Node): Annotations {
    // ...
  }
}
```

I'm partial to idea C since the function has a clear role and it's easy to add new arguments if annotation generators need more information.

This function/class would then be passed to the config:
```ts
const config = {
    path: "path/to/source/file",
    tsconfig: "path/to/tsconfig.json",
    type: "*", // Or <type-name> if you want to generate schema for that one type only,
    getAnnotations: myGetAnnotations,
};

const schema = tsj.createGenerator(config).createSchema(config.type);
```

What do you think?

**Comment by domoritz** [comment]
I wonder whether instead of making the parsing customizable, we can come up with a good default. I like to err on the side of having fewer knobs.

**Comment by stevenlandis-rl** [comment]
That makes sense. Coming from [typescript-json-schema](https://github.com/YousefED/typescript-json-schema) there are a few changes to existing schemas I need to make for consistency.

- Don't strip newlines from @description tags so markdown is preserved (breaking)
- Don't parse JSDoc tags as JSON (breaking)
- Set the default value for all empty tags, including built in tags, to the empty string. (non-breaking)

Since a few of these changes are breaking, adding a custom annotation parser would be an easy way to let different users get different annotations without having to change existing tests or the schema in vega-lite. There's also some precedent for this since users can add custom node parsers to the generator.

That being said, a good default is definitely ideal. There are a few existing knobs such as `jsDoc` and `extraTags` for customization and I could keep adding knobs to implement the breaking changes.
- `stripNewlinesFromJSDocTags`
- `parseJSDocTagsAsJSON`

Another option might be to add a new type of annotations parser that behaves the same as the parser in [typescript-json-schema](https://github.com/YousefED/typescript-json-schema).

**Comment by domoritz** [comment]
I think the newline one isn't an issue. We could preserve double newlines but collapse singles, which would preserve markdown rendering. 

Parsing as JSON could be something we attempt but fall back to string if it fails.

**Comment by stevenlandis-rl** [comment]
I'll give the newline collapsing a try. If that works, that would be an easy fix.

For JSON parsing, it only falls back to a string if it is a custom field. Built-in JSON fields do not fall back.
https://github.com/vega/ts-json-schema-generator/blob/06491e30866d3be43723293f43ae3dc7232142ea/src/AnnotationsReader/BasicAnnotationsReader.ts#L83-L89
Is that what you're talking about changing?

**Comment by domoritz** [comment]
Sweet, try the markdown code and see whether we can deploy the fix. 

What I meant by fallback is to try parsing with `JSON.parse` and wrapping it in a try catch. I don't have the cycles right now to jump into the code, unfortunately.

**Comment by stevenlandis-rl** [comment]
I looked into markdown regexes and they're actually OK. They already remove single newlines and preserve multiple newlines.

**Comment by stevenlandis-rl** [comment]
I tried having JSON tags fall back to text but it causes a failure in `vega-lite.test.ts`.

For some schemas in vega-lite, there is a `__Default value:__` section below an `@minimum` section. Here's [an example](https://github.com/vega/vega-lite/blob/36f29c7fbe507cc5209c4fed60352c07b0976c52/src/mark.ts#L122-L125) Since JSDoc  includes text below tags, the `__Default value:__` gets included in the `@minimum` doc tag.

Here's how it looks in vscode:
![Screen Shot 2021-10-07 at 1 04 00 PM](https://user-images.githubusercontent.com/51932152/136454389-611a57a4-452b-4f64-b468-7e704ee84dfe.png)

And here's how it looks when I swap the order of `@minimum` and `__Default value:__`:
![Screen Shot 2021-10-07 at 1 04 49 PM](https://user-images.githubusercontent.com/51932152/136454531-7bbfbe73-ef4d-4fdd-b8e7-bb4355936c8d.png)


This seems like an issue in vega-lite that needs to be fixed before all JSON tags fallback to text.

In the meantime, I could make a PR to only let `@deprecated` json tags fall back to text.

**Comment by domoritz** [comment]
Yeah, that seems a problem with Vega-Lite. Can you send prs for all the broken cases where doc tags are not the last?

**Comment by stevenlandis-rl** [comment]
I think I found them all. This regex was helpful: `@([^@]|\n){1,100}?__Default value:`

**Comment by stevenlandis-rl** [comment]
@domoritz how should we update package versions so vega-lite uses the latest version of vega-typings and ts-json-schema-generator uses the latest version of vega-lite?

Would it be these steps?
1. publish new version of vega-typings
2. update vega-lite to use new version of vega-typings
3. publish new version of vega-lite
4. update ts-json-schema-generator to use latest version of vega-lite

**Comment by domoritz** [comment]
Yes, you got it. Unfortunately it'll take some time since we won't make a release just for this update.

**Comment by domoritz** [comment]
We can still fix the behavior here and push a new schema for the tests and assume that things will be fixed eventually.
