### ISSUE TITLE
Get json schema of parameters from a function

### ISSUE THREAD

**Issue by apiel** [vega/ts-json-schema-generator#98]
Would it be possible to get the JSON schema for the parameters of a function (or a method)?

For example:

```ts
export interface GetListInput {
    foo: string;
}

export function getList(input: GetListInput, input2: string) {
    // some code
}
```

I would get something like array:

```json
{
  "$ref": "#/definitions/params",
  "$schema": "http://json-schema.org/draft-06/schema#",
  "definitions": {
    "GetListInput": {
      "additionalProperties": false,
      "properties": {
        "foo": {
          "type": "string"
        }
      },
      "required": [
        "foo"
      ],
      "type": "object"
    },
    "params": {
      "items": [
        {
          "$ref": "#/definitions/GetListInput"
        },
        {
          "type": "string"
        }
      ],
      "maxItems": 2,
      "minItems": 2,
      "type": "array"
    }
  }
```

**Comment by domoritz** [comment]
Yes, it would be possible but I do not intend to support it for now.

**Comment by apiel** [comment]
Could you give me some direction to implement it by my own? I might fork your repo and give a try.

**Comment by domoritz** [comment]
You need to add a parser, type, and formatter for functions. You can look at the existing types we support.

**Comment by sramam** [comment]
@apiel,  have you considered creating an interface to wrap the input arguments?

Here's what I mean:

```
export interface GetListInput {
    foo: string;
}

// An interface to define the InputParams to the function.
export interface InputParams {
  input: GetListInput;
  input2: string;
}

export function getList({input, input2}: InputParams) {
    // some code
}

```

If `getList` is not a function under your control,
```
export const wrapGetList = ({input, input2}: InputParams) => getList(input, input2);
```

**Comment by apiel** [comment]
Yes I thought about it but it doesn't really fit with what I want to achieve. I work on a tool to automatically generate the communication protocole between backend and frontend https://github.com/apiel/isomor , and since I am as using a transpiler for it, I though it would be great to check for types in the generated endpoints. 
Also I could use the JSON schema to improve the generated swagger documentation.

**Comment by apiel** [comment]
I somehow get it to work:
https://github.com/apiel/ts-json-schema-generator/commit/010ce2dbebe4931e589ec06f52198fd1b2a5948e

now I am not so sure about if I need the `withCircular`. Also the `getTypeId` I am not really sure about what I did...

`yarn run run --path ~/test/endpoint.ts --type getList` (I would recommand you to change the script `run` to something else, doesn't work well with yarn)

result to:
```
{
  "$ref": "#/definitions/getList",
  "$schema": "http://json-schema.org/draft-06/schema#",
  "definitions": {
    "GetListInput": {
      "additionalProperties": false,
      "properties": {
        "foo": {
          "type": "string"
        }
      },
      "required": [
        "foo"
      ],
      "type": "object"
    },
    "getList": {
      "additionalProperties": false,
      "properties": {
        "input": {
          "$ref": "#/definitions/GetListInput"
        }
      },
      "required": [
        "input"
      ],
      "type": "object"
    }
  }
``` 
I will then do the same for arrowFunction (and try as well with class method).
Is there any chance to merged a PR to your repo or would it be out of scope?

**Comment by apiel** [comment]
Here is the last version https://github.com/apiel/isomor/blob/master/packages/isomor-json-schema-generator/src/NodeParser/FuncTypeNodeParser.ts

and https://github.com/apiel/isomor/blob/master/packages/isomor-json-schema-generator/src/SchemaGenerator.ts#L74

But after making some research, I think I should have used tuple validation: https://json-schema.org/understanding-json-schema/reference/array.html#tuple-validation

Would be great to get this code merge, then I would not need my custom repo. Please let me know which kind of changes I need to do, to make it mergeable...

**Comment by domoritz** [comment]
I don't plan to support functions until json schema has support for them and ajv also validates them.

**Comment by apiel** [comment]
What's about tuple validation for array? https://json-schema.org/understanding-json-schema/reference/array.html#tuple-validation

**Comment by domoritz** [comment]
That would make sense. I haven't checked, but we may already support it.

**Comment by paztis** [comment]
There's something wrong here: you are only mapping the input parameters of the function, not the output 
It can be void or something else.

In your schema representation, how do you want to represent it ?

I'm really interested to use or develop it if we found a correct representation of a method / function here
