### ISSUE TITLE
exclude single file from --path ?

### ISSUE THREAD

**Issue by tomdavidson** [vega/ts-json-schema-generator#987]
Hello and thank you!

I'd like to do something along the lines of ` --path 'src/!(app)*.ts' ` but am not figuring out a negate option.
Any options to include `*.ts` but leave out `app.ts`?

Its a different issue, but the reason I need to exclude `app.ts` is due to:

```shell
Error: Unknown node "() => {" (ts.SyntaxKind = 212)
```

on `err` in (with our without the explicit type):
```js
  (err: NodeJS.ErrnoException) => {
    if (err) {
```

**Comment by domoritz** [comment]
Can you use a tsconfig file to load only the files you want?

**Comment by tomdavidson** [comment]
Yes, I could have a separate tsconfig for the schema gen. Thanks.

**Comment by tomdavidson** [comment]
Didn't quite work, I must be missing something:

```json
{
  "extends": "./tsconfig.json",
  "exclude": ["node_modules", "dist", "src/app.ts"]
}
```

```shell
$ npx ts-json-schema-generator --tsconfig tsconfig-genschemata.json --path src/*.ts --no-type-check --out src/schemata.json
Error: Unknown node "(err: NodeJS.ErrnoException) => {" (ts.SyntaxKind = 212) at src/app.ts(99,2)

$ npx ts-json-schema-generator -f tsconfig-genschemata.json  --no-type-check --out src/schemata.json
NoRootNamesError: No source files found
```

**Comment by tomdavidson** [comment]
aah looks related to #976 and #979

**Comment by tomdavidson** [comment]
@domoritz The break happens with v0.94.1. The following works great.

```shell
npx ts-json-schema-generator@v0.94.0 --tsconfig tsconfig-genschemata.json  --no-type-check --out src/schemata.json
````

Is this the same issue in #976 and #979?

**Comment by domoritz** [comment]
Could be. Can you try the release from #979?

**Comment by tomdavidson** [comment]
Oh cool, I didnt realize there was a released canary. You made getting some feedback super easy. The canary works with path but not with the custom tsconfig.

```shell
$ npx ts-json-schema-generator@v0.96.1--canary.979.fe4869a.0 --tsconfig tsconfig-genschemata.json  --no-type-check --out src/schemata.json
Error: Unknown node "() => {" (ts.SyntaxKind = 212) at /home/tom/Documents/affrim-take-home/src/offer.spec.ts(4,29)

$ npx ts-json-schema-generator@v0.96.1--canary.979.fe4869a.0  --path src/*.ts  --no-type-check --out src/schemata.json
```

But now the schema looks like this with exported functions, not types:

```json
"definitions": {
 "NamedParameters<typeof writeAssignments>": {
      "additionalProperties": false,
      "properties": {
        "filePath": {
          "type": "string"
        }
      },
      "required": [
        "filePath"
      ],
      "type": "object"
    }
```
Rather than the actual types such as:

```json
"definitions": {
    "Rate": {
      "description": "Rate 0-1",
      "maximum": 1,
      "minimum": 0,
      "type": "number"
    },
```

**Comment by domoritz** [comment]
Thanks for the canaries goes to @hydrosquall for setting it up.

If you could debug the issue, that would be great. I won't have the cycles to dig into it unfortunately.
